In [6]:
from nltk.corpus import stopwords

#stopwords.words('english')

In [7]:
from sqlalchemy import create_engine
import pandas as pd
import re
import string
import nltk
pd.set_option('display.max_colwidth', 100)

In [8]:
QUERY=""" 
with business_categories as (
select  bc.business_detail_id
,listagg(c.name,'|') within group (order by c.name) as categories
from mysql_oneflare_production.business_categories bc 
left join mysql_oneflare_production.categories c on bc.category_id = c.id
group by 1
)

SELECT
trim(nvl(bm.name,'') || ' ' || nvl(description,'')) "feature"
,bc.categories
,category_name "label"
FROM oneflare_reports.business_master bm
left join business_categories bc on bm.id = bc.business_detail_id
WHERE bm.total_quotes_made >= 3 and category_name is not null
"""

In [9]:
def make_engine():
    user = 'xxx' # change it to your username
    pw = 'xxx' #change it to your password
    db_name = 'snowplow'
    host = 'redshift.oneflare.io'
    port = 5439
    engine_string = "postgresql://%s:%s@%s:%s/%s" % (
        user, pw, host, port, db_name)
    engine = create_engine(engine_string)
    return engine

redshift = make_engine()
data=pd.read_sql(QUERY,redshift)

In [11]:
data.head()

,feature,categories,label
0,"S.F.D Caringbah We are on time and on budget.\nWe have experience in new homes, renovations and ...",Bathroom Renovations|Builder|Carpenter|Decking|Gazebo|Home Renovation|Kitchen Renovations|Pergola,Handyman
1,Gardeners@Work I specialise in all types of fencing and gates.\nGardeners@Work construct quality...,Fencing|Gardener|Lawn Mowing|Tree Lopping,Gardener
2,"Melbourne Computer And Business Consultants Hi, I offer services for home and small business com...",Computer Repair,Computer Repair
3,Looker Electrics Looker Electrics providing the very best electrical contracting services.\nI sp...,Electrician,Air Conditioning and Heating
4,Wire Not Electrical Pty Ltd Wire-Not Electrical is an awarding winning locally-owned and operate...,Electrician,Security System

In [13]:
stopwords = nltk.corpus.stopwords.words('english')
wn = nltk.WordNetLemmatizer()
ps = nltk.PorterStemmer()

In [7]:
features_importances_df=pd.read_csv('features_importances.csv')
import_features_list=list(features_importances_df['feature'])
len(import_features_list)

38077

In [5]:
bool(re.search('\d','a3bc'))

True

In [14]:
def clean_text_by_porter_stem(text):

    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if (word not in stopwords) and (word.isdigit() ==False)  ]
    #text = [ word for word in text if word in import_features_list]
    
    return text

def multiLabelBinarizer(text):
    if text is None: 
        return ['']
    categories = re.split('\|', text)
    return categories

def clean_text_by_wordnet_lemmatize(text):

    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [wn.lemmatize(word)  for word in tokens if (word not in stopwords) and (word.isdigit() ==False)] 
    text = [ word for word in text if word in import_features_list]
    
    return text

In [13]:
#data.drop('feature_cleaned', axis=1, inplace=True)

In [28]:
data['feature_cleaned_ps']=data['feature'].apply(lambda x: clean_text_by_porter_stem( ('' if x is None else x).lower()))
data['feature_cleaned_wd']=data['feature'].apply(lambda x: clean_text_by_wordnet_lemmatize( ('' if x is None else x).lower()))

In [29]:
data.head()

,feature,label,feature_cleaned_ps,feature_cleaned_wd
0,"Anaxim Accounting Solutions The company is a qualified, professional accountant who deals with a...",Accountant,"[anaxim, account, solut, compani, qualifi, profession, account, deal, array, account, issu, prov...","[anaxim, accounting, solution, company, qualified, professional, accountant, deal, array, accoun..."
1,RCS Websites Let RCS Websites breath life in to your existing website!\r\nOur websites are simpl...,SEO and SEM,"[rc, websit, let, rc, websit, breath, life, exist, websit, websit, simpl, clean, profession, sur...","[rcs, website, let, rcs, website, breath, life, existing, website, website, simple, clean, profe..."
2,Intouch Carpet Cleaning Services InTouch Carpet and Pest Control is a family owned business who ...,Pest Control,"[intouch, carpet, clean, servic, intouch, carpet, pest, control, famili, own, busi, valu, old, f...","[intouch, carpet, cleaning, service, intouch, carpet, pest, control, family, owned, business, va..."
3,Shannon Thomas Carpenter Licensed Carpenter\r\n - Small Decks and Pergolas as well as re deck...,Carpenter,"[shannon, thoma, carpent, licens, carpent, small, deck, pergola, well, deck, repair, attent, det...","[shannon, thomas, carpenter, licensed, carpenter, small, deck, pergola, well, decking, repair, a..."
4,"M&M Cabinets Custom-made Cabinets for kitchen, laundries, bathroom and anywhere in your house. 3...",Builder,"[mm, cabinet, custommad, cabinet, kitchen, laundri, bathroom, anywher, hous, 3d, comput, draw, a...","[mm, cabinet, custommade, cabinet, kitchen, laundry, bathroom, anywhere, house, 3d, computer, dr..."

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [16]:

count_vectorizer_categories = CountVectorizer(analyzer=multiLabelBinarizer)
count_vectorized_matrix_categories = count_vectorizer_categories.fit_transform(data['categories'] )

tfidf_vectorizer_ps = TfidfVectorizer(analyzer=clean_text_by_porter_stem)
tfidf_vectorized_matrix_ps = tfidf_vectorizer_ps.fit_transform(data['feature'] )

In [11]:
count_vectorizer_ps = CountVectorizer(analyzer=clean_text_by_porter_stem)
count_vectorized_matrix_ps = count_vectorizer_ps.fit_transform(data['feature'] )

In [17]:
count_vectorized_matrix_categories.shape

(39081, 139)

In [18]:
tfidf_vectorized_matrix_ps.shape

(39081, 48735)

In [19]:
from scipy.sparse import coo_matrix, hstack
import pandas as pd

print(pd.DataFrame(hstack([tfidf_vectorized_matrix_ps[0:10],count_vectorized_matrix_categories[0:10]], format='csr').toarray()))
type(hstack([tfidf_vectorized_matrix_ps[0:10],count_vectorized_matrix_categories[0:10]], format='csr'))

vectorized_matrix = hstack([tfidf_vectorized_matrix_ps,count_vectorized_matrix_categories], format='csr')

   0      1      2      3      4      5      6      7      8      9      \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
7    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
8    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
9    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

   ...    48864  48865  48866  48867  48868  48869  48870  48871  48872  48873
0  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
1  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
7  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
8  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
9  ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

[10 rows x 48874 columns]

In [21]:
tfidf_vectorized_df_ps = pd.DataFrame(tfidf_vectorized_matrix_ps.toarray())

MemoryError:

In [18]:
tfidf_vectorized_df_ps.head()

,0,1,2,3,4,5,6,7,8,9,...,48564,48565,48566,48567,48568,48569,48570,48571,48572,48573
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
tfidf_vectorizer_wn = TfidfVectorizer(analyzer=clean_text_by_wordnet_lemmatize)
tfidf_vectorized_matrix_wn = tfidf_vectorizer_wn.fit_transform(data['feature'])

In [10]:
tfidf_vectorized_matrix_wn.shape

(38974, 56825)

In [ ]:
tfidf_vectorizer_wn = TfidfVectorizer(analyzer=clean_text_by_wordnet_lemmatize)
tfidf_vectorized_matrix_wn = tfidf_vectorizer_wn.fit_transform(data['feature'])
tfidf_vectorized_df_wn = pd.DataFrame(tfidf_vectorized_matrix_wn.toarray())

In [19]:
tfidf_vectorized_df_ps_h = tfidf_vectorized_df_ps
tfidf_vectorized_df_ps_h.columns = tfidf_vectorizer_ps.get_feature_names()
tfidf_vectorized_df_ps_h.head()

,,00,000107l,000684l,000710l,001023l,01000sqm,0118651a01,012km,024481i,...,ўвўfrighten,ўвўhave,ўвўin,ўёўў,ўўв,中國理解,在墨尔本的中国婚礼乐队,ﬁnanc,ﬁnancial,ﬁngertip
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import precision_recall_fscore_support as score
import time

## Start to evaluate models

In [21]:
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(vectorized_matrix, data['label'], test_size=0.2)

In [23]:
def train_RF(n_est, depth):
    rf = RandomForestClassifier(n_estimators=n_est, max_depth=depth, n_jobs=-1, verbose=10)
    rf_model = rf.fit(X_train, y_train)
    y_pred = rf_model.predict(X_test)
    precision, recall, fscore, support = score(y_test, y_pred)
    print('Est: {} / Depth: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
        n_est, depth, precision, recall,
        round((y_pred==y_test).sum() / len(y_pred), 3)))

In [24]:
from ipywidgets import FloatProgress
from IPython.display import display

In [25]:
max_count = 12
count = 0
progressBar = FloatProgress(min=0, max=max_count)
display(progressBar)

for n_est in [50, 10, 300]:
    for depth in [10, 20, 30, None]:
        print("\n\nTraining combination: n_est:{n_est} - depth:{depth}".format(n_est=str(n_est),depth=str(depth)))
        progressBar.value+=1
        count += 1
        train_RF(n_est, depth)

A Jupyter Widget

Training combination: n_est:50 - depth:10
building tree 1 of 50
building tree 2 of 50building tree 4 of 50
building tree 3 of 50

building tree 5 of 50
building tree 6 of 50
building tree 7 of 50
building tree 8 of 50
building tree 9 of 50
building tree 10 of 50
building tree 11 of 50
building tree 12 of 50
building tree 13 of 50

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    0.5s

building tree 14 of 50
building tree 15 of 50
building tree 16 of 50
building tree 17 of 50
building tree 18 of 50
building tree 19 of 50
building tree 20 of 50
building tree 21 of 50
building tree 22 of 50
building tree 23 of 50

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    0.8s

building tree 24 of 50
building tree 25 of 50
building tree 26 of 50
building tree 27 of 50
building tree 28 of 50
building tree 29 of 50
building tree 30 of 50
building tree 31 of 50
building tree 32 of 50

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    1.2s

building tree 33 of 50
building tree 34 of 50
building tree 35 of 50
building tree 36 of 50
building tree 37 of 50

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    1.7s

building tree 38 of 50
building tree 39 of 50
building tree 40 of 50
building tree 41 of 50
building tree 42 of 50
building tree 43 of 50
building tree 44 of 50
building tree 45 of 50

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    2.2s

building tree 46 of 50
building tree 47 of 50
building tree 48 of 50
building tree 49 of 50
building tree 50 of 50

[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    2.5s finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  50 out of  50 | elapsed:    0.3s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 10 ---- Precision: [ 0.82608696  0.          0.70833333  0.          0.33333333  0.          0.
  0.          0.          0.          0.87804878  0.16482412  0.          0.
  0.          0.          0.          0.          0.          1.
  0.88679245  0.          0.95967742  0.          0.46888412  0.79005525
  0.82278481  0.94444444  0.          0.          0.79069767  0.5         0.
  0.77777778  0.          0.          0.65789474  0.          0.69318182
  0.          0.          0.          0.50445104  0.          1.
  0.72727273  0.          0.          0.          0.          0.          1.
  0.          0.6         0.          0.          0.          0.47019868
  0.94444444  0.71428571  0.          1.          0.          0.8         0.
  0.          0.          0.          0.          0.92227979  0.91489362
  0.          0.94366197  0.          0.64571429  0.          0.
  0.71823204  0.          0.          0.          0.          0.          0.
  0.83246073  0.          0.          0.          0.47368421  1.          0.
  0.          0.40804598  0.          0.          1.          0.          0.65625
  0.          0.          0.80645161  1.          0.66666667  1.          0.
  0.          0.          0.45578231  1.          0.          0.          0.
  0.          0.          1.          1.        ] / Recall: [ 0.99723757  0.          0.41463415  0.          0.02173913  0.          0.
  0.          0.          0.          0.70588235  0.9609375   0.          0.
  0.          0.          0.          0.          0.          0.01010101
  0.63513514  0.          0.93700787  0.          0.98202247  1.
  0.34946237  0.32692308  0.          0.          0.60714286  0.00460829
  0.          0.2         0.          0.          0.23148148  0.
  0.62244898  0.          0.          0.          0.80952381  0.
  0.53658537  0.1         0.          0.          0.          0.          0.
  0.02068966  0.          0.0212766   0.          0.          0.
  0.89873418  0.49275362  0.79207921  0.          0.07692308  0.
  0.03149606  0.          0.          0.          0.          0.          1.
  0.89583333  0.          0.84810127  0.          0.96170213  0.          0.
  0.96296296  0.          0.          0.          0.          0.          0.
  0.98148148  0.          0.          0.          0.65060241  0.14814815
  0.          0.          0.69268293  0.          0.          0.01960784
  0.          0.80769231  0.          0.          0.17605634  0.88888889
  0.0754717   0.00980392  0.          0.          0.          0.69791667
  0.04545455  0.          0.          0.          0.          0.
  0.01075269  0.1       ] / Accuracy: 0.467


Training combination: n_est:50 - depth:20
building tree 1 of 50building tree 2 of 50building tree 4 of 50building tree 3 of 50



building tree 5 of 50
building tree 6 of 50
building tree 7 of 50
building tree 8 of 50

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    1.0s

building tree 9 of 50building tree 10 of 50

building tree 11 of 50
building tree 12 of 50
building tree 13 of 50
building tree 14 of 50
building tree 15 of 50
building tree 16 of 50

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    1.5s

building tree 17 of 50
building tree 18 of 50
building tree 19 of 50
building tree 20 of 50
building tree 21 of 50
building tree 22 of 50
building tree 23 of 50
building tree 24 of 50

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    2.7s

building tree 25 of 50
building tree 26 of 50
building tree 27 of 50
building tree 28 of 50

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    3.4s

building tree 29 of 50
building tree 30 of 50
building tree 31 of 50
building tree 32 of 50
building tree 33 of 50building tree 34 of 50

building tree 35 of 50
building tree 36 of 50
building tree 37 of 50
building tree 38 of 50
building tree 39 of 50
building tree 40 of 50

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    4.9s

building tree 41 of 50
building tree 42 of 50
building tree 43 of 50
building tree 44 of 50
building tree 45 of 50
building tree 46 of 50
building tree 47 of 50

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    6.0s

building tree 48 of 50
building tree 49 of 50
building tree 50 of 50

[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    7.0s finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  50 out of  50 | elapsed:    0.2s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 20 ---- Precision: [ 0.87378641  0.84        0.7804878   0.          0.5         0.62962963
  0.          1.          0.          0.          0.90697674  0.25067096
  0.          1.          0.          0.          0.96774194  0.          0.
  0.82        0.90123457  0.          0.91666667  1.          0.52722772
  0.79329609  0.69832402  0.77777778  0.93333333  0.          0.72463768
  0.34782609  0.          0.78378378  0.68        0.14285714  0.57777778
  0.          0.70114943  0.          0.          0.          0.42729306
  0.          1.          0.53061224  0.          0.25        0.          0.
  0.          0.          0.          0.52        0.          1.          0.
  0.46625767  0.79452055  0.71126761  0.66666667  0.8         0.
  0.39461883  1.          0.07692308  0.          0.          0.
  0.83568075  0.875       0.          0.89534884  0.625       0.6442577   0.
  0.          0.72357724  0.          0.          0.          0.          0.
  0.          0.76923077  0.          0.          0.          0.46315789
  0.90909091  0.          0.          0.38799076  0.          0.
  0.91666667  0.          0.78571429  0.          0.          0.72180451
  1.          0.48387097  0.66666667  0.          0.          0.
  0.44776119  1.          0.          0.          0.          0.          0.
  0.8         1.        ] / Recall: [ 0.99447514  0.72413793  0.3902439   0.          0.10869565  0.32075472
  0.          0.05263158  0.          0.          0.76470588  0.91210938
  0.          0.06976744  0.          0.          0.53571429  0.          0.
  0.20707071  0.98648649  0.          0.95275591  0.20833333  0.95730337
  0.99300699  0.67204301  0.80769231  0.4         0.          0.89285714
  0.03686636  0.          0.82857143  0.4047619   0.02380952  0.24074074
  0.          0.62244898  0.          0.          0.          0.90952381
  0.          0.73170732  0.325       0.          0.01685393  0.          0.
  0.          0.          0.          0.09219858  0.          0.06896552
  0.          0.96202532  0.84057971  1.          0.11764706  0.61538462
  0.          0.69291339  0.5         0.00675676  0.          0.          0.
  1.          0.94791667  0.          0.97468354  0.19230769  0.9787234   0.
  0.          0.98888889  0.          0.          0.          0.          0.
  0.          0.98765432  0.          0.          0.          0.53012048
  0.37037037  0.          0.          0.8195122   0.          0.
  0.64705882  0.          0.63461538  0.          0.          0.67605634
  0.38888889  0.28301887  0.03921569  0.          0.          0.          0.625
  0.54545455  0.          0.          0.          0.          0.
  0.08602151  0.6       ] / Accuracy: 0.552


Training combination: n_est:50 - depth:30
building tree 1 of 50
building tree 2 of 50building tree 3 of 50building tree 4 of 50


building tree 5 of 50
building tree 6 of 50
building tree 7 of 50
building tree 8 of 50

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    2.0s

building tree 9 of 50
building tree 10 of 50
building tree 11 of 50
building tree 12 of 50
building tree 13 of 50
building tree 14 of 50
building tree 15 of 50
building tree 16 of 50

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    3.4s

building tree 17 of 50
building tree 18 of 50
building tree 19 of 50
building tree 20 of 50

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    5.4s

building tree 21 of 50
building tree 22 of 50
building tree 23 of 50
building tree 24 of 50
building tree 25 of 50
building tree 26 of 50
building tree 27 of 50

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    6.9s

building tree 28 of 50
building tree 29 of 50
building tree 30 of 50
building tree 31 of 50
building tree 32 of 50
building tree 33 of 50
building tree 34 of 50
building tree 35 of 50
building tree 36 of 50
building tree 37 of 50

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   10.2s

building tree 38 of 50
building tree 39 of 50
building tree 40 of 50
building tree 41 of 50
building tree 42 of 50
building tree 43 of 50
building tree 44 of 50
building tree 45 of 50

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   12.8s

building tree 46 of 50
building tree 47 of 50
building tree 48 of 50
building tree 49 of 50
building tree 50 of 50

[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   14.7s finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  50 out of  50 | elapsed:    0.2s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 30 ---- Precision: [ 0.89330025  0.84615385  0.74107143  0.69230769  0.63157895  0.73076923
  0.          0.66666667  0.          0.          0.83333333  0.37184703
  0.          0.8         0.          0.          0.95918367  1.          0.
  0.80555556  0.86046512  0.          0.86206897  1.          0.57201087
  0.8150289   0.64830508  0.77358491  1.          0.          0.73239437
  0.38235294  0.          0.83783784  0.6         0.82758621  0.58730159
  0.          0.66990291  1.          0.          1.          0.49009901
  0.          0.97222222  0.53164557  1.          0.21052632  0.6         0.
  0.          0.39285714  1.          0.63157895  0.          1.          1.
  0.48148148  0.77380952  0.67785235  0.          0.875       0.
  0.38554217  1.          0.25438596  0.          0.5         0.
  0.91666667  0.85981308  1.          0.875       0.375       0.63920455
  0.          0.          0.76149425  0.          0.          0.
  0.63636364  1.          0.77777778  0.77560976  0.5         0.          0.
  0.48031496  0.84848485  0.          0.          0.40470588  0.          0.
  0.74545455  0.          0.78846154  0.          0.          0.68531469
  1.          0.525       0.66666667  0.          0.          0.
  0.47328244  1.          0.          0.          1.          1.          0.
  0.9047619   1.        ] / Recall: [ 0.99447514  0.75862069  0.50609756  0.45        0.26086957  0.35849057
  0.          0.10526316  0.          0.          0.88235294  0.89257812
  0.          0.27906977  0.          0.          0.83928571  0.66666667
  0.          0.29292929  1.          0.          0.98425197  0.66666667
  0.94606742  0.98601399  0.82258065  0.78846154  0.05714286  0.
  0.92857143  0.1797235   0.          0.88571429  0.5         0.57142857
  0.34259259  0.          0.70408163  0.03703704  0.          0.25
  0.94285714  0.          0.85365854  0.525       0.08        0.04494382
  0.05263158  0.          0.          0.15172414  0.45        0.34042553
  0.          0.10344828  0.09090909  0.98734177  0.94202899  1.          0.
  0.53846154  0.          0.75590551  0.4         0.19594595  0.
  0.01923077  0.          0.98876404  0.95833333  0.09090909  0.97468354
  0.23076923  0.95744681  0.          0.          0.98148148  0.          0.
  0.          0.25        0.03703704  0.36842105  0.98148148  0.01492537
  0.          0.          0.73493976  0.51851852  0.          0.
  0.83902439  0.          0.          0.80392157  0.          0.78846154
  0.          0.          0.69014085  0.38888889  0.39622642  0.03921569
  0.          0.          0.          0.64583333  0.63636364  0.          0.
  0.05454545  0.05        0.          0.20430108  0.8       ] / Accuracy: 0.606


Training combination: n_est:50 - depth:None
building tree 1 of 50building tree 2 of 50

building tree 3 of 50building tree 4 of 50

building tree 5 of 50
building tree 6 of 50
building tree 7 of 50
building tree 8 of 50

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   15.4s

building tree 9 of 50
building tree 10 of 50
building tree 11 of 50
building tree 12 of 50
building tree 13 of 50
building tree 14 of 50

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   23.6s

building tree 15 of 50
building tree 16 of 50
building tree 17 of 50
building tree 18 of 50
building tree 19 of 50
building tree 20 of 50
building tree 21 of 50
building tree 22 of 50
building tree 23 of 50

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   40.2s

building tree 24 of 50
building tree 25 of 50
building tree 26 of 50
building tree 27 of 50
building tree 28 of 50

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   48.5s

building tree 29 of 50
building tree 30 of 50
building tree 31 of 50
building tree 32 of 50
building tree 33 of 50
building tree 34 of 50
building tree 35 of 50
building tree 36 of 50
building tree 37 of 50building tree 38 of 50

building tree 39 of 50

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.2min

building tree 40 of 50
building tree 41 of 50
building tree 42 of 50
building tree 43 of 50
building tree 44 of 50
building tree 45 of 50
building tree 46 of 50

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.5min

building tree 47 of 50
building tree 48 of 50
building tree 49 of 50
building tree 50 of 50

[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.8min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done  50 out of  50 | elapsed:    0.4s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: None ---- Precision: [ 0.96266667  0.84615385  0.66666667  0.75        0.42857143  0.54411765
  0.62962963  1.          0.          0.5         0.78947368  0.55637255
  0.          0.76470588  0.          1.          0.93103448  1.          0.3125
  0.7244898   0.91358025  0.          0.93333333  0.94117647  0.62992126
  0.83040936  0.69469027  0.8125      0.83333333  0.          0.76388889
  0.34810127  0.66666667  0.88571429  0.72222222  0.73684211  0.54411765
  0.83333333  0.68571429  0.55555556  0.66666667  0.          0.56231003
  0.          0.92682927  0.61363636  0.53846154  0.37634409  0.6
  0.11764706  0.5         0.34343434  1.          0.55737705  0.
  0.71428571  0.875       0.49006623  0.8         0.81451613  1.
  0.92307692  1.          0.42512077  1.          0.28654971  0.6
  0.77777778  0.          0.96216216  0.94897959  0.5         0.91666667
  0.625       0.69453376  1.          0.42857143  0.82018927  0.75
  0.88888889  0.          0.57894737  0.92        0.92857143  0.8579235
  0.41666667  0.          0.          0.46721311  0.87878788  0.          1.
  0.43126685  0.          0.          0.82352941  1.          0.75862069
  1.          0.72222222  0.74825175  1.          0.41538462  0.52380952
  0.25        1.          1.          0.53030303  0.95238095  1.
  0.33333333  0.8         0.8         1.          0.75925926  1.        ] / Recall: [ 0.99723757  0.75862069  0.51219512  0.75        0.13043478  0.69811321
  0.62962963  0.47368421  0.          0.375       0.88235294  0.88671875
  0.          0.60465116  0.          0.11111111  0.96428571  0.83333333
  0.1         0.35858586  1.          0.          0.99212598  0.66666667
  0.8988764   0.99300699  0.84408602  0.75        0.57142857  0.
  0.98214286  0.25345622  0.13333333  0.88571429  0.61904762  0.66666667
  0.34259259  0.38461538  0.73469388  0.18518519  0.5         0.
  0.88095238  0.          0.92682927  0.675       0.28        0.19662921
  0.15789474  0.02857143  0.04081633  0.23448276  0.9         0.4822695   0.
  0.34482759  0.63636364  0.93670886  0.92753623  1.          0.05882353
  0.92307692  0.2         0.69291339  0.9         0.33108108  0.2
  0.26923077  0.          1.          0.96875     0.45454545  0.97468354
  0.57692308  0.91914894  0.42857143  0.140625    0.96296296  0.42857143
  0.61538462  0.          0.39285714  0.85185185  0.68421053  0.9691358
  0.2238806   0.          0.          0.68674699  0.53703704  0.          1.
  0.7804878   0.          0.          0.82352941  0.38888889  0.84615385
  0.2173913   0.59090909  0.75352113  0.88888889  0.50943396  0.10784314
  0.01666667  0.33333333  0.42105263  0.72916667  0.90909091  0.8         0.03125
  0.14545455  0.4         0.57142857  0.44086022  1.        ] / Accuracy: 0.665


Training combination: n_est:10 - depth:10
building tree 1 of 10
building tree 2 of 10building tree 3 of 10building tree 4 of 10


building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10
building tree 9 of 10

[Parallel(n_jobs=-1)]: Done   5 out of  10 | elapsed:    0.3s remaining:    0.3s
[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:    0.4s remaining:    0.1s

building tree 10 of 10

[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    0.6s finished
[Parallel(n_jobs=4)]: Done   5 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   7 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.0s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 10 ---- Precision: [ 0.62003454  0.          0.55279503  0.          0.          0.          0.
  0.42857143  0.          0.          0.          0.12866016  0.
  0.55172414  0.          0.          0.          0.          0.
  0.61538462  0.91358025  0.          0.94656489  0.          0.47786606
  0.73913043  0.73758865  0.69491525  0.          0.          0.83928571
  0.17647059  0.          0.68181818  0.35294118  0.5         0.28571429
  0.          0.61111111  0.33333333  0.          0.          0.40393013
  0.          1.          0.5         0.          0.2         0.          0.
  0.          0.28571429  0.          0.5         0.          0.25        0.
  0.43478261  0.9         0.74418605  0.          0.          0.
  0.33333333  0.          0.          0.          0.          0.
  0.95698925  0.7826087   0.          0.54081633  0.          0.60555556
  0.          0.          0.59259259  0.          0.          0.          0.
  1.          0.2         0.67826087  0.          0.          0.
  0.28571429  0.          0.          0.          0.4         0.          0.
  0.74545455  0.          0.          0.          0.          0.64539007
  0.          0.28571429  0.27272727  0.          0.          0.
  0.45833333  0.          0.          0.          0.66666667  0.          0.
  0.125       0.        ] / Recall: [ 0.99171271  0.          0.54268293  0.          0.          0.          0.
  0.31578947  0.          0.          0.          0.84960938  0.
  0.37209302  0.          0.          0.          0.          0.
  0.04040404  1.          0.          0.97637795  0.          0.94606742
  0.23776224  0.55913978  0.78846154  0.          0.          0.83928571
  0.01382488  0.          0.85714286  0.14285714  0.02380952  0.01851852
  0.          0.1122449   0.03703704  0.          0.          0.88095238
  0.          0.02439024  0.025       0.          0.00561798  0.          0.
  0.          0.0137931   0.          0.0212766   0.          0.03448276
  0.          0.12658228  0.65217391  0.95049505  0.          0.          0.
  0.03937008  0.          0.          0.          0.          0.          1.
  0.75        0.          0.67088608  0.          0.92765957  0.          0.
  0.41481481  0.          0.          0.          0.          0.07407407
  0.10526316  0.48148148  0.          0.          0.          0.04819277
  0.          0.          0.          0.14634146  0.          0.
  0.80392157  0.          0.          0.          0.          0.64084507
  0.          0.03773585  0.02941176  0.          0.          0.
  0.11458333  0.          0.          0.          0.03636364  0.          0.
  0.02150538  0.        ] / Accuracy: 0.392


Training combination: n_est:10 - depth:20
building tree 1 of 10building tree 2 of 10

building tree 3 of 10
building tree 4 of 10
building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10

[Parallel(n_jobs=-1)]: Done   5 out of  10 | elapsed:    1.2s remaining:    1.2s
[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:    1.3s remaining:    0.5s

building tree 9 of 10
building tree 10 of 10

[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    1.8s finished
[Parallel(n_jobs=4)]: Done   5 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   7 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.0s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 20 ---- Precision: [ 0.77559913  0.33333333  0.58163265  0.          0.30769231  0.52941176
  0.57142857  0.66666667  0.          0.          0.72413793  0.19175455
  0.66666667  0.875       0.          0.          0.72093023  0.          0.
  0.71084337  0.90243902  0.          0.86764706  0.          0.51698113
  0.74193548  0.66463415  0.73809524  0.73076923  0.          0.50980392
  0.21052632  0.          0.58974359  0.4         0.33333333  0.42666667
  0.16666667  0.57281553  0.5         0.          0.          0.45244957
  0.          0.          0.52941176  0.25        0.18918919  0.2         0.
  0.          0.28947368  1.          0.25806452  0.          0.75        1.
  0.42056075  0.70833333  0.4         1.          0.6         0.
  0.44736842  0.          0.11111111  0.          0.          0.
  0.76190476  0.875       0.          0.84146341  0.25        0.57435897
  0.          0.          0.65194805  0.          0.          0.2         1.
  0.          0.          0.69480519  0.          0.          0.
  0.26666667  0.7         0.28571429  0.          0.37567568  0.          0.
  0.375       0.          0.63333333  0.          0.          0.5739645
  0.86666667  0.34146341  0.18181818  0.          0.          0.5
  0.43518519  0.          0.          0.          0.36363636  0.25        0.
  0.28571429  0.        ] / Recall: [ 0.98342541  0.03448276  0.34756098  0.          0.08695652  0.33962264
  0.44444444  0.10526316  0.          0.          0.82352941  0.78125
  0.0952381   0.1627907   0.          0.          0.55357143  0.          0.
  0.2979798   1.          0.          0.92913386  0.          0.92359551
  0.64335664  0.58602151  0.59615385  0.54285714  0.          0.46428571
  0.07373272  0.          0.65714286  0.0952381   0.04761905  0.2962963
  0.07692308  0.60204082  0.18518519  0.          0.          0.74761905
  0.          0.          0.225       0.04        0.03932584  0.01754386
  0.          0.          0.07586207  0.6         0.05673759  0.
  0.10344828  0.18181818  0.56962025  0.73913043  0.33663366  0.11764706
  0.23076923  0.          0.4015748   0.          0.00675676  0.          0.
  0.          0.98876404  0.94791667  0.          0.87341772  0.03846154
  0.95319149  0.          0.          0.92962963  0.          0.
  0.09090909  0.03571429  0.          0.          0.66049383  0.          0.
  0.          0.04819277  0.25925926  0.06060606  0.          0.67804878
  0.          0.          0.05882353  0.          0.73076923  0.          0.
  0.68309859  0.72222222  0.26415094  0.01960784  0.          0.
  0.05263158  0.48958333  0.          0.          0.          0.07272727
  0.05        0.          0.02150538  0.        ] / Accuracy: 0.476


Training combination: n_est:10 - depth:30
building tree 2 of 10building tree 3 of 10building tree 4 of 10building tree 1 of 10



building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10

[Parallel(n_jobs=-1)]: Done   5 out of  10 | elapsed:    2.2s remaining:    2.2s

building tree 9 of 10
building tree 10 of 10

[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:    2.6s remaining:    1.1s
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    3.4s finished
[Parallel(n_jobs=4)]: Done   5 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   7 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.0s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 30 ---- Precision: [ 0.89108911  0.61290323  0.64705882  0.66666667  0.5         0.515625    0.
  0.88888889  0.          0.          0.69767442  0.31536189  0.
  0.77777778  1.          0.          0.83673469  0.          0.13333333
  0.57142857  0.91139241  0.          0.87586207  0.5         0.54794521
  0.68269231  0.65445026  0.78947368  0.72727273  0.          0.7260274
  0.2238806   0.          0.68292683  0.52380952  1.          0.39240506
  1.          0.52136752  0.42857143  0.          0.          0.50859107
  0.          0.88888889  0.44578313  0.4         0.20987654  0.18181818
  0.          0.          0.15384615  0.75        0.11764706  0.          0.4
  0.          0.47445255  0.75        0.73484848  0.          0.83333333
  0.          0.31363636  1.          0.13793103  0.          0.13636364
  0.          0.84210526  0.82300885  0.          0.7254902   0.27272727
  0.59714286  0.          0.06666667  0.72980501  0.          0.          0.
  0.2         0.66666667  0.77777778  0.67553191  0.25        0.          0.
  0.37755102  0.55172414  0.25        1.          0.38501292  0.          0.
  0.79545455  0.          0.63235294  0.          0.59259259  0.64925373
  1.          0.23809524  0.17647059  0.          0.6         0.
  0.51785714  0.93333333  1.          0.          0.36363636  0.625       0.
  0.          0.83333333] / Recall: [ 0.99447514  0.65517241  0.4695122   0.4         0.19565217  0.62264151
  0.          0.42105263  0.          0.          0.58823529  0.83398438
  0.          0.3255814   0.5         0.          0.73214286  0.          0.04
  0.3030303   0.97297297  0.          1.          0.04166667  0.8988764
  0.99300699  0.67204301  0.57692308  0.22857143  0.          0.94642857
  0.13824885  0.          0.8         0.26190476  0.14285714  0.28703704
  0.07692308  0.62244898  0.11111111  0.          0.          0.7047619   0.
  0.19512195  0.4625      0.08        0.09550562  0.03508772  0.          0.
  0.04137931  0.15        0.0141844   0.          0.06896552  0.
  0.82278481  0.86956522  0.96039604  0.          0.38461538  0.
  0.54330709  0.5         0.08108108  0.          0.05769231  0.
  0.98876404  0.96875     0.          0.93670886  0.11538462  0.8893617   0.
  0.015625    0.97037037  0.          0.          0.          0.03571429
  0.07407407  0.36842105  0.78395062  0.02985075  0.          0.
  0.44578313  0.2962963   0.03030303  0.42857143  0.72682927  0.          0.
  0.68627451  0.          0.82692308  0.          0.72727273  0.61267606
  0.72222222  0.09433962  0.02941176  0.          0.33333333  0.
  0.60416667  0.63636364  0.2         0.          0.14545455  0.25        0.
  0.          0.25      ] / Accuracy: 0.54


Training combination: n_est:10 - depth:None
building tree 1 of 10
building tree 2 of 10building tree 3 of 10
building tree 4 of 10

building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10

[Parallel(n_jobs=-1)]: Done   5 out of  10 | elapsed:   16.0s remaining:   16.0s

building tree 9 of 10
building tree 10 of 10

[Parallel(n_jobs=-1)]: Done   7 out of  10 | elapsed:   16.3s remaining:    6.9s
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:   22.1s finished
[Parallel(n_jobs=4)]: Done   5 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   7 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.0s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: None ---- Precision: [ 0.9164557   0.75862069  0.50276243  0.63636364  0.38461538  0.47826087
  0.46428571  0.53846154  0.          0.5         0.74137931  0.53479853
  0.66666667  0.62068966  0.          0.          0.7826087   0.75
  0.26923077  0.53020134  0.82022472  0.          0.91240876  0.94117647
  0.60774411  0.77777778  0.67567568  0.74576271  0.8         1.
  0.77464789  0.23728814  0.22222222  0.79487179  0.60606061  0.63157895
  0.46464646  0.75        0.61320755  0.35714286  0.5         0.          0.59
  0.          0.86046512  0.4587156   0.36363636  0.26168224  0.625
  0.2173913   0.1         0.28703704  1.          0.55045872  0.
  0.64285714  1.          0.45323741  0.79487179  0.78632479  0.
  0.81818182  0.5         0.40935673  1.          0.26027397  0.66666667
  0.69565217  0.          0.95187166  0.92929293  0.75        0.91463415
  0.60714286  0.68728522  1.          0.46666667  0.81329114  0.
  0.83333333  0.          0.40909091  0.89473684  0.71428571  0.8603352
  0.37037037  0.          0.2         0.5         0.75757576  0.36363636
  1.          0.47348485  0.          0.5         0.86046512  1.
  0.76595745  1.          0.53846154  0.71621622  0.88235294  0.45454545
  0.325       0.          1.          0.8         0.5         1.          1.
  0.          0.26086957  0.77777778  0.          0.73333333  0.94117647] / Recall: [ 1.          0.75862069  0.55487805  0.7         0.32608696  0.62264151
  0.48148148  0.36842105  0.          0.625       0.84313725  0.85546875
  0.0952381   0.41860465  0.          0.          0.96428571  0.5         0.14
  0.3989899   0.98648649  0.          0.98425197  0.66666667  0.81123596
  0.97902098  0.80645161  0.84615385  0.57142857  0.5         0.98214286
  0.19354839  0.13333333  0.88571429  0.47619048  0.57142857  0.42592593
  0.23076923  0.66326531  0.18518519  0.25        0.          0.84285714
  0.          0.90243902  0.625       0.32        0.15730337  0.1754386
  0.14285714  0.08163265  0.2137931   0.9         0.42553191  0.
  0.31034483  0.72727273  0.79746835  0.89855072  0.91089109  0.
  0.69230769  0.1         0.5511811   0.9         0.25675676  0.13333333
  0.30769231  0.          1.          0.95833333  0.54545455  0.94936709
  0.65384615  0.85106383  0.28571429  0.109375    0.95185185  0.
  0.38461538  0.          0.32142857  0.62962963  0.52631579  0.95061728
  0.14925373  0.          0.09090909  0.57831325  0.46296296  0.12121212
  0.28571429  0.6097561   0.          0.33333333  0.7254902   0.27777778
  0.69230769  0.2173913   0.31818182  0.74647887  0.83333333  0.37735849
  0.12745098  0.          0.11111111  0.21052632  0.45833333  0.90909091
  0.8         0.          0.10909091  0.35        0.          0.35483871
  0.8       ] / Accuracy: 0.624


Training combination: n_est:300 - depth:10
building tree 1 of 300
building tree 2 of 300building tree 3 of 300building tree 4 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300
building tree 9 of 300
building tree 10 of 300building tree 11 of 300

building tree 12 of 300
building tree 13 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    0.5s

building tree 14 of 300
building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    1.1s

building tree 27 of 300building tree 26 of 300

building tree 28 of 300
building tree 29 of 300
building tree 30 of 300
building tree 31 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    1.4s

building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300
building tree 39 of 300
building tree 40 of 300
building tree 41 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    1.9s

building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300
building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    2.3s

building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300
building tree 59 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:    2.9s

building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:    3.6s

building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300building tree 79 of 300

building tree 80 of 300
building tree 81 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:    4.3s

building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300
building tree 95 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:    4.9s

building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:    5.8s

building tree 109 of 300
building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300
building tree 125 of 300
building tree 126 of 300
building tree 127 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:    6.6s

building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300
building tree 142 of 300
building tree 143 of 300
building tree 144 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:    7.7s

building tree 145 of 300
building tree 146 of 300building tree 147 of 300

building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:    8.7s

building tree 158 of 300
building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300
building tree 178 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:    9.9s

building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300
building tree 197 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   11.2s

building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:   12.7s

building tree 217 of 300
building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:   14.2s

building tree 238 of 300
building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:   15.7s

building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300
building tree 285 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:   17.2s

building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   18.7s finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    0.7s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    0.8s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:    0.9s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:    1.1s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:    1.2s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    1.5s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:    1.7s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:    1.9s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:    2.1s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:    2.3s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:    2.5s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: 10 ---- Precision: [ 0.8783455   0.          0.78205128  0.          0.          0.          0.
  0.          0.          0.          0.85714286  0.14831946  0.          0.
  0.          0.          1.          0.          0.          0.91666667
  0.92753623  0.          0.93181818  0.          0.48826816  0.83625731
  0.81751825  0.8         0.          0.          0.83333333  0.          0.
  0.66666667  0.          0.          0.83333333  0.          0.85714286
  0.          0.          0.          0.48974359  0.          1.
  0.66666667  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.47945205
  0.859375    0.78448276  0.          0.          0.          0.55882353
  0.          0.          0.          0.          0.          0.90816327
  0.97802198  0.          0.95121951  0.          0.64957265  0.          0.
  0.71621622  0.          0.          0.          0.          0.          0.
  0.83333333  0.          0.          0.          0.53846154  0.          0.
  0.          0.40590406  0.          0.          0.91666667  0.
  0.77777778  0.          0.          0.79268293  0.          0.          0.
  0.          0.          0.          0.43373494  0.          0.          0.
  0.          0.          0.          0.          0.        ] / Recall: [ 0.99723757  0.          0.37195122  0.          0.          0.          0.
  0.          0.          0.          0.11764706  0.93945312  0.          0.
  0.          0.          0.16071429  0.          0.          0.05555556
  0.86486486  0.          0.96850394  0.          0.98202247  1.
  0.60215054  0.84615385  0.          0.          0.53571429  0.          0.
  0.05714286  0.          0.          0.23148148  0.          0.24489796
  0.          0.          0.          0.90952381  0.          0.17073171
  0.125       0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.88607595
  0.79710145  0.9009901   0.          0.          0.          0.1496063   0.
  0.          0.          0.          0.          1.          0.92708333
  0.          0.49367089  0.          0.97021277  0.          0.
  0.98148148  0.          0.          0.          0.          0.          0.
  0.98765432  0.          0.          0.          0.08433735  0.          0.
  0.          0.53658537  0.          0.          0.21568627  0.
  0.40384615  0.          0.          0.45774648  0.          0.          0.
  0.          0.          0.          0.375       0.          0.          0.
  0.          0.          0.          0.          0.        ] / Accuracy: 0.459


Training combination: n_est:300 - depth:20
building tree 1 of 300building tree 3 of 300building tree 2 of 300
building tree 4 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    1.1s

building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300
building tree 16 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    2.0s

building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    3.3s

building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    4.0s

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    5.8s

building tree 37 of 300
building tree 38 of 300building tree 39 of 300

building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300
building tree 47 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    7.2s

building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:    9.4s

building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300
building tree 69 of 300
building tree 70 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:   11.3s

building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:   12.9s

building tree 81 of 300
building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300
building tree 95 of 300
building tree 96 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:   14.8s

building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300
building tree 110 of 300
building tree 111 of 300
building tree 112 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:   16.9s

building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:   18.6s

building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:   21.0s

building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:   23.4s

building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:   26.4s

building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300
building tree 197 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   29.4s

building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:   32.7s

building tree 217 of 300
building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300
building tree 238 of 300
building tree 239 of 300
building tree 240 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:   36.2s

building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300
building tree 262 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:   39.4s

building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300
building tree 285 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:   42.3s

building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   45.0s finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:    0.7s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:    0.8s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:    0.9s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:    1.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    1.1s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:    1.3s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:    1.5s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:    1.7s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:    1.8s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: 20 ---- Precision: [ 0.85545024  0.9047619   0.75247525  1.          0.61538462  0.69230769
  0.          1.          0.          0.          0.88888889  0.28639904
  0.          0.88888889  0.          0.          1.          1.          0.
  0.92105263  0.94871795  0.          0.91240876  1.          0.52760736
  0.78142077  0.66666667  0.85714286  0.          0.          0.82089552
  0.425       0.          0.82051282  0.66666667  1.          0.81578947
  0.          0.76470588  0.          0.          0.          0.44273128
  0.          0.97222222  0.62121212  0.          0.1875      0.          0.
  0.          0.53846154  1.          0.62962963  0.          0.          0.
  0.47852761  0.74418605  0.72661871  0.          0.83333333  0.
  0.36610169  1.          0.          0.          0.          0.
  0.89847716  0.91176471  1.          0.82105263  0.66666667  0.61827957
  0.          0.          0.76231884  0.          0.          0.          1.
  0.          0.          0.79207921  0.          0.          0.          0.5
  0.9         0.          0.          0.39872068  0.          0.
  0.81481481  0.          0.73684211  0.          0.          0.76612903
  1.          0.47058824  1.          0.          0.          0.
  0.49180328  1.          0.          0.          0.          1.          0.
  0.          1.        ] / Recall: [ 0.99723757  0.65517241  0.46341463  0.05        0.17391304  0.33962264
  0.          0.05263158  0.          0.          0.78431373  0.93359375
  0.          0.18604651  0.          0.          0.91071429  0.16666667
  0.          0.17676768  1.          0.          0.98425197  0.04166667
  0.96629213  1.          0.79569892  0.69230769  0.          0.
  0.98214286  0.07834101  0.          0.91428571  0.28571429  0.02380952
  0.28703704  0.          0.66326531  0.          0.          0.
  0.95714286  0.          0.85365854  0.5125      0.          0.01685393
  0.          0.          0.          0.04827586  0.05        0.12056738
  0.          0.          0.          0.98734177  0.92753623  1.          0.
  0.38461538  0.          0.8503937   0.15        0.          0.          0.
  0.          0.99438202  0.96875     0.09090909  0.98734177  0.07692308
  0.9787234   0.          0.          0.97407407  0.          0.          0.
  0.10714286  0.          0.          0.98765432  0.          0.          0.
  0.75903614  0.33333333  0.          0.          0.91219512  0.          0.
  0.8627451   0.          0.80769231  0.          0.          0.66901408
  0.22222222  0.30188679  0.01960784  0.          0.          0.          0.625
  0.45454545  0.          0.          0.          0.05        0.          0.
  0.1       ] / Accuracy: 0.573


Training combination: n_est:300 - depth:30
building tree 1 of 300
building tree 2 of 300building tree 3 of 300building tree 4 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    2.2s

building tree 9 of 300building tree 10 of 300

building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    3.4s

building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    5.4s

building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    7.7s

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   11.3s

building tree 38 of 300
building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   14.2s

building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:   17.5s

building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:   21.4s

building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:   24.6s

building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:   27.9s

building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300
building tree 110 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:   32.0s

building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300
building tree 125 of 300
building tree 126 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:   36.6s

building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300
building tree 142 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:   41.9s

building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:   46.9s

building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:   53.2s

building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   58.9s

building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300
building tree 217 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  1.1min

building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300
building tree 238 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  1.2min

building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  1.3min

building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  1.4min

building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.5min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:    0.7s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:    0.8s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:    0.9s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:    1.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    1.2s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:    1.3s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:    1.6s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:    1.8s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:    1.9s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: 30 ---- Precision: [ 0.87621359  0.84615385  0.77227723  0.75        0.8         0.66666667
  0.81818182  1.          0.          0.          0.81481481  0.39513423
  0.          0.93333333  0.          0.          0.98076923  1.          0.
  0.77922078  0.93670886  0.          0.89928058  1.          0.57814661
  0.83928571  0.66094421  0.85        0.93333333  0.          0.74324324
  0.35714286  0.          0.86486486  0.71052632  0.85        0.72093023
  0.          0.70212766  0.          0.          0.          0.48888889
  0.          0.97368421  0.65671642  0.          0.20689655  0.          0.
  0.          0.40384615  1.          0.6         0.          0.          0.
  0.47560976  0.77108434  0.73188406  0.          0.875       0.
  0.36734694  1.          0.25773196  0.          1.          0.
  0.92227979  0.87037037  0.          0.84782609  0.88888889  0.64124294
  0.          0.          0.77647059  0.          0.          0.
  0.70588235  0.          1.          0.8071066   0.66666667  0.          0.
  0.47407407  0.92307692  0.          0.          0.39316239  0.          0.
  0.79245283  0.          0.70967742  0.          0.90909091  0.71641791
  1.          0.49019608  0.66666667  0.          0.          0.
  0.47651007  1.          0.          0.          0.          0.75        0.
  0.79166667  1.        ] / Recall: [ 0.99723757  0.75862069  0.47560976  0.45        0.26086957  0.56603774
  0.33333333  0.21052632  0.          0.          0.8627451   0.91992188
  0.          0.3255814   0.          0.          0.91071429  0.16666667
  0.          0.3030303   1.          0.          0.98425197  0.41666667
  0.93932584  0.98601399  0.82795699  0.65384615  0.4         0.
  0.98214286  0.1843318   0.          0.91428571  0.64285714  0.4047619
  0.28703704  0.          0.67346939  0.          0.          0.
  0.94285714  0.          0.90243902  0.55        0.          0.03370787
  0.          0.          0.          0.14482759  0.7         0.31914894
  0.          0.          0.          0.98734177  0.92753623  1.          0.
  0.53846154  0.          0.8503937   0.65        0.16891892  0.
  0.01923077  0.          1.          0.97916667  0.          0.98734177
  0.61538462  0.96595745  0.          0.          0.97777778  0.          0.
  0.          0.42857143  0.          0.21052632  0.98148148  0.02985075
  0.          0.          0.77108434  0.44444444  0.          0.
  0.89756098  0.          0.          0.82352941  0.          0.84615385
  0.          0.45454545  0.67605634  0.77777778  0.47169811  0.01960784
  0.          0.          0.          0.73958333  0.90909091  0.          0.
  0.          0.15        0.          0.20430108  0.8       ] / Accuracy: 0.618


Training combination: n_est:300 - depth:None
building tree 1 of 300building tree 4 of 300building tree 2 of 300building tree 3 of 300



building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   15.7s

building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   23.7s

building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   40.6s

building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   50.6s

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.2min

building tree 37 of 300
building tree 38 of 300
building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.5min

building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.9min

building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  2.2min

building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.7min

building tree 81 of 300
building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  3.2min

building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  3.8min

building tree 109 of 300
building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  4.3min

building tree 124 of 300
building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  5.0min

building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  5.4min

building tree 158 of 300
building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300
building tree 178 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  5.8min

building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  6.2min

building tree 196 of 300
building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  6.8min

building tree 217 of 300
building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  7.3min

building tree 238 of 300
building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  8.0min

building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  8.5min

building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  9.0min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    1.0s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    2.7s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    2.9s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    3.0s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    3.2s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    3.4s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    4.1s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    6.5s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    8.4s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    9.0s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:    9.3s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:    9.6s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   12.8s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   13.2s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   13.5s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   15.3s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   16.2s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   16.5s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   16.8s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:   17.0s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: None ---- Precision: [ 0.96010638  0.88        0.76851852  0.78947368  0.8125      0.57142857
  0.71428571  1.          0.          0.625       0.8         0.55247286
  0.          0.76470588  0.          0.          0.98113208  1.          0.125
  0.76666667  0.94871795  0.          0.94029851  0.94736842  0.62826421
  0.83431953  0.7027027   0.76923077  0.82608696  0.25        0.78571429
  0.34911243  0.5         0.90909091  0.73809524  0.75        0.6         1.
  0.67924528  0.57142857  0.5         0.          0.5641791   0.
  0.92682927  0.6125      0.72727273  0.28205128  0.76923077  0.2         0.5
  0.37078652  1.          0.57758621  0.          0.71428571  0.88888889
  0.48701299  0.83333333  0.808       1.          0.92307692  1.
  0.42857143  1.          0.27932961  0.66666667  0.9047619   0.
  0.97802198  0.95876289  0.71428571  0.89655172  0.8         0.68454259
  1.          0.55555556  0.8343949   0.66666667  0.8         0.
  0.66666667  0.86363636  0.75        0.86338798  0.38461538  0.          0.
  0.46564885  0.875       0.          1.          0.42753623  0.          0.5
  0.82        1.          0.75471698  1.          0.78947368  0.72857143
  1.          0.48484848  0.42105263  0.          0.5         1.          0.5
  1.          1.          0.          0.6         0.72727273  1.
  0.75471698  1.        ] / Recall: [ 0.99723757  0.75862069  0.50609756  0.75        0.2826087   0.67924528
  0.55555556  0.52631579  0.          0.625       0.8627451   0.89453125
  0.          0.60465116  0.          0.          0.92857143  0.83333333
  0.02        0.34848485  1.          0.          0.99212598  0.75
  0.91910112  0.98601399  0.83870968  0.76923077  0.54285714  0.25
  0.98214286  0.2718894   0.13333333  0.85714286  0.73809524  0.71428571
  0.30555556  0.46153846  0.73469388  0.14814815  0.5         0.          0.9
  0.          0.92682927  0.6125      0.32        0.12359551  0.1754386
  0.04285714  0.02040816  0.22758621  0.9         0.4751773   0.
  0.17241379  0.72727273  0.94936709  0.94202899  1.          0.05882353
  0.92307692  0.1         0.75590551  0.9         0.33783784  0.26666667
  0.36538462  0.          1.          0.96875     0.45454545  0.98734177
  0.61538462  0.92340426  0.57142857  0.15625     0.97037037  0.28571429
  0.61538462  0.          0.5         0.7037037   0.63157895  0.97530864
  0.2238806   0.          0.          0.73493976  0.51851852  0.          1.
  0.86341463  0.          0.33333333  0.80392157  0.44444444  0.76923077
  0.34782609  0.68181818  0.71830986  0.88888889  0.60377358  0.07843137
  0.          0.11111111  0.36842105  0.72916667  0.90909091  0.8         0.
  0.10909091  0.4         0.42857143  0.43010753  1.        ] / Accuracy: 0.669

In [31]:
train_RF(900, None) # 0.613 accuracy if i use wordnet lemamtizing

building tree 1 of 900
building tree 4 of 900
building tree 3 of 900
building tree 2 of 900
building tree 5 of 900
building tree 6 of 900
building tree 7 of 900
building tree 8 of 900

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   11.2s

building tree 9 of 900
building tree 10 of 900
building tree 11 of 900
building tree 12 of 900
building tree 13 of 900
building tree 14 of 900
building tree 15 of 900
building tree 16 of 900

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   17.6s

building tree 17 of 900
building tree 18 of 900
building tree 19 of 900
building tree 20 of 900
building tree 21 of 900

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   29.0s

building tree 22 of 900
building tree 23 of 900
building tree 24 of 900
building tree 25 of 900
building tree 26 of 900
building tree 27 of 900
building tree 28 of 900

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   35.3s

building tree 29 of 900
building tree 30 of 900
building tree 31 of 900
building tree 32 of 900
building tree 33 of 900
building tree 34 of 900
building tree 35 of 900
building tree 36 of 900

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   54.3s

building tree 37 of 900
building tree 38 of 900
building tree 39 of 900
building tree 40 of 900
building tree 41 of 900
building tree 42 of 900
building tree 43 of 900
building tree 44 of 900
building tree 45 of 900
building tree 46 of 900

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.1min

building tree 47 of 900
building tree 48 of 900
building tree 49 of 900
building tree 50 of 900
building tree 51 of 900
building tree 52 of 900
building tree 53 of 900
building tree 54 of 900
building tree 55 of 900
building tree 56 of 900

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.5min

building tree 57 of 900
building tree 58 of 900
building tree 59 of 900
building tree 60 of 900
building tree 61 of 900
building tree 62 of 900
building tree 63 of 900
building tree 64 of 900
building tree 65 of 900
building tree 66 of 900
building tree 67 of 900
building tree 68 of 900

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  1.7min

building tree 69 of 900
building tree 70 of 900
building tree 71 of 900
building tree 72 of 900
building tree 73 of 900
building tree 74 of 900
building tree 75 of 900
building tree 76 of 900
building tree 77 of 900
building tree 78 of 900
building tree 79 of 900
building tree 80 of 900
building tree 81 of 900
building tree 82 of 900

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.2min

building tree 83 of 900
building tree 84 of 900
building tree 85 of 900
building tree 86 of 900
building tree 87 of 900
building tree 88 of 900
building tree 89 of 900
building tree 90 of 900
building tree 91 of 900
building tree 92 of 900
building tree 93 of 900
building tree 94 of 900

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.5min

building tree 95 of 900
building tree 96 of 900
building tree 97 of 900
building tree 98 of 900
building tree 99 of 900
building tree 100 of 900
building tree 101 of 900
building tree 102 of 900
building tree 103 of 900
building tree 104 of 900
building tree 105 of 900
building tree 106 of 900
building tree 107 of 900
building tree 108 of 900

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  2.9min

building tree 109 of 900
building tree 110 of 900
building tree 111 of 900
building tree 112 of 900
building tree 113 of 900
building tree 114 of 900
building tree 115 of 900
building tree 116 of 900
building tree 117 of 900
building tree 118 of 900
building tree 119 of 900
building tree 120 of 900
building tree 121 of 900
building tree 122 of 900
building tree 123 of 900
building tree 124 of 900

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  3.2min

building tree 125 of 900
building tree 126 of 900
building tree 127 of 900
building tree 128 of 900
building tree 129 of 900
building tree 130 of 900
building tree 131 of 900
building tree 132 of 900
building tree 133 of 900
building tree 134 of 900
building tree 135 of 900
building tree 136 of 900
building tree 137 of 900
building tree 138 of 900
building tree 139 of 900
building tree 140 of 900
building tree 141 of 900

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  3.7min

building tree 142 of 900
building tree 143 of 900
building tree 144 of 900
building tree 145 of 900
building tree 146 of 900
building tree 147 of 900
building tree 148 of 900
building tree 149 of 900
building tree 150 of 900
building tree 151 of 900
building tree 152 of 900
building tree 153 of 900
building tree 154 of 900
building tree 155 of 900
building tree 156 of 900
building tree 157 of 900
building tree 158 of 900

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  4.2min

building tree 159 of 900
building tree 160 of 900
building tree 161 of 900
building tree 162 of 900
building tree 163 of 900
building tree 164 of 900
building tree 165 of 900
building tree 166 of 900
building tree 167 of 900
building tree 168 of 900
building tree 169 of 900
building tree 170 of 900
building tree 171 of 900
building tree 172 of 900
building tree 173 of 900
building tree 174 of 900
building tree 175 of 900
building tree 176 of 900

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  4.7min

building tree 177 of 900
building tree 178 of 900
building tree 179 of 900
building tree 180 of 900
building tree 181 of 900
building tree 182 of 900
building tree 183 of 900
building tree 184 of 900
building tree 185 of 900
building tree 186 of 900
building tree 187 of 900
building tree 188 of 900
building tree 189 of 900
building tree 190 of 900
building tree 191 of 900
building tree 192 of 900
building tree 193 of 900
building tree 194 of 900
building tree 195 of 900

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  5.2min

building tree 196 of 900
building tree 197 of 900
building tree 198 of 900
building tree 199 of 900
building tree 200 of 900
building tree 201 of 900
building tree 202 of 900
building tree 203 of 900
building tree 204 of 900
building tree 205 of 900
building tree 206 of 900
building tree 207 of 900
building tree 208 of 900
building tree 209 of 900
building tree 210 of 900
building tree 211 of 900
building tree 212 of 900
building tree 213 of 900
building tree 214 of 900
building tree 215 of 900
building tree 216 of 900
building tree 217 of 900

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  6.0min

building tree 218 of 900
building tree 219 of 900
building tree 220 of 900
building tree 221 of 900
building tree 222 of 900
building tree 223 of 900
building tree 224 of 900
building tree 225 of 900
building tree 226 of 900
building tree 227 of 900
building tree 228 of 900
building tree 229 of 900
building tree 230 of 900
building tree 231 of 900
building tree 232 of 900
building tree 233 of 900
building tree 234 of 900
building tree 235 of 900
building tree 236 of 900
building tree 237 of 900

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  6.8min

building tree 238 of 900
building tree 239 of 900
building tree 240 of 900
building tree 241 of 900
building tree 242 of 900
building tree 243 of 900
building tree 244 of 900
building tree 245 of 900
building tree 246 of 900
building tree 247 of 900
building tree 248 of 900
building tree 249 of 900
building tree 250 of 900
building tree 251 of 900
building tree 252 of 900
building tree 253 of 900
building tree 254 of 900
building tree 255 of 900
building tree 256 of 900
building tree 257 of 900
building tree 258 of 900
building tree 259 of 900
building tree 260 of 900
building tree 261 of 900

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  7.6min

building tree 262 of 900
building tree 263 of 900
building tree 264 of 900
building tree 265 of 900
building tree 266 of 900
building tree 267 of 900
building tree 268 of 900
building tree 269 of 900
building tree 270 of 900
building tree 271 of 900
building tree 272 of 900
building tree 273 of 900
building tree 274 of 900
building tree 275 of 900
building tree 276 of 900
building tree 277 of 900
building tree 278 of 900
building tree 279 of 900
building tree 280 of 900
building tree 281 of 900
building tree 282 of 900
building tree 283 of 900
building tree 284 of 900

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  8.4min

building tree 285 of 900
building tree 286 of 900
building tree 287 of 900
building tree 288 of 900
building tree 289 of 900
building tree 290 of 900
building tree 291 of 900
building tree 292 of 900
building tree 293 of 900
building tree 294 of 900
building tree 295 of 900
building tree 296 of 900
building tree 297 of 900
building tree 298 of 900
building tree 299 of 900
building tree 300 of 900
building tree 301 of 900
building tree 302 of 900
building tree 303 of 900
building tree 304 of 900
building tree 305 of 900
building tree 306 of 900
building tree 307 of 900
building tree 308 of 900
building tree 309 of 900

[Parallel(n_jobs=-1)]: Done 305 tasks      | elapsed:  9.2min

building tree 310 of 900
building tree 311 of 900
building tree 312 of 900
building tree 313 of 900
building tree 314 of 900
building tree 315 of 900
building tree 316 of 900
building tree 317 of 900
building tree 318 of 900
building tree 319 of 900
building tree 320 of 900
building tree 321 of 900
building tree 322 of 900
building tree 323 of 900
building tree 324 of 900
building tree 325 of 900
building tree 326 of 900
building tree 327 of 900
building tree 328 of 900
building tree 329 of 900
building tree 330 of 900
building tree 331 of 900
building tree 332 of 900
building tree 333 of 900
building tree 334 of 900

[Parallel(n_jobs=-1)]: Done 330 tasks      | elapsed: 10.2min

building tree 335 of 900
building tree 336 of 900
building tree 337 of 900
building tree 338 of 900
building tree 339 of 900
building tree 340 of 900
building tree 341 of 900
building tree 342 of 900
building tree 343 of 900
building tree 344 of 900
building tree 345 of 900
building tree 346 of 900
building tree 347 of 900
building tree 348 of 900
building tree 349 of 900
building tree 350 of 900
building tree 351 of 900
building tree 352 of 900
building tree 353 of 900
building tree 354 of 900
building tree 355 of 900
building tree 356 of 900
building tree 357 of 900
building tree 358 of 900
building tree 359 of 900
building tree 360 of 900

[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed: 11.2min

building tree 361 of 900
building tree 362 of 900
building tree 363 of 900
building tree 364 of 900
building tree 365 of 900
building tree 366 of 900
building tree 367 of 900
building tree 368 of 900
building tree 369 of 900
building tree 370 of 900
building tree 371 of 900
building tree 372 of 900
building tree 373 of 900
building tree 374 of 900
building tree 375 of 900
building tree 376 of 900
building tree 377 of 900
building tree 378 of 900
building tree 379 of 900
building tree 380 of 900
building tree 381 of 900
building tree 382 of 900
building tree 383 of 900
building tree 384 of 900
building tree 385 of 900
building tree 386 of 900
building tree 387 of 900
building tree 388 of 900

[Parallel(n_jobs=-1)]: Done 384 tasks      | elapsed: 12.1min

building tree 389 of 900
building tree 390 of 900
building tree 391 of 900
building tree 392 of 900
building tree 393 of 900
building tree 394 of 900
building tree 395 of 900
building tree 396 of 900
building tree 397 of 900
building tree 398 of 900
building tree 399 of 900
building tree 400 of 900
building tree 401 of 900
building tree 402 of 900
building tree 403 of 900
building tree 404 of 900
building tree 405 of 900
building tree 406 of 900
building tree 407 of 900
building tree 408 of 900
building tree 409 of 900
building tree 410 of 900
building tree 411 of 900
building tree 412 of 900
building tree 413 of 900
building tree 414 of 900
building tree 415 of 900
building tree 416 of 900
building tree 417 of 900

[Parallel(n_jobs=-1)]: Done 413 tasks      | elapsed: 13.2min

building tree 418 of 900
building tree 419 of 900
building tree 420 of 900
building tree 421 of 900
building tree 422 of 900
building tree 423 of 900
building tree 424 of 900
building tree 425 of 900
building tree 426 of 900
building tree 427 of 900
building tree 428 of 900
building tree 429 of 900
building tree 430 of 900
building tree 431 of 900
building tree 432 of 900
building tree 433 of 900
building tree 434 of 900
building tree 435 of 900
building tree 436 of 900
building tree 437 of 900
building tree 438 of 900
building tree 439 of 900
building tree 440 of 900
building tree 441 of 900
building tree 442 of 900
building tree 443 of 900
building tree 444 of 900
building tree 445 of 900

[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed: 14.2min

building tree 446 of 900
building tree 447 of 900
building tree 448 of 900
building tree 449 of 900
building tree 450 of 900
building tree 451 of 900
building tree 452 of 900
building tree 453 of 900
building tree 454 of 900
building tree 455 of 900
building tree 456 of 900
building tree 457 of 900
building tree 458 of 900
building tree 459 of 900
building tree 460 of 900
building tree 461 of 900
building tree 462 of 900
building tree 463 of 900
building tree 464 of 900
building tree 465 of 900
building tree 466 of 900
building tree 467 of 900
building tree 468 of 900
building tree 469 of 900
building tree 470 of 900
building tree 471 of 900
building tree 472 of 900
building tree 473 of 900
building tree 474 of 900
building tree 475 of 900
building tree 476 of 900
building tree 477 of 900

[Parallel(n_jobs=-1)]: Done 473 tasks      | elapsed: 15.3min

building tree 478 of 900
building tree 479 of 900
building tree 480 of 900
building tree 481 of 900
building tree 482 of 900
building tree 483 of 900
building tree 484 of 900
building tree 485 of 900
building tree 486 of 900
building tree 487 of 900
building tree 488 of 900
building tree 489 of 900
building tree 490 of 900
building tree 491 of 900
building tree 492 of 900
building tree 493 of 900
building tree 494 of 900
building tree 495 of 900
building tree 496 of 900
building tree 497 of 900
building tree 498 of 900
building tree 499 of 900
building tree 500 of 900
building tree 501 of 900
building tree 502 of 900
building tree 503 of 900
building tree 504 of 900
building tree 505 of 900
building tree 506 of 900
building tree 507 of 900
building tree 508 of 900

[Parallel(n_jobs=-1)]: Done 504 tasks      | elapsed: 16.3min

building tree 509 of 900
building tree 510 of 900
building tree 511 of 900
building tree 512 of 900
building tree 513 of 900
building tree 514 of 900
building tree 515 of 900
building tree 516 of 900
building tree 517 of 900
building tree 518 of 900
building tree 519 of 900
building tree 520 of 900
building tree 521 of 900
building tree 522 of 900
building tree 523 of 900
building tree 524 of 900
building tree 525 of 900
building tree 526 of 900
building tree 527 of 900
building tree 528 of 900
building tree 529 of 900
building tree 530 of 900
building tree 531 of 900
building tree 532 of 900
building tree 533 of 900
building tree 534 of 900
building tree 535 of 900
building tree 536 of 900
building tree 537 of 900
building tree 538 of 900
building tree 539 of 900
building tree 540 of 900
building tree 541 of 900

[Parallel(n_jobs=-1)]: Done 537 tasks      | elapsed: 17.4min

building tree 542 of 900
building tree 543 of 900
building tree 544 of 900
building tree 545 of 900
building tree 546 of 900
building tree 547 of 900
building tree 548 of 900
building tree 549 of 900
building tree 550 of 900
building tree 551 of 900
building tree 552 of 900
building tree 553 of 900
building tree 554 of 900
building tree 555 of 900
building tree 556 of 900
building tree 557 of 900
building tree 558 of 900
building tree 559 of 900
building tree 560 of 900
building tree 561 of 900
building tree 562 of 900
building tree 563 of 900
building tree 564 of 900
building tree 565 of 900
building tree 566 of 900
building tree 567 of 900
building tree 568 of 900
building tree 569 of 900
building tree 570 of 900
building tree 571 of 900
building tree 572 of 900
building tree 573 of 900
building tree 574 of 900

[Parallel(n_jobs=-1)]: Done 570 tasks      | elapsed: 18.6min

building tree 575 of 900
building tree 576 of 900
building tree 577 of 900
building tree 578 of 900
building tree 579 of 900
building tree 580 of 900
building tree 581 of 900
building tree 582 of 900
building tree 583 of 900
building tree 584 of 900
building tree 585 of 900
building tree 586 of 900
building tree 587 of 900
building tree 588 of 900
building tree 589 of 900
building tree 590 of 900
building tree 591 of 900
building tree 592 of 900
building tree 593 of 900
building tree 594 of 900
building tree 595 of 900
building tree 596 of 900
building tree 597 of 900
building tree 598 of 900
building tree 599 of 900
building tree 600 of 900
building tree 601 of 900
building tree 602 of 900
building tree 603 of 900
building tree 604 of 900
building tree 605 of 900
building tree 606 of 900
building tree 607 of 900
building tree 608 of 900
building tree 609 of 900

[Parallel(n_jobs=-1)]: Done 605 tasks      | elapsed: 19.9min

building tree 610 of 900
building tree 611 of 900
building tree 612 of 900
building tree 613 of 900
building tree 614 of 900
building tree 615 of 900
building tree 616 of 900
building tree 617 of 900
building tree 618 of 900
building tree 619 of 900
building tree 620 of 900
building tree 621 of 900
building tree 622 of 900
building tree 623 of 900
building tree 624 of 900
building tree 625 of 900
building tree 626 of 900
building tree 627 of 900
building tree 628 of 900
building tree 629 of 900
building tree 630 of 900
building tree 631 of 900
building tree 632 of 900
building tree 633 of 900
building tree 634 of 900
building tree 635 of 900
building tree 636 of 900
building tree 637 of 900
building tree 638 of 900
building tree 639 of 900
building tree 640 of 900
building tree 641 of 900
building tree 642 of 900
building tree 643 of 900
building tree 644 of 900

[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed: 21.0min

building tree 645 of 900
building tree 646 of 900
building tree 647 of 900
building tree 648 of 900
building tree 649 of 900
building tree 650 of 900
building tree 651 of 900
building tree 652 of 900
building tree 653 of 900
building tree 654 of 900
building tree 655 of 900
building tree 656 of 900
building tree 657 of 900
building tree 658 of 900
building tree 659 of 900
building tree 660 of 900
building tree 661 of 900
building tree 662 of 900
building tree 663 of 900
building tree 664 of 900
building tree 665 of 900
building tree 666 of 900
building tree 667 of 900
building tree 668 of 900
building tree 669 of 900
building tree 670 of 900
building tree 671 of 900
building tree 672 of 900
building tree 673 of 900
building tree 674 of 900
building tree 675 of 900
building tree 676 of 900
building tree 677 of 900
building tree 678 of 900
building tree 679 of 900
building tree 680 of 900
building tree 681 of 900

[Parallel(n_jobs=-1)]: Done 677 tasks      | elapsed: 22.3min

building tree 682 of 900
building tree 683 of 900
building tree 684 of 900
building tree 685 of 900
building tree 686 of 900
building tree 687 of 900
building tree 688 of 900
building tree 689 of 900
building tree 690 of 900
building tree 691 of 900
building tree 692 of 900
building tree 693 of 900
building tree 694 of 900
building tree 695 of 900
building tree 696 of 900
building tree 697 of 900
building tree 698 of 900
building tree 699 of 900
building tree 700 of 900
building tree 701 of 900
building tree 702 of 900
building tree 703 of 900
building tree 704 of 900
building tree 705 of 900
building tree 706 of 900
building tree 707 of 900
building tree 708 of 900
building tree 709 of 900
building tree 710 of 900
building tree 711 of 900
building tree 712 of 900
building tree 713 of 900
building tree 714 of 900
building tree 715 of 900
building tree 716 of 900
building tree 717 of 900

[Parallel(n_jobs=-1)]: Done 714 tasks      | elapsed: 23.6min

building tree 718 of 900
building tree 719 of 900
building tree 720 of 900
building tree 721 of 900
building tree 722 of 900
building tree 723 of 900
building tree 724 of 900
building tree 725 of 900
building tree 726 of 900
building tree 727 of 900
building tree 728 of 900
building tree 729 of 900
building tree 730 of 900
building tree 731 of 900
building tree 732 of 900
building tree 733 of 900
building tree 734 of 900
building tree 735 of 900
building tree 736 of 900
building tree 737 of 900
building tree 738 of 900
building tree 739 of 900
building tree 740 of 900
building tree 741 of 900
building tree 742 of 900
building tree 743 of 900
building tree 744 of 900
building tree 745 of 900
building tree 746 of 900
building tree 747 of 900
building tree 748 of 900
building tree 749 of 900
building tree 750 of 900
building tree 751 of 900
building tree 752 of 900
building tree 753 of 900
building tree 754 of 900
building tree 755 of 900
building tree 756 of 900
building tree 757 of 900

[Parallel(n_jobs=-1)]: Done 753 tasks      | elapsed: 25.0min

building tree 758 of 900
building tree 759 of 900
building tree 760 of 900
building tree 761 of 900
building tree 762 of 900
building tree 763 of 900
building tree 764 of 900
building tree 765 of 900
building tree 766 of 900
building tree 767 of 900
building tree 768 of 900
building tree 769 of 900
building tree 770 of 900
building tree 771 of 900
building tree 772 of 900
building tree 773 of 900
building tree 774 of 900
building tree 775 of 900
building tree 776 of 900
building tree 777 of 900
building tree 778 of 900
building tree 779 of 900
building tree 780 of 900
building tree 781 of 900
building tree 782 of 900
building tree 783 of 900
building tree 784 of 900
building tree 785 of 900
building tree 786 of 900
building tree 787 of 900
building tree 788 of 900
building tree 789 of 900
building tree 790 of 900
building tree 791 of 900
building tree 792 of 900
building tree 793 of 900
building tree 794 of 900
building tree 795 of 900
building tree 796 of 900

[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed: 26.0min

building tree 797 of 900
building tree 798 of 900
building tree 799 of 900
building tree 800 of 900
building tree 801 of 900
building tree 802 of 900
building tree 803 of 900
building tree 804 of 900
building tree 805 of 900
building tree 806 of 900
building tree 807 of 900
building tree 808 of 900
building tree 809 of 900
building tree 810 of 900
building tree 811 of 900
building tree 812 of 900
building tree 813 of 900
building tree 814 of 900
building tree 815 of 900
building tree 816 of 900
building tree 817 of 900
building tree 818 of 900
building tree 819 of 900
building tree 820 of 900
building tree 821 of 900
building tree 822 of 900
building tree 823 of 900
building tree 824 of 900
building tree 825 of 900
building tree 826 of 900
building tree 827 of 900
building tree 828 of 900
building tree 829 of 900
building tree 830 of 900
building tree 831 of 900
building tree 832 of 900
building tree 833 of 900
building tree 834 of 900
building tree 835 of 900
building tree 836 of 900

[Parallel(n_jobs=-1)]: Done 833 tasks      | elapsed: 27.2min

building tree 837 of 900
building tree 838 of 900
building tree 839 of 900
building tree 840 of 900
building tree 841 of 900
building tree 842 of 900
building tree 843 of 900
building tree 844 of 900
building tree 845 of 900
building tree 846 of 900
building tree 847 of 900
building tree 848 of 900
building tree 849 of 900
building tree 850 of 900
building tree 851 of 900
building tree 852 of 900
building tree 853 of 900
building tree 854 of 900
building tree 855 of 900
building tree 856 of 900
building tree 857 of 900
building tree 858 of 900
building tree 859 of 900
building tree 860 of 900
building tree 861 of 900
building tree 862 of 900
building tree 863 of 900
building tree 864 of 900
building tree 865 of 900
building tree 866 of 900
building tree 867 of 900
building tree 868 of 900
building tree 869 of 900
building tree 870 of 900
building tree 871 of 900
building tree 872 of 900
building tree 873 of 900
building tree 874 of 900
building tree 875 of 900
building tree 876 of 900
building tree 877 of 900

[Parallel(n_jobs=-1)]: Done 874 tasks      | elapsed: 28.2min

building tree 878 of 900
building tree 879 of 900
building tree 880 of 900
building tree 881 of 900
building tree 882 of 900
building tree 883 of 900
building tree 884 of 900
building tree 885 of 900
building tree 886 of 900
building tree 887 of 900
building tree 888 of 900
building tree 889 of 900
building tree 890 of 900
building tree 891 of 900
building tree 892 of 900
building tree 893 of 900
building tree 894 of 900
building tree 895 of 900
building tree 896 of 900
building tree 897 of 900
building tree 898 of 900
building tree 899 of 900
building tree 900 of 900

[Parallel(n_jobs=-1)]: Done 900 out of 900 | elapsed: 28.9min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    1.3s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    1.8s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    1.9s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    2.4s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    3.1s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    6.5s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    6.9s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    7.2s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    7.4s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    7.8s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:   11.0s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:   11.9s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   12.3s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   12.8s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   14.9s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   16.2s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   19.8s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   20.4s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   23.6s
[Parallel(n_jobs=4)]: Done 305 tasks      | elapsed:   24.2s
[Parallel(n_jobs=4)]: Done 330 tasks      | elapsed:   24.8s
[Parallel(n_jobs=4)]: Done 357 tasks      | elapsed:   28.8s
[Parallel(n_jobs=4)]: Done 384 tasks      | elapsed:   29.4s
[Parallel(n_jobs=4)]: Done 413 tasks      | elapsed:   32.8s
[Parallel(n_jobs=4)]: Done 442 tasks      | elapsed:   33.5s
[Parallel(n_jobs=4)]: Done 473 tasks      | elapsed:   36.9s
[Parallel(n_jobs=4)]: Done 504 tasks      | elapsed:   38.2s
[Parallel(n_jobs=4)]: Done 537 tasks      | elapsed:   41.0s
[Parallel(n_jobs=4)]: Done 570 tasks      | elapsed:   44.1s
[Parallel(n_jobs=4)]: Done 605 tasks      | elapsed:   46.2s
[Parallel(n_jobs=4)]: Done 640 tasks      | elapsed:   48.7s
[Parallel(n_jobs=4)]: Done 677 tasks      | elapsed:   51.3s
[Parallel(n_jobs=4)]: Done 714 tasks      | elapsed:   54.9s
[Parallel(n_jobs=4)]: Done 753 tasks      | elapsed:   56.0s
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed:  1.0min
[Parallel(n_jobs=4)]: Done 833 tasks      | elapsed:  1.0min
[Parallel(n_jobs=4)]: Done 874 tasks      | elapsed:  1.1min
[Parallel(n_jobs=4)]: Done 900 out of 900 | elapsed:  1.1min finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 900 / Depth: None ---- Precision: [ 0.8617284   0.77777778  0.73214286  0.6         0.47826087  0.53731343
  0.6875      1.          0.          0.          0.75862069  0.45292621
  0.          0.73333333  0.          0.          0.89830508  0.375       0.15
  0.61333333  0.84313725  0.          0.86861314  0.875       0.5744089
  0.81656805  0.62264151  0.85106383  0.85714286  0.          0.79487179
  0.21052632  0.44444444  0.75862069  0.39285714  0.63636364  0.35534591
  1.          0.7826087   0.66666667  0.          0.          0.53250774
  0.          0.83333333  0.62765957  0.57142857  0.28        0.6
  0.22222222  0.          0.47142857  0.6875      0.38848921  0.
  0.57894737  0.66666667  0.51369863  0.8         0.62328767  1.          1.
  0.          0.37647059  0.8         0.12        0.          0.63636364
  0.          0.90116279  0.92682927  1.          0.91025641  0.52173913
  0.65373134  0.          0.21568627  0.77925532  0.          0.36363636
  0.          0.64705882  1.          0.83333333  0.78894472  0.33333333
  0.          0.          0.45528455  0.90909091  0.          1.
  0.47580645  0.          0.          0.2         0.66037736  1.
  0.71212121  1.          0.42857143  0.          0.69270833  0.92307692
  0.3         0.66666667  0.          0.5         0.66666667  0.5754717
  0.94117647  0.          0.          0.33333333  0.875       1.
  0.65909091  0.9375    ] / Recall: [ 0.99714286  0.93333333  0.5125      0.75        0.54098361  0.63157895
  0.44        0.26923077  0.          0.          0.84615385  0.80361174
  0.          0.54098361  0.          0.          0.84126984  0.42857143
  0.0483871   0.32624113  0.95555556  0.          0.99166667  0.58333333
  0.86221294  0.91390728  0.72131148  0.6779661   0.4137931   0.
  0.95384615  0.09375     0.23529412  0.91666667  0.5         0.56756757
  0.74834437  0.07692308  0.65693431  0.23255814  0.          0.
  0.75770925  0.          0.66666667  0.70238095  0.13793103  0.07865169
  0.11111111  0.03571429  0.          0.25581395  1.          0.44628099
  0.          0.39285714  0.75        0.86206897  0.92753623  0.91919192
  0.25        0.57894737  0.          0.78527607  0.63157895  0.02325581
  0.          0.13461538  0.          0.99358974  0.93442623  0.07142857
  0.97260274  0.4         0.96475771  0.          0.18333333  0.9184953   0.
  0.30769231  0.          0.26190476  0.60869565  0.55555556  0.97515528
  0.28571429  0.          0.          0.66666667  0.4         0.
  0.57142857  0.33714286  0.          0.          0.5         0.83333333
  0.52941176  0.88679245  0.25        0.4         0.          0.76
  0.66666667  0.09375     0.08928571  0.          0.33333333  0.11111111
  0.67032967  0.8         0.          0.          0.06521739  0.29166667
  0.33333333  0.3258427   0.75      ] / Accuracy: 0.62

In [31]:
train_RF(300, None) # 0.618 accuracy if i use wordnet lemamtizing

building tree 1 of 300
building tree 2 of 300building tree 3 of 300building tree 4 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   13.0s

building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   20.8s

building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   34.6s

building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   42.5s

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300
building tree 39 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.0min

building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300
building tree 47 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.2min

building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.7min

building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  1.9min

building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.5min

building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300
building tree 95 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.9min

building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  3.4min

building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  3.9min

building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  4.5min

building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  5.1min

building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  5.6min

building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  6.1min

building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300
building tree 217 of 300
building tree 218 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  6.7min

building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  7.2min

building tree 238 of 300
building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  7.8min

building tree 261 of 300
building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  8.3min

building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.7min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    1.6s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    2.9s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    5.2s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    7.4s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    8.4s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    8.7s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    9.0s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:    9.9s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:   15.0s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   16.1s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   17.7s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   19.0s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   21.5s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   22.1s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   23.2s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   25.7s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:   26.1s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: None ---- Precision: [ 0.90364583  0.85714286  0.61344538  0.65        0.46        0.52542373
  0.8125      0.90909091  0.          0.33333333  0.68656716  0.45974026
  0.          0.66666667  0.          0.          0.890625    0.85714286
  0.          0.71830986  0.79518072  0.          0.88429752  0.88235294
  0.60583942  0.80851064  0.70050761  0.87037037  0.84615385  0.          0.75
  0.0962963   0.33333333  0.77777778  0.42307692  0.67741935  0.34726688
  1.          0.78        0.56        0.          0.          0.55214724
  0.          0.8125      0.54954955  0.44444444  0.34285714  0.33333333
  0.25        0.          0.42857143  0.95454545  0.38562092  0.          0.6
  0.75        0.44654088  0.83333333  0.73228346  0.71428571  0.66666667
  0.          0.32361516  0.86666667  0.19230769  1.          0.55555556
  0.          0.9068323   0.88429752  1.          0.86206897  0.47368421
  0.73538462  1.          0.36956522  0.80678851  0.          0.375       0.
  0.75        0.82352941  0.66666667  0.81151832  0.36538462  0.          0.
  0.4789916   0.84615385  0.          1.          0.31707317  0.          0.
  0.          0.67272727  0.875       0.64705882  0.8         0.78571429
  0.          0.67582418  1.          0.37777778  0.5         0.          0.5
  0.          0.51587302  0.95454545  1.          0.8         0.4         0.5
  1.          0.68292683  0.9375    ] / Recall: [ 0.98860399  0.81818182  0.51048951  0.72222222  0.37704918  0.60784314
  0.39393939  0.34482759  0.          0.2         0.85185185  0.77124183
  0.          0.42622951  0.          0.          0.87692308  0.6         0.
  0.34931507  0.97058824  0.          0.97272727  0.78947368  0.87184874
  0.91566265  0.76666667  0.67142857  0.57894737  0.          1.
  0.08843537  0.16666667  0.91304348  0.52380952  0.56756757  0.72
  0.11111111  0.69642857  0.56        0.          0.          0.80357143
  0.          0.61904762  0.70114943  0.15384615  0.096       0.05263158
  0.03174603  0.          0.26712329  0.91304348  0.56730769  0.
  0.42857143  0.42857143  0.93421053  0.88235294  0.87735849  0.20833333
  0.47058824  0.          0.82222222  0.68421053  0.04504505  0.07407407
  0.11363636  0.          1.          0.97272727  0.16666667  0.97402597
  0.3         0.9795082   0.25        0.27868852  0.9251497   0.
  0.27272727  0.          0.46153846  0.53846154  0.53333333  0.98101266
  0.24675325  0.          0.          0.69512195  0.48529412  0.          1.
  0.27857143  0.          0.          0.          0.78723404  0.26923077
  0.88        0.21052632  0.55        0.          0.74096386  0.91666667
  0.27419355  0.0375      0.          0.15384615  0.          0.64356436
  0.84        0.25        0.09090909  0.03636364  0.35714286  0.57142857
  0.31818182  0.9375    ] / Accuracy: 0.617

In [14]:
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier()
param = {'n_estimators': [10, 150, 300],
        'max_depth': [30, 90, None],
         'verbose': [10]
        }

In [ ]:
gs = GridSearchCV(rf, param, cv=5, n_jobs=-1, verbose=10)
gs_fit = gs.fit(tfidf_vectorized_matrix_ps, data['label'])
pd.DataFrame(gs_fit.cv_results_).sort_values('mean_test_score', ascending=False)[0:5]

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   17.2s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:  4.2min
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:  8.6min
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed: 21.6min

### my laptop doesnt have enough memory to run GridsearchCV above 
### so I ran the same on EC2 instance and got n_est 300 and depth None as best mean test score

In [15]:
def train_GB(est, max_depth, lr):
    gb = GradientBoostingClassifier(n_estimators=est, max_depth=max_depth, learning_rate=lr , verbose=10)
    gb_model = gb.fit(X_train, y_train)
    y_pred = gb_model.predict(X_test)
    precision, recall, fscore, train_support = score(y_test, y_pred)
    print('Est: {} / Depth: {} / LR: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
        est, max_depth, lr, precision,recall, 
        round((y_pred==y_test).sum()/len(y_pred), 3)))

In [16]:
from ipywidgets import FloatProgress
from IPython.display import display

In [ ]:
max_count = 12
count = 0
progressBar = FloatProgress(min=0, max=max_count)
display(progressBar)

for n_est in [50, 100, 150]:
    for max_depth in [3, 7, 11, 15]:
        print("\n\nTraining combination: n_est:{n_est} - max_depth:{max_depth}".format(n_est=str(n_est),max_depth=str(max_depth)))
        progressBar.value+=1
        count += 1
        train_GB(n_est, max_depth, 0.01)

A Jupyter Widget

Training combination: 50 - 3

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

Est: 50 / Depth: 3 / LR: 0.01 ---- Precision: [ 0.93452381  0.96        0.73451327  0.75        0.28        0.48        0.71875
  0.45        0.          0.41666667  0.81538462  0.34558824  0.
  0.72972973  0.          0.16666667  0.74545455  0.83333333  0.07692308
  0.61458333  0.83333333  0.          0.90833333  0.75        0.65492958
  0.81761006  0.7         0.69565217  0.76470588  0.5         0.81428571
  0.30508475  0.57142857  0.90243902  0.53125     0.53846154  0.28851541
  0.66666667  0.65137615  0.38461538  0.83333333  1.          0.49832776
  0.          0.86956522  0.43434343  0.66666667  0.19354839  0.66666667
  0.08333333  0.55555556  0.40243902  1.          0.4159292   0.          0.53125
  1.          0.55555556  0.81578947  0.8         0.53846154  0.76470588
  0.          0.36394558  0.84615385  0.11363636  0.75        0.59259259
  0.          0.91156463  0.8877551   0.          0.89041096  0.41176471
  0.68543046  0.625       0.18681319  0.77777778  0.          0.66666667
  0.          0.43333333  0.61111111  0.63636364  0.83428571  0.40350877
  0.          0.          0.47863248  0.89655172  0.33333333  1.
  0.58823529  0.          0.3         0.16666667  0.71428571  0.55
  0.67142857  0.66666667  0.81818182  0.          0.65968586  0.94444444
  0.35897436  0.52173913  0.          0.5         0.75        0.48181818
  0.81818182  0.8         0.          0.23529412  0.38888889  0.5
  0.68518519  0.95      ] / Recall: [ 0.96024465  0.92307692  0.48538012  0.77777778  0.34146341  0.61016949
  0.60526316  0.36        0.          0.55555556  0.85483871  0.76334107
  0.          0.52941176  0.          0.16666667  0.70689655  0.55555556
  0.01219512  0.37341772  0.77464789  0.          0.90082645  0.85714286
  0.80345572  0.86092715  0.73684211  0.60377358  0.54166667  0.11111111
  0.91935484  0.24324324  0.34782609  0.80434783  0.60714286  0.65625
  0.79230769  0.36363636  0.57723577  0.27777778  0.38461538  0.33333333
  0.72682927  0.          0.70175439  0.5375      0.2         0.04545455
  0.14814815  0.01315789  0.07692308  0.23239437  0.88235294  0.4017094   0.
  0.68        0.5         0.80645161  0.86111111  0.81355932  0.31818182
  0.56521739  0.          0.76978417  0.45833333  0.04        0.28571429
  0.33333333  0.          0.86451613  0.93548387  0.          0.79268293
  0.58333333  0.90789474  0.71428571  0.28813559  0.88421053  0.
  0.31578947  0.          0.39393939  0.42307692  0.41176471  0.86390533
  0.26436782  0.          0.          0.64367816  0.40625     0.1
  0.85714286  0.23255814  0.          0.2         0.5         0.8         0.44
  0.79661017  0.52173913  0.31034483  0.          0.81818182  0.94444444
  0.19444444  0.11650485  0.          0.25        0.16666667  0.67088608
  0.6         0.8         0.          0.07843137  0.38888889  0.33333333
  0.52112676  0.9047619 ] / Accuracy: 0.59


Training combination: 50 - 7
Est: 50 / Depth: 7 / LR: 0.01 ---- Precision: [ 0.93529412  0.95        0.67521368  0.72413793  0.3125      0.49275362
  0.60526316  0.55555556  0.          0.2         0.82258065  0.34863388
  0.          0.68571429  0.          0.25        0.82        0.875
  0.08695652  0.60784314  0.83823529  0.          0.9137931   0.8
  0.66727941  0.81212121  0.66853933  0.68        0.86666667  0.          0.828125
  0.23893805  0.53846154  0.8974359   0.55555556  0.45714286  0.30943396
  0.5         0.63302752  0.13333333  0.83333333  1.          0.49458484
  0.          0.88636364  0.48148148  0.5         0.13924051  0.47826087
  0.2         0.30434783  0.30232558  1.          0.37414966  0.
  0.46666667  1.          0.56097561  0.82191781  0.80869565  0.45454545
  0.72222222  0.          0.34920635  0.8125      0.08333333  0.77777778
  0.46428571  0.          0.9205298   0.89690722  0.33333333  0.89041096
  0.40540541  0.66666667  0.57142857  0.15068493  0.78930818  0.          0.625
  0.          0.33333333  0.66666667  0.77777778  0.84745763  0.36538462
  0.          0.          0.46464646  0.78947368  0.3125      1.          0.4
  0.          0.125       0.33333333  0.70833333  0.52631579  0.66153846
  0.6875      0.7         0.33333333  0.68131868  0.94444444  0.40909091
  0.35294118  0.09090909  0.5         0.5         0.42477876  0.81818182
  0.66666667  0.07142857  0.36842105  0.35        1.          0.62962963
  0.9047619 ] / Recall: [ 0.97247706  0.73076923  0.4619883   0.77777778  0.36585366  0.57627119
  0.60526316  0.4         0.          0.11111111  0.82258065  0.74013921
  0.          0.47058824  0.          0.16666667  0.70689655  0.77777778
  0.02439024  0.39240506  0.8028169   0.          0.87603306  0.85714286
  0.78401728  0.88741722  0.69590643  0.64150943  0.54166667  0.
  0.85483871  0.18243243  0.30434783  0.76086957  0.53571429  0.5
  0.63076923  0.36363636  0.56097561  0.05555556  0.38461538  0.16666667
  0.66829268  0.          0.68421053  0.4875      0.175       0.08333333
  0.2037037   0.05263158  0.10769231  0.18309859  0.82352941  0.47008547
  0.          0.56        0.33333333  0.74193548  0.83333333  0.78813559
  0.22727273  0.56521739  0.          0.63309353  0.54166667  0.064
  0.33333333  0.27083333  0.          0.89677419  0.93548387  0.09090909
  0.79268293  0.625       0.81578947  0.57142857  0.18644068  0.88070175
  0.          0.26315789  0.          0.42424242  0.46153846  0.41176471
  0.88757396  0.2183908   0.          0.          0.52873563  0.46875
  0.16666667  0.85714286  0.36046512  0.          0.06666667  0.5         0.68
  0.4         0.72881356  0.47826087  0.24137931  0.33333333  0.80519481
  0.94444444  0.25        0.17475728  0.05357143  0.375       0.05555556
  0.60759494  0.6         0.8         0.03703704  0.1372549   0.38888889
  0.33333333  0.47887324  0.9047619 ] / Accuracy: 0.572


Training combination: 50 - 11
Est: 50 / Depth: 11 / LR: 0.01 ---- Precision: [ 0.94311377  0.95238095  0.65254237  0.65517241  0.3902439   0.41818182
  0.61538462  0.81818182  0.          0.          0.79365079  0.31034483
  0.          0.67647059  0.          0.25        0.86363636  0.77777778
  0.03846154  0.59433962  0.8         0.          0.91452991  0.78571429
  0.67931689  0.81578947  0.66091954  0.66037736  0.86666667  0.
  0.83333333  0.23376623  0.57142857  0.92105263  0.51724138  0.46875
  0.30204082  0.42857143  0.62244898  0.21428571  0.83333333  1.
  0.46570397  0.          0.86666667  0.44594595  0.57142857  0.09876543
  0.44        0.20833333  0.18181818  0.31818182  1.          0.33103448
  0.          0.46428571  1.          0.55555556  0.82352941  0.78448276
  0.4         0.90909091  0.          0.35950413  0.8         0.06481481
  0.77777778  0.42105263  0.          0.92810458  0.90425532  0.30769231
  0.91549296  0.46666667  0.66415094  0.71428571  0.17142857  0.8         0.
  0.7         0.          0.38461538  0.69230769  0.77777778  0.8372093
  0.30769231  0.          0.          0.46875     0.775       0.46153846
  1.          0.34337349  0.          0.22222222  0.25        0.7173913
  0.30769231  0.71186441  0.66666667  0.75        0.33333333  0.65027322
  0.94444444  0.43137255  0.35        0.06666667  0.42857143  0.33333333
  0.40740741  0.90909091  0.6         0.04761905  0.4         0.38888889
  0.33333333  0.68627451  0.90909091] / Recall: [ 0.96330275  0.76923077  0.4502924   0.7037037   0.3902439   0.38983051
  0.42105263  0.36        0.          0.          0.80645161  0.7099768   0.
  0.45098039  0.          0.16666667  0.65517241  0.77777778  0.01219512
  0.39873418  0.78873239  0.          0.88429752  0.78571429  0.77321814
  0.82119205  0.67251462  0.66037736  0.54166667  0.          0.80645161
  0.24324324  0.34782609  0.76086957  0.53571429  0.46875     0.56923077
  0.27272727  0.49593496  0.08333333  0.38461538  0.16666667  0.62926829
  0.          0.68421053  0.4125      0.2         0.06060606  0.2037037
  0.06578947  0.06153846  0.1971831   0.82352941  0.41025641  0.          0.52
  0.33333333  0.64516129  0.77777778  0.77118644  0.18181818  0.43478261
  0.          0.62589928  0.5         0.056       0.33333333  0.33333333
  0.          0.91612903  0.91397849  0.36363636  0.79268293  0.58333333
  0.77192982  0.71428571  0.20338983  0.87017544  0.          0.36842105
  0.          0.45454545  0.34615385  0.41176471  0.85207101  0.18390805
  0.          0.          0.51724138  0.484375    0.2         0.85714286
  0.33139535  0.          0.13333333  0.5         0.66        0.16
  0.71186441  0.43478261  0.31034483  0.33333333  0.77272727  0.94444444
  0.30555556  0.2038835   0.05357143  0.375       0.05555556  0.55696203
  0.66666667  0.6         0.03703704  0.23529412  0.38888889  0.33333333
  0.49295775  0.95238095] / Accuracy: 0.555


Training combination: 50 - 15

Est: 50 / Depth: 15 / LR: 0.01 ---- Precision: [ 0.94864048  0.95238095  0.62601626  0.59375     0.34285714  0.49019608
  0.64        0.64285714  0.          0.          0.77777778  0.27158099
  0.          0.64516129  0.          0.2         0.84444444  0.77777778
  0.03846154  0.52991453  0.79710145  0.          0.90677966  0.8
  0.66793893  0.82550336  0.69871795  0.70212766  0.92857143  0.
  0.81355932  0.17682927  0.5         0.92105263  0.48275862  0.46666667
  0.31481481  0.42857143  0.6         0.30434783  0.83333333  1.          0.4924812
  0.          0.82978723  0.44615385  0.52941176  0.09174312  0.42307692
  0.25        0.14814815  0.32467532  1.          0.37162162  0.
  0.51612903  1.          0.56521739  0.8358209   0.77777778  0.4
  0.90909091  0.          0.37089202  0.8         0.08823529  0.5
  0.45714286  0.07692308  0.93377483  0.91304348  0.25        0.92647059
  0.44444444  0.67054264  0.71428571  0.15789474  0.78456592  0.          0.6
  0.          0.37209302  0.61538462  0.75        0.83529412  0.30508475
  0.          0.          0.46511628  0.71428571  0.5         1.
  0.36363636  0.          0.22222222  0.16666667  0.76744186  0.35714286
  0.70909091  0.66666667  0.72727273  0.33333333  0.64285714  0.94117647
  0.4137931   0.35384615  0.05263158  0.28571429  0.33333333  0.41414141
  0.9         0.6         0.04761905  0.34146341  0.38888889  0.33333333
  0.63461538  0.9047619 ] / Recall: [ 0.96024465  0.76923077  0.4502924   0.7037037   0.29268293  0.42372881
  0.42105263  0.36        0.          0.          0.79032258  0.64965197
  0.          0.39215686  0.          0.16666667  0.65517241  0.77777778
  0.01219512  0.39240506  0.77464789  0.          0.88429752  0.85714286
  0.75593952  0.81456954  0.6374269   0.62264151  0.54166667  0.
  0.77419355  0.19594595  0.26086957  0.76086957  0.5         0.4375
  0.52307692  0.27272727  0.48780488  0.19444444  0.38461538  0.16666667
  0.63902439  0.          0.68421053  0.3625      0.225       0.07575758
  0.2037037   0.09210526  0.06153846  0.17605634  0.82352941  0.47008547
  0.          0.64        0.33333333  0.55913978  0.77777778  0.71186441
  0.18181818  0.43478261  0.          0.56834532  0.5         0.096
  0.14285714  0.33333333  0.02272727  0.90967742  0.90322581  0.18181818
  0.76829268  0.5         0.75877193  0.71428571  0.20338983  0.85614035
  0.          0.31578947  0.          0.48484848  0.30769231  0.35294118
  0.84023669  0.20689655  0.          0.          0.45977011  0.46875
  0.16666667  0.85714286  0.37209302  0.          0.13333333  0.5         0.66
  0.2         0.66101695  0.34782609  0.27586207  0.33333333  0.75974026
  0.88888889  0.33333333  0.22330097  0.03571429  0.25        0.05555556
  0.51898734  0.6         0.6         0.03703704  0.2745098   0.38888889
  0.33333333  0.46478873  0.9047619 ] / Accuracy: 0.541


Training combination: 100 - 3

In [ ]:
gb = GradientBoostingClassifier()
param = {
    'n_estimators': [50, 100, 150], 
    'max_depth': [7, 11, 15],
    'learning_rate': [0.01]
}

clf = GridSearchCV(gb, param, cv=5, n_jobs=-1)
cv_fit = clf.fit(tfidf_vectorized_matrix_ps, data['label'])
pd.DataFrame(cv_fit.cv_results_).sort_values('mean_test_score', ascending=False)[0:5]

### start to predict

In [26]:
tfidf_vectorizer_ps = TfidfVectorizer(analyzer=clean_text_by_porter_stem)
count_vectorizer_categories = CountVectorizer(analyzer=multiLabelBinarizer)

tfidf_vect_words_fit = tfidf_vectorizer_ps.fit(data['feature'])
count_vect_categories_fit = count_vectorizer_categories.fit(data['categories'])

tfidf_words_train = tfidf_vect_words_fit.transform(data['feature'])
count_categories_train = count_vect_categories_fit.transform(data['categories'])

vectorized_matrix_train = hstack([tfidf_words_train,count_categories_train], format='csr')

In [27]:
rf = RandomForestClassifier(n_estimators=300, max_depth=None, n_jobs=-1, verbose=10)
rf_model = rf.fit(vectorized_matrix_train, data['label'])

building tree 1 of 300
building tree 4 of 300building tree 3 of 300building tree 2 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   13.4s

building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   21.3s

building tree 14 of 300
building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   34.1s

building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   43.1s

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.1min

building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.3min

building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.7min

building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  1.9min

building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300
building tree 82 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.3min

building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.7min

building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  3.1min

building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  3.4min

building tree 124 of 300
building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  4.0min

building tree 141 of 300
building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  4.6min

building tree 158 of 300
building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  5.1min

building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  5.6min

building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  6.2min

building tree 217 of 300
building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  6.8min

building tree 238 of 300
building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  7.5min

building tree 261 of 300
building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  8.1min

building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.7min finished

In [44]:
features_importances_df=pd.DataFrame(list(zip(tfidf_vectorizer_ps.get_feature_names() + count_vectorizer_categories.get_feature_names(),rf_model.feature_importances_)))
features_importances_df.columns = ['feature','importance']

                     feature  importance
48830  Plumber                0.006462
33061  plumb                  0.006246
9168   clean                  0.006104
38486  servic                 0.005954
48837  Removalist             0.005578
48745  Bathroom Renovations   0.005392
48748  Bookkeeping            0.005279
1695   account                0.005231
48764  Cleaner                0.005099
48736  Accountant             0.004665
48750  Builder                0.004533
48822  Personal Trainer       0.004528
14290  electr                 0.004451
32595  photographi            0.004323
48777  Electrician            0.004291
48765  Computer Repair        0.004275
7397   busi                   0.003992
48785  Gas fitter             0.003864
34375  provid                 0.003789
48827  Photographer           0.003760
43015  tile                   0.003715
48857  Tiler                  0.003707
48801  Kitchen Renovations    0.003693
10208  concret                0.003622
48762  Celebrant              0.003614
48813  Office Cleaning        0.003595
48766  Concreting             0.003578
48747  Bond Cleaning          0.003561
48856  Tax Accountant         0.003536
31458  paint                  0.003528
...      ...                       ...
43846  treesfallen            0.000000
3217   antsspid               0.000000
46755  windodw                0.000000
20486  hornet                 0.000000
20485  horncastl              0.000000
20588  hoursweekend           0.000000
36771  rindworm               0.000000
33401  poshi                  0.000000
33416  possiblefor            0.000000
20652  housingtownhouseapart  0.000000
33419  possibleloc            0.000000
20641  houseswindow           0.000000
20633  housesoffic            0.000000
3289   aphid                  0.000000
46717  williamtown            0.000000
43916  trickiest              0.000000
20616  houseofficeapart       0.000000
3286   apfinsa                0.000000
36748  rightofpassag          0.000000
3268   apartmentunit          0.000000
26452  maintenanceupgrad      0.000000
20603  houseguard             0.000000
46725  willsi                 0.000000
20602  housefli               0.000000
3275   ape                    0.000000
43906  tribal                 0.000000
3273   apcr                   0.000000
36766  rimmington             0.000000
8006   carmeci                0.000000
35722  relac                  0.000000

[48874 rows x 2 columns]

In [ ]:
features_importances_df.sort_values('importance',ascending =False)

In [28]:
QUERY = """ 

with business_categories as (
select  bc.business_detail_id
,listagg(c.name,'|') within group (order by c.name) as categories
from mysql_oneflare_production.business_categories bc 
left join mysql_oneflare_production.categories c on bc.category_id = c.id
group by 1
)


SELECT
bm.id
,trim(nvl(bm.name,'') || ' ' || nvl(description,'')) "feature"
,bc.categories
FROM oneflare_reports.business_master bm
left join business_categories bc on bm.id = bc.business_detail_id
WHERE bm.total_quotes_made < 3
"""

In [29]:
data_to_predict=pd.read_sql(QUERY,redshift)

In [30]:
data_to_predict.head()

,id,feature,categories
0,54,Flushing Success,Carpet Cleaning|Cleaner|Grout Cleaner|Office Cleaning|Pool Cleaner
1,292,Yarra Plenty Accountants Yarra Plenty Accountants can help with all your bookkeeping requirement...,Accountant|Bookkeeping|Tax Accountant
2,645,Adrian Gold Painter Adrian Gold Painter has been in the painting business for many of our client...,Painter|Printing|Signwriter|T-Shirt Printing
3,657,Ads Painting pty ltd I provide a first class painting service for your home or business.\nWe ha...,Painter
4,709,Cutting Edge Painting,Interior Design|Painter|Wallpaper

In [31]:
#tfidf_vectorizer_ps = TfidfVectorizer(analyzer=clean_text_by_porter_stem)
#tfidf_vectorized_matrix_to_predict_ps = tfidf_vect_fit.transform(data_to_predict['feature'] )

tfidf_words_to_predict = tfidf_vect_words_fit.transform(data_to_predict['feature'])
count_categories_to_predict = count_vect_categories_fit.transform(data_to_predict['categories'])

vectorized_matrix_to_predict = hstack([tfidf_words_to_predict,count_categories_to_predict], format='csr')

In [32]:
y_to_predict = rf_model.predict(vectorized_matrix_to_predict)

[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    1.1s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    6.3s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    7.0s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    7.6s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    9.9s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:   10.9s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:   14.7s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:   15.4s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:   17.9s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   18.7s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   21.2s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   23.5s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   25.7s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   27.6s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   31.3s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   32.7s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:   34.8s finished

In [34]:
data_to_predict['predited_category'] = y_to_predict

In [35]:
data_to_predict.to_csv('predited_category_rf.csv',index=False)

In [36]:
pd.set_option('display.max_colwidth', -1)
data_to_predict.head()

,id,feature,categories,predited_category
0,54,Flushing Success,Carpet Cleaning|Cleaner|Grout Cleaner|Office Cleaning|Pool Cleaner,Cleaner
1,292,"Yarra Plenty Accountants Yarra Plenty Accountants can help with all your bookkeeping requirements.\nI have a Cert IV in Accounting.\nSpecialising in MYOB, Reckon and Quickbooks, Yarra Plenty Accountants provide a range of services to individuals and small businesses.",Accountant|Bookkeeping|Tax Accountant,Accountant
2,645,Adrian Gold Painter Adrian Gold Painter has been in the painting business for many of our clients.\nWe have a high attention to detail and pride in our work.\nReliable and professional.,Painter|Printing|Signwriter|T-Shirt Printing,Painter
3,657,"Ads Painting pty ltd I provide a first class painting service for your home or business.\nWe have been in the painting and decorating business for many years.\nThe company are highly skilled, professional and extremely reliable providing the very best painting services.",Painter,Painter
4,709,Cutting Edge Painting,Interior Design|Painter|Wallpaper,Partitioning

In [32]:
from sklearn.externals import joblib
joblib.dump(rf_model, 'random_forest.pkl') 
#clf = joblib.load('filename.pk1')

['random_forest.pkl']