In [1]:
from nltk.corpus import stopwords

stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [2]:
from sqlalchemy import create_engine
import pandas as pd
import re
import string
import nltk
pd.set_option('display.max_colwidth', 100)

In [3]:
QUERY=""" 
SELECT
trim(nvl(bm.name,'') || ' ' || nvl(description,'')) "feature"
,category_name "label"
FROM oneflare_reports.business_master bm
WHERE bm.total_quotes_made >= 3 and category_name is not null
"""

In [4]:
def make_engine():
    user = 'xxx'
    pw = 'xxx'
    db_name = 'xxx'
    host = 'xxx.xx.xx'
    port = 5439
    engine_string = "postgresql://%s:%s@%s:%s/%s" % (
        user, pw, host, port, db_name)
    engine = create_engine(engine_string)
    return engine

redshift = make_engine()
data=pd.read_sql(QUERY,redshift)

In [5]:
data.head()

,feature,label
0,"Anaxim Accounting Solutions The company is a qualified, professional accountant who deals with a...",Accountant
1,RCS Websites Let RCS Websites breath life in to your existing website!\r\nOur websites are simpl...,SEO and SEM
2,Intouch Carpet Cleaning Services InTouch Carpet and Pest Control is a family owned business who ...,Pest Control
3,Shannon Thomas Carpenter Licensed Carpenter\r\n - Small Decks and Pergolas as well as re deck...,Carpenter
4,"M&M Cabinets Custom-made Cabinets for kitchen, laundries, bathroom and anywhere in your house. 3...",Builder

In [6]:
stopwords = nltk.corpus.stopwords.words('english')
wn = nltk.WordNetLemmatizer()
ps = nltk.PorterStemmer()

In [79]:
'123'.isdigit()

True

In [7]:
def clean_text_by_porter_stem(text):

    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if (word not in stopwords) and (word.isdigit() ==False) ]
    
    return text

def clean_text_by_wordnet_lemmatize(text):

    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [wn.lemmatize(word)  for word in tokens if (word not in stopwords) and (word.isdigit() ==False)] 
    
    return text

In [13]:
#data.drop('feature_cleaned', axis=1, inplace=True)

In [28]:
data['feature_cleaned_ps']=data['feature'].apply(lambda x: clean_text_by_porter_stem( ('' if x is None else x).lower()))
data['feature_cleaned_wd']=data['feature'].apply(lambda x: clean_text_by_wordnet_lemmatize( ('' if x is None else x).lower()))

In [29]:
data.head()

,feature,label,feature_cleaned_ps,feature_cleaned_wd
0,"Anaxim Accounting Solutions The company is a qualified, professional accountant who deals with a...",Accountant,"[anaxim, account, solut, compani, qualifi, profession, account, deal, array, account, issu, prov...","[anaxim, accounting, solution, company, qualified, professional, accountant, deal, array, accoun..."
1,RCS Websites Let RCS Websites breath life in to your existing website!\r\nOur websites are simpl...,SEO and SEM,"[rc, websit, let, rc, websit, breath, life, exist, websit, websit, simpl, clean, profession, sur...","[rcs, website, let, rcs, website, breath, life, existing, website, website, simple, clean, profe..."
2,Intouch Carpet Cleaning Services InTouch Carpet and Pest Control is a family owned business who ...,Pest Control,"[intouch, carpet, clean, servic, intouch, carpet, pest, control, famili, own, busi, valu, old, f...","[intouch, carpet, cleaning, service, intouch, carpet, pest, control, family, owned, business, va..."
3,Shannon Thomas Carpenter Licensed Carpenter\r\n - Small Decks and Pergolas as well as re deck...,Carpenter,"[shannon, thoma, carpent, licens, carpent, small, deck, pergola, well, deck, repair, attent, det...","[shannon, thomas, carpenter, licensed, carpenter, small, deck, pergola, well, decking, repair, a..."
4,"M&M Cabinets Custom-made Cabinets for kitchen, laundries, bathroom and anywhere in your house. 3...",Builder,"[mm, cabinet, custommad, cabinet, kitchen, laundri, bathroom, anywher, hous, 3d, comput, draw, a...","[mm, cabinet, custommade, cabinet, kitchen, laundry, bathroom, anywhere, house, 3d, computer, dr..."

In [31]:
print(type(data.iloc[0]['feature_cleaned_ps']))
print(type(data.iloc[0]['feature_cleaned_wd']))

<class 'list'>
<class 'list'>

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [9]:
tfidf_vectorizer_ps = TfidfVectorizer(analyzer=clean_text_by_porter_stem)
tfidf_vectorized_matrix_ps = tfidf_vectorizer_ps.fit_transform(data['feature'] )

In [10]:
tfidf_vectorized_matrix_ps.shape

(38897, 48583)

In [21]:
tfidf_vectorized_df_ps = pd.DataFrame(tfidf_vectorized_matrix_ps.toarray())

MemoryError:

In [18]:
tfidf_vectorized_df_ps.head()

,0,1,2,3,4,5,6,7,8,9,...,48564,48565,48566,48567,48568,48569,48570,48571,48572,48573
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
tfidf_vectorizer_wn = TfidfVectorizer(analyzer=clean_text_by_wordnet_lemmatize)
tfidf_vectorized_matrix_wn = tfidf_vectorizer_wn.fit_transform(data['feature'])

In [63]:
tfidf_vectorized_matrix_wn.shape

(39014, 58815)

In [ ]:
tfidf_vectorizer_wn = TfidfVectorizer(analyzer=clean_text_by_wordnet_lemmatize)
tfidf_vectorized_matrix_wn = tfidf_vectorizer_wn.fit_transform(data['feature'])
tfidf_vectorized_df_wn = pd.DataFrame(tfidf_vectorized_matrix_wn.toarray())

In [19]:
tfidf_vectorized_df_ps_h = tfidf_vectorized_df_ps
tfidf_vectorized_df_ps_h.columns = tfidf_vectorizer_ps.get_feature_names()
tfidf_vectorized_df_ps_h.head()

,,00,000107l,000684l,000710l,001023l,01000sqm,0118651a01,012km,024481i,...,ўвўfrighten,ўвўhave,ўвўin,ўёўў,ўўв,中國理解,在墨尔本的中国婚礼乐队,ﬁnanc,ﬁnancial,ﬁngertip
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
tfidf_vectorized_df_wn_h = tfidf_vectorized_df_wn
tfidf_vectorized_df_wn_h.columns = tfidf_vectorizer_wn.get_feature_names()
tfidf_vectorized_df_wn_h.head()

In [11]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import precision_recall_fscore_support as score
import time

In [65]:
print(dir(RandomForestClassifier))
print(RandomForestClassifier())

['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_estimator_type', '_get_param_names', '_make_estimator', '_set_oob_score', '_validate_X_predict', '_validate_estimator', '_validate_y_class_weight', 'apply', 'decision_path', 'feature_importances_', 'fit', 'get_params', 'predict', 'predict_log_proba', 'predict_proba', 'score', 'set_params']
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [66]:
print(dir(GradientBoostingClassifier))
print(GradientBoostingClassifier())

['_SUPPORTED_LOSS', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_check_initialized', '_check_params', '_clear_state', '_decision_function', '_estimator_type', '_fit_stage', '_fit_stages', '_get_param_names', '_init_decision_function', '_init_state', '_is_initialized', '_make_estimator', '_resize_state', '_staged_decision_function', '_validate_estimator', '_validate_y', 'apply', 'decision_function', 'feature_importances_', 'fit', 'get_params', 'n_features', 'predict', 'predict_log_proba', 'predict_proba', 'score', 'set_params', 'staged_decision_function', 'staged_predict', 'staged_predict_proba']
GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

## Start to evaluate models

In [12]:
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(tfidf_vectorized_matrix_ps, data['label'], test_size=0.2)

In [28]:
print(X_train)
print(y_train)

  (0, 12554)	0.897560979187
  (0, 43683)	0.418577057734
  (0, 38357)	0.138482978662
  (1, 546)	0.153514794957
  (1, 25221)	0.140580537403
  (1, 27985)	0.614059179828
  (1, 30343)	0.129450761432
  (1, 31123)	0.116775518268
  (1, 10302)	0.0797108439834
  (1, 7831)	0.176736539174
  (1, 43756)	0.0797108439834
  (1, 1885)	0.0838096269878
  (1, 5411)	0.0679026764305
  (1, 31732)	0.089084966057
  (1, 38273)	0.102735537169
  (1, 44046)	0.0800556182295
  (1, 45950)	0.0960768681014
  (1, 17635)	0.240989165277
  (1, 47144)	0.0874223538907
  (1, 14034)	0.0742547705572
  (1, 41046)	0.106732115752
  (1, 32781)	0.138885720703
  (1, 39241)	0.0787243392195
  (1, 24799)	0.064152586744
  (1, 31790)	0.0704076165584
  :	:
  (31109, 4269)	0.0377460871041
  (31109, 35272)	0.0577218965356
  (31109, 24686)	0.0417189988265
  (31109, 21468)	0.0281246360286
  (31109, 3707)	0.100935388312
  (31109, 14571)	0.0423268753826
  (31109, 46080)	0.0482403344871
  (31109, 11701)	0.0361762110722
  (31109, 2750)	0.0289037009938
  (31109, 26419)	0.0322898505704
  (31109, 9435)	0.029176706815
  (31109, 20514)	0.0429523147684
  (31109, 27413)	0.0362260546839
  (31109, 29392)	0.0777149243008
  (31109, 43528)	0.0369232215741
  (31109, 15099)	0.040564659642
  (31109, 21584)	0.0289853454357
  (31109, 46899)	0.0648565924512
  (31109, 7718)	0.0563129109073
  (31109, 40154)	0.0270330351744
  (31109, 9988)	0.0295151781965
  (31109, 33974)	0.0353588278113
  (31109, 41667)	0.0354400159436
  (31109, 15343)	0.0450484575541
  (31109, 48055)	0.0226438182527
19634                  Tree Lopping
11354                       Fencing
26991                  Partitioning
13747               Carpet Cleaning
12442                    Accountant
35804              Wedding Car Hire
6660                Carpet Cleaning
15530                    Accountant
36342                       Pergola
12312                      Handyman
29114                       Glazier
5810                   Pest Control
15983                   Solar Panel
13605                    Accountant
26491                   Solar Panel
34408                    Accountant
11164               Carpet Cleaning
29109                   Lawn Mowing
24815                       Cleaner
30543              T-Shirt Printing
14093                       Pergola
1060                    Pet Sitting
21871                  Conveyancing
10337                 Makeup Artist
38780                     Celebrant
21543                    Accountant
14454                   Electrician
19832                  Videographer
23916                       Massage
20480                  Photographer
                    ...
11827                       Builder
6296                   Photographer
29715               Security System
29266                       Roofing
5378                       Gardener
4781                        Ceiling
29660          Wedding Hair Stylist
7469                Interior Design
25921    Prepurchase Car Inspection
5321                Carpet Cleaning
23824                       Painter
2980                      Carpenter
9817                        Decking
36115                       Painter
14067                    Accountant
8844                Computer Repair
25465                       Cleaner
2822                        Plumber
30377                     Wallpaper
12136                      Handyman
1541                     Accountant
2719                        Fencing
9912                     TV Repairs
30708                  Partitioning
31582               Computer Repair
12759                    Accountant
914                       Plasterer
22930               Security System
23594              Personal Trainer
38363                 Makeup Artist
Name: label, Length: 31110, dtype: object

In [31]:
print(X_test)

  (0, 10272)	0.248899690119
  (0, 44883)	0.248899690119
  (0, 3670)	0.2658434338
  (0, 23632)	0.5316868676
  (0, 23979)	0.210811382518
  (0, 32119)	0.192613791953
  (0, 11749)	0.22008787539
  (0, 25430)	0.222044491763
  (0, 19132)	0.130824386178
  (0, 26435)	0.119020203111
  (0, 14463)	0.18765297304
  (0, 29282)	0.11753117282
  (0, 35354)	0.163801977225
  (0, 31704)	0.106775275246
  (0, 38178)	0.142796360154
  (0, 39919)	0.138101859336
  (0, 5235)	0.220350590333
  (0, 12337)	0.0936864965212
  (0, 15249)	0.12099438661
  (0, 45669)	0.102670656056
  (0, 25754)	0.0851553043744
  (0, 14683)	0.0885781407425
  (0, 11701)	0.0911815794986
  (0, 44489)	0.112900334261
  (0, 21584)	0.073057114076
  :	:
  (7776, 14571)	0.0995837462847
  (7776, 17076)	0.0685402501629
  (7776, 37387)	0.105277003827
  (7776, 30447)	0.0601834483687
  (7776, 40154)	0.0636014563273
  (7776, 26337)	0.284373096009
  (7776, 44750)	0.0794525675833
  (7776, 33974)	0.0831898056697
  (7776, 41667)	0.0833808194948
  (7776, 38357)	0.107539066383
  (7777, 23167)	0.595892640529
  (7777, 40565)	0.212615355724
  (7777, 19955)	0.228554164934
  (7777, 35959)	0.183573275798
  (7777, 39564)	0.312208822892
  (7777, 5709)	0.200086893321
  (7777, 46899)	0.126870418158
  (7777, 40154)	0.158643509335
  (7777, 26337)	0.354661264981
  (7777, 23006)	0.154929327269
  (7777, 9988)	0.173209978736
  (7777, 35029)	0.229003851895
  (7777, 14253)	0.210838003378
  (7777, 34271)	0.120690015385
  (7777, 2125)	0.209156935879

In [15]:
def train_RF(n_est, depth):
    rf = RandomForestClassifier(n_estimators=n_est, max_depth=depth, n_jobs=-1)
    rf_model = rf.fit(X_train, y_train)
    y_pred = rf_model.predict(X_test)
    precision, recall, fscore, support = score(y_test, y_pred)
    print('Est: {} / Depth: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
        n_est, depth, precision, recall,
        round((y_pred==y_test).sum() / len(y_pred), 3)))

In [34]:
for n_est in [10, 50, 100]:
    for depth in [10, 20, 30, None]:
        train_RF(n_est, depth)

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 10 ---- Precision: [ 0.62993763  0.          0.16666667  0.          0.46153846  0.6         0.
  0.          0.          0.          0.          0.24217586  0.
  0.66666667  0.          0.66666667  0.          0.          0.36842105
  0.72916667  0.          0.83870968  0.85714286  0.12417686  0.61111111
  0.          0.33333333  0.88888889  0.          0.          0.          0.
  0.44444444  0.          0.          0.          0.          0.65384615
  0.          0.          0.          0.41208791  0.          0.71428571
  0.5         0.          0.          0.          0.          0.
  0.14285714  0.          0.          0.          0.          0.
  0.42635659  0.71428571  0.75728155  0.          0.5         0.
  0.32962963  0.33333333  0.5         0.          0.          0.
  0.62987013  0.71014493  0.          1.          0.          0.51456311
  0.          0.          0.421875    0.          0.          0.          0.
  0.          0.          0.61256545  0.          0.          0.
  0.33333333  0.          0.          0.          1.          0.          0.
  0.          0.5         0.          0.58928571  0.          0.          0.
  0.63855422  0.          0.34482759  0.          0.          0.          0.
  0.5         0.          0.          0.          0.25        0.          0.
  0.          0.        ] / Recall: [ 0.89380531  0.          0.00699301  0.          0.10526316  0.04        0.
  0.          0.          0.          0.          0.7629108   0.
  0.03921569  0.          0.03389831  0.          0.          0.09459459
  0.48611111  0.          0.89041096  0.66666667  0.81818182  0.2244898   0.
  0.03508772  0.47058824  0.          0.          0.          0.
  0.14814815  0.          0.          0.          0.          0.272       0.
  0.          0.          0.36585366  0.          0.51470588  0.01265823
  0.          0.          0.          0.          0.          0.00699301
  0.          0.          0.          0.          0.          0.64705882
  0.78125     0.8125      0.          0.03333333  0.          0.50568182
  0.09090909  0.00961538  0.          0.          0.          0.65100671
  0.9245283   0.          0.01219512  0.          0.73611111  0.          0.
  0.44554455  0.          0.          0.          0.          0.          0.
  0.74050633  0.          0.          0.          0.01428571  0.          0.
  0.          0.01324503  0.          0.          0.          0.02173913
  0.          0.54098361  0.          0.          0.          0.30285714
  0.          0.14285714  0.          0.          0.          0.
  0.45263158  0.          0.          0.          0.0212766   0.          0.
  0.          0.        ] / Accuracy: 0.323

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

Est: 10 / Depth: 20 ---- Precision: [ 0.71496437  0.75        0.57281553  0.          0.36666667  0.40625     0.5
  0.          0.          0.          0.82        0.23483226  0.
  0.16666667  0.          0.          0.6969697   0.          0.
  0.54545455  0.72727273  0.25        0.90666667  1.          0.23382273
  0.57608696  0.68674699  0.66666667  0.9         0.          0.54166667
  0.09090909  0.          0.75        1.          0.14285714  0.36        0.
  0.69411765  0.          0.          0.          0.42939481  0.
  0.67647059  0.44        0.          0.23076923  0.375       0.          0.
  0.11538462  1.          0.41935484  0.          1.          0.
  0.42857143  0.6875      0.49107143  0.33333333  0.55555556  0.
  0.33870968  0.25        0.33333333  0.          0.33333333  0.
  0.66847826  0.82653061  0.          0.86046512  0.          0.63461538
  0.          0.09090909  0.59139785  0.          0.          0.33333333
  0.30769231  0.          0.8         0.66197183  0.          0.          0.
  0.25        0.7826087   0.          0.          0.52941176  0.          0.
  0.          0.62790698  0.5         0.63461538  0.          0.85714286
  0.          0.51094891  0.5         0.36923077  0.          0.          0.
  0.          0.34831461  0.57142857  0.          0.33333333  0.38888889
  0.          0.          0.33333333  1.        ] / Recall: [ 0.8879056   0.14285714  0.41258741  0.          0.19298246  0.17333333
  0.16        0.          0.          0.          0.75925926  0.77230047
  0.          0.01960784  0.          0.          0.38983051  0.          0.
  0.12162162  0.55555556  0.08333333  0.93150685  0.11111111  0.88842975
  0.72108844  0.62295082  0.56140351  0.26470588  0.          0.2
  0.0078125   0.          0.33333333  0.03333333  0.025       0.15340909
  0.          0.472       0.          0.          0.          0.72682927
  0.          0.33823529  0.27848101  0.          0.02803738  0.05263158
  0.          0.          0.02097902  0.2         0.11016949  0.          0.025
  0.          0.52941176  0.34375     0.57291667  0.04347826  0.16666667
  0.          0.47727273  0.09090909  0.02884615  0.          0.02272727
  0.          0.82550336  0.76415094  0.          0.90243902  0.
  0.91666667  0.          0.01538462  0.72607261  0.          0.          0.1
  0.10526316  0.          0.22222222  0.89240506  0.          0.          0.
  0.01428571  0.26086957  0.          0.          0.05960265  0.          0.
  0.          0.58695652  0.04347826  0.54098361  0.          0.28571429
  0.          0.4         0.0625      0.34285714  0.          0.          0.
  0.          0.32631579  0.18181818  0.          0.05555556  0.14893617
  0.          0.          0.02439024  0.23076923] / Accuracy: 0.434

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 30 ---- Precision: [ 0.70613108  0.91666667  0.43859649  0.66666667  0.36734694  0.38888889
  0.25        0.75        0.          0.          0.82051282  0.26343612
  0.          0.6         0.          0.75        1.          0.11111111
  0.49152542  0.67010309  0.          0.90604027  0.71428571  0.26799486
  0.79754601  0.62874251  0.7173913   0.85        0.          0.67605634
  0.06666667  0.          0.42857143  0.28571429  0.41666667  0.3362069   1.
  0.66666667  0.30434783  0.          0.          0.43533123  0.
  0.64102564  0.34482759  0.          0.14285714  0.33333333  0.          0.2
  0.13333333  1.          0.31304348  0.          0.66666667  0.
  0.42962963  0.73333333  0.67226891  0.2         0.14285714  0.
  0.37241379  0.          0.          0.33333333  0.09090909  0.14285714
  0.7345679   0.80530973  0.66666667  0.8875      0.4375      0.56689342
  0.          0.          0.67718447  0.          0.          0.          0.5
  0.          0.          0.67156863  0.          0.          0.
  0.16666667  0.725       0.25        0.          0.41176471  0.          0.
  0.          0.25        0.33333333  0.68421053  0.          0.          0.
  0.56018519  0.33333333  0.2962963   0.15789474  0.          0.5
  0.66666667  0.30588235  0.33333333  0.          0.          0.25925926
  0.33333333  0.          0.          0.83333333] / Recall: [ 0.98525074  0.52380952  0.34965035  0.5         0.31578947  0.09333333
  0.04        0.10714286  0.          0.          0.59259259  0.70187793
  0.          0.23529412  0.          0.45762712  0.25        0.01351351
  0.19594595  0.90277778  0.          0.92465753  0.55555556  0.86157025
  0.88435374  0.57377049  0.57894737  0.5         0.          0.73846154
  0.0234375   0.          0.22222222  0.06666667  0.125       0.22159091
  0.11111111  0.496       0.175       0.          0.          0.67317073
  0.          0.36764706  0.25316456  0.          0.01869159  0.07017544
  0.          0.01886792  0.02797203  0.06666667  0.30508475  0.          0.15
  0.          0.68235294  0.859375    0.83333333  0.04347826  0.03333333
  0.          0.30681818  0.          0.          0.04347826  0.02272727
  0.02439024  0.79865772  0.85849057  0.10526316  0.86585366  0.29166667
  0.86805556  0.          0.          0.92079208  0.          0.          0.
  0.23684211  0.          0.          0.86708861  0.          0.          0.
  0.01428571  0.42028986  0.04545455  0.          0.13907285  0.          0.
  0.          0.02173913  0.04347826  0.63934426  0.          0.          0.
  0.69142857  0.0625      0.11428571  0.03947368  0.          0.07142857
  0.13333333  0.27368421  0.09090909  0.          0.          0.14893617
  0.06666667  0.          0.          0.38461538] / Accuracy: 0.469

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

Est: 10 / Depth: None ---- Precision: [ 0.84634761  0.53333333  0.34482759  0.52631579  0.28985507  0.42268041
  0.33333333  0.4         0.          0.2         0.71875     0.40196078
  0.25        0.47058824  0.          0.          0.75        0.42857143
  0.08333333  0.46616541  0.73404255  0.09090909  0.89440994  0.63636364
  0.59235669  0.7027027   0.61926606  0.70909091  0.82352941  0.33333333
  0.7125      0.09160305  0.14285714  0.52631579  0.42857143  0.40909091
  0.35294118  0.5         0.55555556  0.32        0.66666667  0.
  0.45454545  0.          0.7         0.41666667  0.41176471  0.15384615
  0.3         0.22222222  0.04347826  0.22222222  0.91666667  0.34883721
  0.          0.59259259  1.          0.46086957  0.65714286  0.73584906
  0.55555556  0.92857143  0.          0.39719626  0.91666667  0.05084746
  0.16666667  0.27777778  0.11111111  0.85365854  0.81666667  0.25
  0.78350515  0.53333333  0.74063401  0.66666667  0.14285714  0.72922252
  0.          0.          0.          0.5483871   0.625       0.58333333
  0.75757576  0.31428571  0.          0.5         0.46875     0.88888889
  0.          0.66666667  0.42608696  0.          0.          0.
  0.79487179  0.6         0.70967742  1.          0.15384615  0.
  0.62162162  0.8125      0.29411765  0.1875      0.14285714  0.
  0.33333333  0.42857143  0.88888889  1.          0.3125      0.19047619
  0.6         1.          0.56410256  0.83333333] / Recall: [ 0.99115044  0.76190476  0.55944056  0.5         0.35087719  0.54666667
  0.32        0.21428571  0.          0.25        0.85185185  0.67370892
  0.15384615  0.31372549  0.          0.          0.76271186  0.75
  0.08108108  0.41891892  0.95833333  0.08333333  0.98630137  0.38888889
  0.76859504  0.88435374  0.73770492  0.68421053  0.41176471  0.33333333
  0.87692308  0.09375     0.07692308  0.74074074  0.3         0.225
  0.51136364  0.11111111  0.56        0.2         0.28571429  0.
  0.68292683  0.          0.61764706  0.56962025  0.26923077  0.05607477
  0.05263158  0.08108108  0.01886792  0.15384615  0.73333333  0.25423729
  0.          0.4         0.14285714  0.62352941  0.71875     0.8125
  0.2173913   0.43333333  0.          0.48295455  0.5         0.02884615
  0.04347826  0.11363636  0.02439024  0.93959732  0.9245283   0.05263158
  0.92682927  0.33333333  0.89236111  0.33333333  0.07692308  0.89768977
  0.          0.          0.          0.44736842  0.22727273  0.38888889
  0.94936709  0.2037037   0.          0.13333333  0.42857143  0.34782609
  0.          0.4         0.32450331  0.          0.          0.
  0.67391304  0.13043478  0.72131148  0.16666667  0.0952381   0.
  0.65714286  0.8125      0.14285714  0.03947368  0.01538462  0.
  0.06666667  0.31578947  0.72727273  0.2         0.13888889  0.08510638
  0.2         0.5         0.26829268  0.76923077] / Accuracy: 0.551

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 10 ---- Precision: [ 0.73333333  0.          0.82        0.          0.46666667  0.          0.
  0.          0.          0.          0.          0.21931464  0.          1.
  0.          1.          0.          0.          0.          0.93181818
  0.          0.98058252  0.          0.14339981  0.81168831  0.75757576
  0.85714286  0.          0.          0.84615385  0.          0.          0.
  0.          0.          0.33333333  0.          1.          0.          0.
  0.          0.44444444  0.          1.          0.25        0.          0.
  0.          0.          0.          0.          0.          1.          0.
  0.          0.          0.38095238  0.86363636  0.81578947  0.          0.
  0.          0.37190083  0.          0.          0.          0.          0.
  0.72131148  0.94827586  0.          0.95833333  0.          0.58215962
  0.          0.          0.6835443   0.          0.          0.          0.
  0.          0.          0.82993197  0.          0.          0.          0.4
  1.          0.          0.          0.75862069  0.          0.          0.
  0.          0.          0.74358974  0.          0.          0.
  0.72972973  0.          0.75        0.          0.          0.          0.
  0.625       0.          0.          0.          0.          0.          0.
  0.          0.        ] / Recall: [ 0.97345133  0.          0.28671329  0.          0.24561404  0.          0.
  0.          0.          0.          0.          0.82629108  0.
  0.01960784  0.          0.11864407  0.          0.          0.
  0.56944444  0.          0.69178082  0.          0.93595041  0.85034014
  0.40983607  0.52631579  0.          0.          0.84615385  0.          0.
  0.          0.          0.          0.03409091  0.          0.016       0.
  0.          0.          0.42926829  0.          0.07352941  0.01265823
  0.          0.          0.          0.          0.          0.          0.
  0.00847458  0.          0.          0.          0.18823529  0.59375
  0.32291667  0.          0.          0.          0.25568182  0.          0.
  0.          0.          0.          0.88590604  0.51886792  0.          0.2804878
  0.          0.86111111  0.          0.          0.89108911  0.          0.
  0.          0.          0.          0.          0.7721519   0.          0.
  0.          0.02857143  0.04347826  0.          0.          0.14569536
  0.          0.          0.          0.          0.          0.47540984
  0.          0.          0.          0.61714286  0.          0.04285714
  0.          0.          0.          0.          0.26315789  0.          0.
  0.          0.          0.          0.          0.          0.        ] / Accuracy: 0.373

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 20 ---- Precision: [ 0.73960613  0.75        0.75        0.          0.38095238  0.42857143
  0.          0.          0.          0.          0.92105263  0.25302061
  0.          0.63636364  0.          0.92        0.          0.          0.75
  0.91525424  0.          0.97183099  1.          0.24759207  0.78947368
  0.74698795  0.8         0.94736842  0.          0.77333333  0.          0.
  0.875       0.71428571  0.5         0.37096774  0.          0.80487805
  0.33333333  0.          0.          0.42159383  0.          0.84615385
  0.44186047  0.          0.5         0.          0.          0.          0.7
  1.          0.28571429  0.          0.          0.          0.48571429
  0.82142857  0.67424242  0.          1.          0.          0.36723164
  0.          0.          0.          1.          0.          0.71921182
  0.85087719  0.          0.69642857  0.16666667  0.6347032   0.          0.
  0.6682243   0.          0.          0.          0.75        0.          0.
  0.69124424  0.          0.          0.          0.25        0.9047619   0.
  0.          0.5625      0.          0.          0.          0.81081081
  0.          0.66129032  0.          0.5         0.          0.60526316
  0.          0.375       0.          0.          0.          0.
  0.45901639  1.          0.          0.          0.          0.          0.
  0.          1.        ] / Recall: [ 0.99705015  0.57142857  0.41958042  0.          0.14035088  0.04        0.
  0.          0.          0.          0.64814815  0.83568075  0.          0.1372549
  0.          0.38983051  0.          0.          0.12162162  0.75        0.
  0.94520548  0.05555556  0.90289256  0.91836735  0.67759563  0.14035088
  0.52941176  0.          0.89230769  0.          0.          0.25925926
  0.16666667  0.025       0.39204545  0.          0.528       0.075       0.
  0.          0.8         0.          0.48529412  0.24050633  0.
  0.00934579  0.          0.          0.          0.04895105  0.06666667
  0.03389831  0.          0.          0.          0.8         0.71875
  0.92708333  0.          0.2         0.          0.36931818  0.          0.
  0.          0.02272727  0.          0.97986577  0.91509434  0.
  0.95121951  0.04166667  0.96527778  0.          0.          0.94389439
  0.          0.          0.          0.07894737  0.          0.
  0.94936709  0.          0.          0.          0.01428571  0.27536232
  0.          0.          0.17880795  0.          0.          0.
  0.65217391  0.          0.67213115  0.          0.04761905  0.
  0.65714286  0.          0.08571429  0.          0.          0.          0.
  0.29473684  0.09090909  0.          0.          0.          0.          0.
  0.          0.30769231] / Accuracy: 0.489

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 30 ---- Precision: [ 0.76309795  0.73684211  0.62037037  1.          0.45762712  0.60714286
  0.66666667  0.8         0.          0.          0.94871795  0.29958506
  0.          0.75        0.          1.          0.          0.
  0.72340426  0.87012987  0.          0.92857143  0.85714286  0.32041729
  0.78235294  0.71038251  0.78571429  1.          0.          0.77333333
  0.33333333  0.          0.72222222  0.66666667  0.          0.37325905
  0.          0.76829268  0.44444444  0.          0.          0.45689655
  0.          0.77358491  0.50819672  0.          0.33333333  0.          0.
  0.          0.53333333  0.          0.44186047  0.          0.59459459
  0.          0.50684932  0.71621622  0.6350365   0.          0.83333333
  0.          0.39442231  1.          0.5         0.          0.66666667
  0.          0.77777778  0.88392857  0.          0.74285714  0.
  0.64037123  0.          0.          0.6563981   0.          0.          0.
  0.86666667  0.          0.75        0.76142132  0.33333333  0.          0.
  0.46428571  0.94736842  0.          0.          0.5483871   0.          0.
  0.          0.67272727  0.          0.70588235  0.          1.          0.
  0.65317919  1.          0.38235294  0.          0.          0.          0.
  0.43396226  1.          0.          0.          0.2         0.          0.
  0.          0.        ] / Recall: [ 0.98820059  0.66666667  0.46853147  0.1         0.47368421  0.22666667
  0.16        0.14285714  0.          0.          0.68518519  0.84741784
  0.          0.23529412  0.          0.44067797  0.          0.
  0.22972973  0.93055556  0.          0.97945205  0.66666667  0.88842975
  0.9047619   0.71038251  0.57894737  0.05882353  0.          0.89230769
  0.03125     0.          0.48148148  0.13333333  0.          0.76136364
  0.          0.504       0.1         0.          0.          0.77560976
  0.          0.60294118  0.39240506  0.          0.01869159  0.          0.
  0.          0.05594406  0.          0.16101695  0.          0.55        0.
  0.87058824  0.828125    0.90625     0.          0.16666667  0.          0.5625
  0.04545455  0.00961538  0.          0.04545455  0.          0.98657718
  0.93396226  0.          0.95121951  0.          0.95833333  0.          0.
  0.91419142  0.          0.          0.          0.34210526  0.
  0.16666667  0.94936709  0.01851852  0.          0.          0.18571429
  0.26086957  0.          0.          0.22516556  0.          0.          0.
  0.80434783  0.          0.78688525  0.          0.19047619  0.
  0.64571429  0.3125      0.18571429  0.          0.          0.          0.
  0.48421053  0.31818182  0.          0.          0.0212766   0.          0.
  0.          0.        ] / Accuracy: 0.534

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: None ---- Precision: [ 0.87080103  0.71428571  0.55        0.77777778  0.44642857  0.57534247
  0.63636364  0.91666667  0.          0.2         0.92        0.41886792
  0.          0.71428571  0.          0.88461538  0.5         0.26086957
  0.62921348  0.68269231  0.25        0.94078947  0.85714286  0.58737151
  0.76111111  0.67317073  0.79245283  1.          0.          0.7721519
  0.20338983  0.28571429  0.76470588  0.42424242  0.51612903  0.38125     1.
  0.62809917  0.43333333  0.          0.          0.50159744  0.
  0.74576271  0.46534653  0.33333333  0.14285714  0.33333333  0.18181818
  0.22222222  0.4         1.          0.45283019  0.          0.56756757
  1.          0.47101449  0.67088608  0.69924812  0.5         1.          0.
  0.4025974   1.          0.06896552  0.33333333  0.4375      0.
  0.87647059  0.89090909  1.          0.82291667  0.35294118  0.74792244
  1.          0.18181818  0.7574124   1.          0.75        0.          0.8
  0.8         0.57142857  0.75242718  0.2972973   0.          0.
  0.45454545  0.96875     0.          1.          0.38461538  0.          0.5
  0.          0.77083333  0.85714286  0.765625    1.          0.4375      0.
  0.635       1.          0.38095238  0.42857143  0.33333333  0.25        1.
  0.42718447  1.          0.66666667  0.25        0.11111111  0.85714286
  1.          0.74193548  1.        ] / Recall: [ 0.99410029  0.71428571  0.53846154  0.7         0.43859649  0.56        0.28
  0.39285714  0.          0.25        0.85185185  0.78169014  0.
  0.39215686  0.          0.77966102  0.5         0.08108108  0.37837838
  0.98611111  0.08333333  0.97945205  0.66666667  0.82644628  0.93197279
  0.75409836  0.73684211  0.32352941  0.          0.93846154  0.09375
  0.15384615  0.96296296  0.46666667  0.4         0.69318182  0.11111111
  0.608       0.325       0.          0.          0.76585366  0.
  0.64705882  0.59493671  0.15384615  0.05607477  0.03508772  0.02702703
  0.03773585  0.22377622  0.93333333  0.40677966  0.          0.525
  0.57142857  0.76470588  0.828125    0.96875     0.13043478  0.63333333
  0.          0.70454545  0.63636364  0.03846154  0.08695652  0.15909091
  0.          1.          0.9245283   0.10526316  0.96341463  0.25        0.9375
  0.33333333  0.09230769  0.92739274  0.16666667  0.16666667  0.
  0.42105263  0.36363636  0.44444444  0.98101266  0.2037037   0.          0.
  0.57142857  0.44927536  0.          0.6         0.29801325  0.          0.04
  0.          0.80434783  0.26086957  0.80327869  0.29166667  0.33333333
  0.          0.72571429  0.875       0.22857143  0.03947368  0.01538462
  0.07142857  0.06666667  0.46315789  0.77272727  0.4         0.05555556
  0.04255319  0.4         0.5         0.2804878   0.92307692] / Accuracy: 0.604

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: 10 ---- Precision: [ 0.72354212  1.          0.66666667  0.          0.42857143  0.          0.
  0.          0.          0.          0.94736842  0.1511254   0.          0.
  0.          0.          0.          0.          0.          0.95454545
  0.          0.96376812  0.          0.20455581  0.86086957  0.77443609
  0.76190476  0.          0.          1.          0.          0.          0.
  0.          0.          0.39622642  0.          0.84615385  0.          0.
  0.          0.48878924  0.          1.          0.55555556  0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.47540984  0.67948718  0.75        0.          0.
  0.          0.44444444  0.          0.          0.          0.          0.
  0.76136364  0.94339623  0.          0.92957746  0.          0.71544715
  0.          0.          0.61075269  0.          0.          0.          0.
  0.          0.          0.83561644  0.          0.          0.          0.
  0.          0.          0.          0.83333333  0.          0.          0.
  1.          0.          0.80952381  0.          0.          0.
  0.71428571  0.          0.16666667  0.          0.          0.          0.
  0.33333333  0.          0.          0.          0.          0.          0.
  0.          0.        ] / Recall: [ 0.98820059  0.04761905  0.39160839  0.          0.10526316  0.          0.
  0.          0.          0.          0.33333333  0.88262911  0.          0.
  0.          0.          0.          0.          0.          0.29166667
  0.          0.9109589   0.          0.92768595  0.67346939  0.56284153
  0.56140351  0.          0.          0.13846154  0.          0.          0.
  0.          0.          0.11931818  0.          0.44        0.          0.
  0.          0.53170732  0.          0.02941176  0.12658228  0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.68235294  0.828125    0.125       0.          0.
  0.          0.13636364  0.          0.          0.          0.          0.
  0.89932886  0.47169811  0.          0.80487805  0.          0.91666667
  0.          0.          0.93729373  0.          0.          0.          0.
  0.          0.          0.7721519   0.          0.          0.          0.
  0.          0.          0.          0.13245033  0.          0.          0.
  0.06521739  0.          0.27868852  0.          0.          0.
  0.34285714  0.          0.01428571  0.          0.          0.          0.
  0.02105263  0.          0.          0.          0.          0.          0.
  0.          0.        ] / Accuracy: 0.386

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: 20 ---- Precision: [ 0.78554779  0.84615385  0.68888889  0.          0.47058824  0.          0.
  0.          0.          0.          0.9047619   0.27054264  0.
  0.71428571  0.          1.          0.          1.          0.66666667
  0.9047619   0.          0.97241379  1.          0.22107969  0.82208589
  0.72077922  0.80851064  0.          0.          0.84285714  0.          0.
  0.66666667  0.          0.33333333  0.35106383  0.          0.81012658
  0.33333333  0.          0.          0.42487047  0.          0.81578947
  0.42105263  0.          0.          0.          0.          0.          0.4
  0.          0.18181818  0.          1.          0.          0.4829932
  0.71428571  0.68103448  0.          0.          0.          0.38487973
  0.          0.          0.          0.          0.          0.74489796
  0.85087719  0.          0.8875      0.          0.66507177  0.          0.
  0.68509615  0.          0.          0.          0.          0.          0.
  0.76439791  0.          0.          0.          0.36111111  1.          0.
  0.          0.70212766  0.          0.          0.          0.75        0.
  0.73076923  0.          0.          0.          0.68571429  0.          0.3
  0.          0.          0.          0.          0.47540984  0.          0.
  0.          0.          0.          0.          0.          1.        ] / Recall: [ 0.99410029  0.52380952  0.43356643  0.          0.28070175  0.          0.
  0.          0.          0.          0.7037037   0.81924883  0.
  0.19607843  0.          0.30508475  0.          0.01351351  0.12162162
  0.79166667  0.          0.96575342  0.11111111  0.88842975  0.91156463
  0.60655738  0.66666667  0.          0.          0.90769231  0.          0.
  0.14814815  0.          0.05        0.375       0.          0.512       0.025
  0.          0.          0.8         0.          0.45588235  0.20253165
  0.          0.          0.          0.          0.          0.01398601
  0.          0.01694915  0.          0.175       0.          0.83529412
  0.78125     0.82291667  0.          0.          0.          0.63636364
  0.          0.          0.          0.          0.          0.97986577
  0.91509434  0.          0.86585366  0.          0.96527778  0.          0.
  0.94059406  0.          0.          0.          0.          0.          0.
  0.92405063  0.          0.          0.          0.18571429  0.26086957
  0.          0.          0.21854305  0.          0.          0.
  0.32608696  0.          0.62295082  0.          0.          0.
  0.68571429  0.          0.04285714  0.          0.          0.          0.
  0.30526316  0.          0.          0.          0.          0.          0.
  0.          0.30769231] / Accuracy: 0.488

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: 30 ---- Precision: [ 0.79342723  0.92857143  0.61983471  0.75        0.44444444  0.66666667
  0.5         1.          0.          0.          0.91111111  0.27722008
  0.          0.81818182  0.          0.93939394  0.          0.
  0.69230769  0.88157895  0.          0.95333333  0.83333333  0.33754941
  0.75138122  0.7183908   0.88        0.5         0.          0.79487179
  0.          0.          0.73684211  0.5         0.61538462  0.35310734
  0.          0.75581395  0.54545455  0.          0.          0.42821159
  0.          0.91428571  0.48235294  0.          1.          0.          0.
  0.          0.55555556  0.          0.47826087  0.          0.61904762
  0.          0.47945205  0.7027027   0.70731707  0.          1.          0.
  0.38811189  1.          0.          0.          0.          0.
  0.71014493  0.86842105  0.          0.87058824  0.33333333  0.68215159
  0.          0.          0.68446602  0.          0.          0.          0.4
  0.          1.          0.7294686   0.          0.          0.
  0.46969697  1.          0.          0.          0.55405405  0.          0.
  0.          0.8         0.          0.8125      0.          0.          0.
  0.62371134  1.          0.33333333  1.          0.          0.          0.
  0.48780488  1.          0.          0.          0.5         0.          0.
  0.          1.        ] / Recall: [ 0.99705015  0.61904762  0.52447552  0.15        0.28070175  0.02666667
  0.08        0.03571429  0.          0.          0.75925926  0.842723    0.
  0.17647059  0.          0.52542373  0.          0.          0.18243243
  0.93055556  0.          0.97945205  0.27777778  0.8822314   0.92517007
  0.68306011  0.77192982  0.02941176  0.          0.95384615  0.          0.
  0.51851852  0.16666667  0.2         0.71022727  0.          0.52        0.15
  0.          0.          0.82926829  0.          0.47058824  0.51898734
  0.          0.00934579  0.          0.          0.          0.1048951   0.
  0.09322034  0.          0.325       0.          0.82352941  0.8125
  0.90625     0.          0.13333333  0.          0.63068182  0.09090909
  0.          0.          0.          0.          0.98657718  0.93396226
  0.          0.90243902  0.04166667  0.96875     0.          0.
  0.93069307  0.          0.          0.          0.05263158  0.
  0.11111111  0.9556962   0.          0.          0.          0.44285714
  0.34782609  0.          0.          0.27152318  0.          0.          0.
  0.60869565  0.          0.85245902  0.          0.          0.
  0.69142857  0.3125      0.14285714  0.02631579  0.          0.          0.
  0.42105263  0.40909091  0.          0.          0.0212766   0.          0.
  0.          0.76923077] / Accuracy: 0.536

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: None ---- Precision: [ 0.87532468  0.78947368  0.53571429  0.82352941  0.42857143  0.61643836
  0.7         1.          0.          0.          0.88235294  0.42346939
  0.          0.65517241  0.          0.94117647  0.6         0.18518519
  0.65168539  0.8045977   0.          0.94117647  0.83333333  0.59851852
  0.75824176  0.68556701  0.78947368  0.93333333  0.66666667  0.7721519
  0.18421053  0.28571429  0.77419355  0.5483871   0.5625      0.38138138
  0.66666667  0.73529412  0.43478261  0.          0.          0.48181818
  0.          0.72580645  0.50515464  0.5         0.4         0.55555556
  0.25        0.          0.41666667  1.          0.44859813  0.
  0.54545455  1.          0.50757576  0.7012987   0.70895522  0.33333333
  1.          0.          0.39090909  1.          0.07317073  0.4
  0.54545455  0.          0.85632184  0.87610619  1.          0.87777778
  0.52173913  0.75833333  1.          0.29268293  0.76630435  0.
  0.71428571  0.          0.71428571  0.81818182  0.53846154  0.78282828
  0.26829268  0.          0.          0.44897959  0.96969697  0.          1.
  0.3853211   0.          0.          0.          0.79591837  1.
  0.78688525  0.81818182  0.57142857  0.          0.60093897  1.          0.4
  0.57142857  0.5         0.42857143  1.          0.49557522  0.94444444
  0.75        0.33333333  0.2         0.75        1.          0.67741935
  0.9       ] / Recall: [ 0.99410029  0.71428571  0.52447552  0.7         0.36842105  0.6         0.56
  0.35714286  0.          0.          0.83333333  0.77934272  0.
  0.37254902  0.          0.81355932  0.75        0.06756757  0.39189189
  0.97222222  0.          0.98630137  0.55555556  0.83471074  0.93877551
  0.72677596  0.78947368  0.41176471  0.66666667  0.93846154  0.109375
  0.15384615  0.88888889  0.56666667  0.45        0.72159091  0.22222222
  0.6         0.5         0.          0.          0.77560976  0.
  0.66176471  0.62025316  0.19230769  0.11214953  0.0877193   0.02702703
  0.          0.20979021  0.93333333  0.40677966  0.          0.6
  0.28571429  0.78823529  0.84375     0.98958333  0.04347826  0.6         0.
  0.73295455  0.45454545  0.02884615  0.08695652  0.13636364  0.          1.
  0.93396226  0.15789474  0.96341463  0.5         0.94791667  0.66666667
  0.18461538  0.93069307  0.          0.27777778  0.          0.39473684
  0.40909091  0.38888889  0.98101266  0.2037037   0.          0.
  0.62857143  0.46376812  0.          0.8         0.2781457   0.          0.
  0.          0.84782609  0.17391304  0.78688525  0.375       0.38095238
  0.          0.73142857  0.8125      0.28571429  0.05263158  0.01538462
  0.21428571  0.13333333  0.58947368  0.77272727  0.6         0.08333333
  0.06382979  0.4         1.          0.25609756  0.69230769] / Accuracy: 0.614

In [14]:
from sklearn.model_selection import GridSearchCV

In [38]:
rf = RandomForestClassifier()
param = {'n_estimators': [10, 150, 300],
        'max_depth': [30, 60, 90, None]}

In [ ]:
train_RF(150, None)

In [16]:
train_RF(300, None)

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: None ---- Precision: [ 0.91269841  0.79166667  0.50714286  0.79310345  0.47058824  0.57971014
  0.76470588  0.71428571  0.          0.25        0.78571429  0.41724942
  0.          0.65957447  0.          0.          0.83050847  1.          0.
  0.68421053  0.82978723  0.          0.91724138  0.73913043  0.55036496
  0.77272727  0.59585492  0.796875    0.86666667  0.          0.77142857
  0.26804124  0.75        0.69565217  0.53571429  0.71794872  0.37864078
  0.          0.79        0.28205128  1.          0.25        0.54754098
  0.          0.8372093   0.50666667  0.5         0.21568627  0.625       0.4
  0.          0.35087719  0.95        0.34193548  0.          0.6         0.9
  0.46022727  0.79310345  0.73451327  1.          0.92857143  0.
  0.41176471  0.75        0.03703704  0.66666667  0.57142857  0.33333333
  0.88        0.80357143  0.75        0.85        0.41666667  0.65970149
  1.          0.11538462  0.76442308  1.          1.          0.
  0.63157895  0.91666667  0.83333333  0.80295567  0.31914894  0.          0.
  0.52380952  0.86206897  0.          1.          0.40462428  0.          1.
  0.          0.68852459  0.6         0.68        0.9         0.64285714
  0.          0.6954023   1.          0.35849057  0.55555556  0.11111111
  0.75        0.5         0.55479452  0.94736842  1.          0.          0.
  0.75        0.33333333  0.65517241  1.        ] / Recall: [ 0.98571429  0.79166667  0.4965035   0.88461538  0.28070175  0.64516129
  0.39393939  0.26315789  0.          0.2         0.8         0.78508772
  0.          0.60784314  0.          0.          0.875       0.57142857
  0.          0.30409357  0.975       0.          0.97794118  0.80952381
  0.86666667  0.91275168  0.67647059  0.75        0.46428571  0.
  0.91525424  0.15757576  0.26086957  0.76190476  0.53571429  0.58333333
  0.57777778  0.          0.60769231  0.34375     0.16666667  0.25
  0.74887892  0.          0.8         0.51351351  0.19354839  0.08870968
  0.08474576  0.03333333  0.          0.25806452  1.          0.46086957
  0.          0.52173913  0.75        0.96428571  0.85185185  0.90217391
  0.13043478  0.5         0.          0.83802817  0.81818182  0.00934579
  0.10526316  0.13114754  0.02857143  0.97777778  0.9375      0.17647059
  0.95774648  0.47619048  0.96929825  0.6         0.06382979  0.94362018
  0.07692308  0.2         0.          0.33333333  0.5         0.55555556
  0.95882353  0.27272727  0.          0.          0.63461538  0.52083333
  0.          0.66666667  0.42424242  0.          0.05263158  0.          0.875
  0.17647059  0.72340426  0.33333333  0.42857143  0.          0.69942197
  0.64285714  0.3015873   0.05102041  0.01492537  0.33333333  0.0625
  0.69230769  0.85714286  0.33333333  0.          0.          0.33333333
  0.16666667  0.26388889  0.88888889] / Accuracy: 0.606

In [ ]:
gs = GridSearchCV(rf, param, cv=5, n_jobs=-1)
gs_fit = gs.fit(tfidf_vectorized_matrix_ps, data['label'])
pd.DataFrame(gs_fit.cv_results_).sort_values('mean_test_score', ascending=False)[0:5]

In [15]:
def train_GB(est, max_depth, lr):
    gb = GradientBoostingClassifier(n_estimators=est, max_depth=max_depth, learning_rate=lr)
    gb_model = gb.fit(X_train, y_train)
    y_pred = gb_model.predict(X_test)
    precision, recall, fscore, train_support = score(y_test, y_pred)
    print('Est: {} / Depth: {} / LR: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
        est, max_depth, lr, precision,recall, 
        round((y_pred==y_test).sum()/len(y_pred), 3)))

In [16]:
from ipywidgets import FloatProgress
from IPython.display import display

In [ ]:
max_count = 12
count = 0
progressBar = FloatProgress(min=0, max=max_count)
display(progressBar)

for n_est in [50, 100, 150]:
    for max_depth in [3, 7, 11, 15]:
        print("\n\nTraining combination: n_est:{n_est} - max_depth:{max_depth}".format(n_est=str(n_est),max_depth=str(max_depth)))
        progressBar.value+=1
        count += 1
        train_GB(n_est, max_depth, 0.01)

A Jupyter Widget

Training combination: 50 - 3

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

Est: 50 / Depth: 3 / LR: 0.01 ---- Precision: [ 0.93452381  0.96        0.73451327  0.75        0.28        0.48        0.71875
  0.45        0.          0.41666667  0.81538462  0.34558824  0.
  0.72972973  0.          0.16666667  0.74545455  0.83333333  0.07692308
  0.61458333  0.83333333  0.          0.90833333  0.75        0.65492958
  0.81761006  0.7         0.69565217  0.76470588  0.5         0.81428571
  0.30508475  0.57142857  0.90243902  0.53125     0.53846154  0.28851541
  0.66666667  0.65137615  0.38461538  0.83333333  1.          0.49832776
  0.          0.86956522  0.43434343  0.66666667  0.19354839  0.66666667
  0.08333333  0.55555556  0.40243902  1.          0.4159292   0.          0.53125
  1.          0.55555556  0.81578947  0.8         0.53846154  0.76470588
  0.          0.36394558  0.84615385  0.11363636  0.75        0.59259259
  0.          0.91156463  0.8877551   0.          0.89041096  0.41176471
  0.68543046  0.625       0.18681319  0.77777778  0.          0.66666667
  0.          0.43333333  0.61111111  0.63636364  0.83428571  0.40350877
  0.          0.          0.47863248  0.89655172  0.33333333  1.
  0.58823529  0.          0.3         0.16666667  0.71428571  0.55
  0.67142857  0.66666667  0.81818182  0.          0.65968586  0.94444444
  0.35897436  0.52173913  0.          0.5         0.75        0.48181818
  0.81818182  0.8         0.          0.23529412  0.38888889  0.5
  0.68518519  0.95      ] / Recall: [ 0.96024465  0.92307692  0.48538012  0.77777778  0.34146341  0.61016949
  0.60526316  0.36        0.          0.55555556  0.85483871  0.76334107
  0.          0.52941176  0.          0.16666667  0.70689655  0.55555556
  0.01219512  0.37341772  0.77464789  0.          0.90082645  0.85714286
  0.80345572  0.86092715  0.73684211  0.60377358  0.54166667  0.11111111
  0.91935484  0.24324324  0.34782609  0.80434783  0.60714286  0.65625
  0.79230769  0.36363636  0.57723577  0.27777778  0.38461538  0.33333333
  0.72682927  0.          0.70175439  0.5375      0.2         0.04545455
  0.14814815  0.01315789  0.07692308  0.23239437  0.88235294  0.4017094   0.
  0.68        0.5         0.80645161  0.86111111  0.81355932  0.31818182
  0.56521739  0.          0.76978417  0.45833333  0.04        0.28571429
  0.33333333  0.          0.86451613  0.93548387  0.          0.79268293
  0.58333333  0.90789474  0.71428571  0.28813559  0.88421053  0.
  0.31578947  0.          0.39393939  0.42307692  0.41176471  0.86390533
  0.26436782  0.          0.          0.64367816  0.40625     0.1
  0.85714286  0.23255814  0.          0.2         0.5         0.8         0.44
  0.79661017  0.52173913  0.31034483  0.          0.81818182  0.94444444
  0.19444444  0.11650485  0.          0.25        0.16666667  0.67088608
  0.6         0.8         0.          0.07843137  0.38888889  0.33333333
  0.52112676  0.9047619 ] / Accuracy: 0.59


Training combination: 50 - 7
Est: 50 / Depth: 7 / LR: 0.01 ---- Precision: [ 0.93529412  0.95        0.67521368  0.72413793  0.3125      0.49275362
  0.60526316  0.55555556  0.          0.2         0.82258065  0.34863388
  0.          0.68571429  0.          0.25        0.82        0.875
  0.08695652  0.60784314  0.83823529  0.          0.9137931   0.8
  0.66727941  0.81212121  0.66853933  0.68        0.86666667  0.          0.828125
  0.23893805  0.53846154  0.8974359   0.55555556  0.45714286  0.30943396
  0.5         0.63302752  0.13333333  0.83333333  1.          0.49458484
  0.          0.88636364  0.48148148  0.5         0.13924051  0.47826087
  0.2         0.30434783  0.30232558  1.          0.37414966  0.
  0.46666667  1.          0.56097561  0.82191781  0.80869565  0.45454545
  0.72222222  0.          0.34920635  0.8125      0.08333333  0.77777778
  0.46428571  0.          0.9205298   0.89690722  0.33333333  0.89041096
  0.40540541  0.66666667  0.57142857  0.15068493  0.78930818  0.          0.625
  0.          0.33333333  0.66666667  0.77777778  0.84745763  0.36538462
  0.          0.          0.46464646  0.78947368  0.3125      1.          0.4
  0.          0.125       0.33333333  0.70833333  0.52631579  0.66153846
  0.6875      0.7         0.33333333  0.68131868  0.94444444  0.40909091
  0.35294118  0.09090909  0.5         0.5         0.42477876  0.81818182
  0.66666667  0.07142857  0.36842105  0.35        1.          0.62962963
  0.9047619 ] / Recall: [ 0.97247706  0.73076923  0.4619883   0.77777778  0.36585366  0.57627119
  0.60526316  0.4         0.          0.11111111  0.82258065  0.74013921
  0.          0.47058824  0.          0.16666667  0.70689655  0.77777778
  0.02439024  0.39240506  0.8028169   0.          0.87603306  0.85714286
  0.78401728  0.88741722  0.69590643  0.64150943  0.54166667  0.
  0.85483871  0.18243243  0.30434783  0.76086957  0.53571429  0.5
  0.63076923  0.36363636  0.56097561  0.05555556  0.38461538  0.16666667
  0.66829268  0.          0.68421053  0.4875      0.175       0.08333333
  0.2037037   0.05263158  0.10769231  0.18309859  0.82352941  0.47008547
  0.          0.56        0.33333333  0.74193548  0.83333333  0.78813559
  0.22727273  0.56521739  0.          0.63309353  0.54166667  0.064
  0.33333333  0.27083333  0.          0.89677419  0.93548387  0.09090909
  0.79268293  0.625       0.81578947  0.57142857  0.18644068  0.88070175
  0.          0.26315789  0.          0.42424242  0.46153846  0.41176471
  0.88757396  0.2183908   0.          0.          0.52873563  0.46875
  0.16666667  0.85714286  0.36046512  0.          0.06666667  0.5         0.68
  0.4         0.72881356  0.47826087  0.24137931  0.33333333  0.80519481
  0.94444444  0.25        0.17475728  0.05357143  0.375       0.05555556
  0.60759494  0.6         0.8         0.03703704  0.1372549   0.38888889
  0.33333333  0.47887324  0.9047619 ] / Accuracy: 0.572


Training combination: 50 - 11
Est: 50 / Depth: 11 / LR: 0.01 ---- Precision: [ 0.94311377  0.95238095  0.65254237  0.65517241  0.3902439   0.41818182
  0.61538462  0.81818182  0.          0.          0.79365079  0.31034483
  0.          0.67647059  0.          0.25        0.86363636  0.77777778
  0.03846154  0.59433962  0.8         0.          0.91452991  0.78571429
  0.67931689  0.81578947  0.66091954  0.66037736  0.86666667  0.
  0.83333333  0.23376623  0.57142857  0.92105263  0.51724138  0.46875
  0.30204082  0.42857143  0.62244898  0.21428571  0.83333333  1.
  0.46570397  0.          0.86666667  0.44594595  0.57142857  0.09876543
  0.44        0.20833333  0.18181818  0.31818182  1.          0.33103448
  0.          0.46428571  1.          0.55555556  0.82352941  0.78448276
  0.4         0.90909091  0.          0.35950413  0.8         0.06481481
  0.77777778  0.42105263  0.          0.92810458  0.90425532  0.30769231
  0.91549296  0.46666667  0.66415094  0.71428571  0.17142857  0.8         0.
  0.7         0.          0.38461538  0.69230769  0.77777778  0.8372093
  0.30769231  0.          0.          0.46875     0.775       0.46153846
  1.          0.34337349  0.          0.22222222  0.25        0.7173913
  0.30769231  0.71186441  0.66666667  0.75        0.33333333  0.65027322
  0.94444444  0.43137255  0.35        0.06666667  0.42857143  0.33333333
  0.40740741  0.90909091  0.6         0.04761905  0.4         0.38888889
  0.33333333  0.68627451  0.90909091] / Recall: [ 0.96330275  0.76923077  0.4502924   0.7037037   0.3902439   0.38983051
  0.42105263  0.36        0.          0.          0.80645161  0.7099768   0.
  0.45098039  0.          0.16666667  0.65517241  0.77777778  0.01219512
  0.39873418  0.78873239  0.          0.88429752  0.78571429  0.77321814
  0.82119205  0.67251462  0.66037736  0.54166667  0.          0.80645161
  0.24324324  0.34782609  0.76086957  0.53571429  0.46875     0.56923077
  0.27272727  0.49593496  0.08333333  0.38461538  0.16666667  0.62926829
  0.          0.68421053  0.4125      0.2         0.06060606  0.2037037
  0.06578947  0.06153846  0.1971831   0.82352941  0.41025641  0.          0.52
  0.33333333  0.64516129  0.77777778  0.77118644  0.18181818  0.43478261
  0.          0.62589928  0.5         0.056       0.33333333  0.33333333
  0.          0.91612903  0.91397849  0.36363636  0.79268293  0.58333333
  0.77192982  0.71428571  0.20338983  0.87017544  0.          0.36842105
  0.          0.45454545  0.34615385  0.41176471  0.85207101  0.18390805
  0.          0.          0.51724138  0.484375    0.2         0.85714286
  0.33139535  0.          0.13333333  0.5         0.66        0.16
  0.71186441  0.43478261  0.31034483  0.33333333  0.77272727  0.94444444
  0.30555556  0.2038835   0.05357143  0.375       0.05555556  0.55696203
  0.66666667  0.6         0.03703704  0.23529412  0.38888889  0.33333333
  0.49295775  0.95238095] / Accuracy: 0.555


Training combination: 50 - 15

Est: 50 / Depth: 15 / LR: 0.01 ---- Precision: [ 0.94864048  0.95238095  0.62601626  0.59375     0.34285714  0.49019608
  0.64        0.64285714  0.          0.          0.77777778  0.27158099
  0.          0.64516129  0.          0.2         0.84444444  0.77777778
  0.03846154  0.52991453  0.79710145  0.          0.90677966  0.8
  0.66793893  0.82550336  0.69871795  0.70212766  0.92857143  0.
  0.81355932  0.17682927  0.5         0.92105263  0.48275862  0.46666667
  0.31481481  0.42857143  0.6         0.30434783  0.83333333  1.          0.4924812
  0.          0.82978723  0.44615385  0.52941176  0.09174312  0.42307692
  0.25        0.14814815  0.32467532  1.          0.37162162  0.
  0.51612903  1.          0.56521739  0.8358209   0.77777778  0.4
  0.90909091  0.          0.37089202  0.8         0.08823529  0.5
  0.45714286  0.07692308  0.93377483  0.91304348  0.25        0.92647059
  0.44444444  0.67054264  0.71428571  0.15789474  0.78456592  0.          0.6
  0.          0.37209302  0.61538462  0.75        0.83529412  0.30508475
  0.          0.          0.46511628  0.71428571  0.5         1.
  0.36363636  0.          0.22222222  0.16666667  0.76744186  0.35714286
  0.70909091  0.66666667  0.72727273  0.33333333  0.64285714  0.94117647
  0.4137931   0.35384615  0.05263158  0.28571429  0.33333333  0.41414141
  0.9         0.6         0.04761905  0.34146341  0.38888889  0.33333333
  0.63461538  0.9047619 ] / Recall: [ 0.96024465  0.76923077  0.4502924   0.7037037   0.29268293  0.42372881
  0.42105263  0.36        0.          0.          0.79032258  0.64965197
  0.          0.39215686  0.          0.16666667  0.65517241  0.77777778
  0.01219512  0.39240506  0.77464789  0.          0.88429752  0.85714286
  0.75593952  0.81456954  0.6374269   0.62264151  0.54166667  0.
  0.77419355  0.19594595  0.26086957  0.76086957  0.5         0.4375
  0.52307692  0.27272727  0.48780488  0.19444444  0.38461538  0.16666667
  0.63902439  0.          0.68421053  0.3625      0.225       0.07575758
  0.2037037   0.09210526  0.06153846  0.17605634  0.82352941  0.47008547
  0.          0.64        0.33333333  0.55913978  0.77777778  0.71186441
  0.18181818  0.43478261  0.          0.56834532  0.5         0.096
  0.14285714  0.33333333  0.02272727  0.90967742  0.90322581  0.18181818
  0.76829268  0.5         0.75877193  0.71428571  0.20338983  0.85614035
  0.          0.31578947  0.          0.48484848  0.30769231  0.35294118
  0.84023669  0.20689655  0.          0.          0.45977011  0.46875
  0.16666667  0.85714286  0.37209302  0.          0.13333333  0.5         0.66
  0.2         0.66101695  0.34782609  0.27586207  0.33333333  0.75974026
  0.88888889  0.33333333  0.22330097  0.03571429  0.25        0.05555556
  0.51898734  0.6         0.6         0.03703704  0.2745098   0.38888889
  0.33333333  0.46478873  0.9047619 ] / Accuracy: 0.541


Training combination: 100 - 3

In [ ]:
gb = GradientBoostingClassifier()
param = {
    'n_estimators': [50, 100, 150], 
    'max_depth': [7, 11, 15],
    'learning_rate': [0.01]
}

clf = GridSearchCV(gb, param, cv=5, n_jobs=-1)
cv_fit = clf.fit(tfidf_vectorized_matrix_ps, data['label'])
pd.DataFrame(cv_fit.cv_results_).sort_values('mean_test_score', ascending=False)[0:5]

In [ ]:
rf = RandomForestClassifier(n_estimators=150, max_depth=None, n_jobs=-1)
rf_model = rf.fit(tfidf_vectorized_matrix_ps, data['label'])

In [ ]:
QUERY = """ 
SELECT
bm.id
,trim(nvl(bm.name,'') || ' ' || nvl(description,'')) "feature"
FROM oneflare_reports.business_master bm
WHERE bm.total_quotes_made < 3
"""

In [ ]:
data_to_predict=pd.read_sql(QUERY,redshift)

In [ ]:
from sklearn.externals import joblib
joblib.dump(rf_model, 'filename.pkl') 
#clf = joblib.load('filename.pk1')