In [66]:
from nltk.corpus import stopwords

#stopwords.words('english')

In [67]:
from sqlalchemy import create_engine
import pandas as pd
import re
import string
import nltk
pd.set_option('display.max_colwidth', 100)

In [68]:
QUERY=""" 
SELECT
trim(nvl(bm.name,'') || ' ' || nvl(description,'')) "feature"
,category_name "label"
FROM oneflare_reports.business_master bm
WHERE bm.total_quotes_made >= 3 and category_name is not null
"""

In [69]:
def make_engine():
    user = 'xxx'
    pw = 'xxx'
    db_name = 'snowplow'
    host = 'redshift.oneflare.io'
    port = 5439
    engine_string = "postgresql://%s:%s@%s:%s/%s" % (
        user, pw, host, port, db_name)
    engine = create_engine(engine_string)
    return engine

redshift = make_engine()
data=pd.read_sql(QUERY,redshift)

In [70]:
data.head()

,feature,label
0,"Abbey Road Constructions We, since 30 years have been working to provide workmanship services to...",Decking
1,A & E Accountants Pty Ltd A & E Accountants Pty Ltd is an established business providing Complet...,Accountant
2,"Walway Plastering No job too big or small.\nI have experience in painting, plastering, tiling.\n...",Plasterer
3,"Ampleamp 27 years as an electrician,running Ampleamp for last 7 years. Lots of experience in the...",Security System
4,First Class Cleaning Services 1st Class Commercial Cleaners Sydney provide superior cleaning ser...,Gardener

In [71]:
stopwords = nltk.corpus.stopwords.words('english')
wn = nltk.WordNetLemmatizer()
ps = nltk.PorterStemmer()

In [93]:
def clean_text_by_porter_stem(text):

    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if (word not in stopwords) and (word.isdigit() ==False) and (bool(re.match('^[a-zA-Z]+$',word))==True ) ]
    text = [ word for word in text if word in import_features_list]
    return text

def clean_text_by_wordnet_lemmatize(text):

    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [wn.lemmatize(word)  for word in tokens if (word not in stopwords) and (word.isdigit() ==False) and (bool(re.match('^[a-zA-Z]+$',word))==True )] 
    text = [ word for word in text if word in import_features_list]
    
    return text

In [13]:
#data.drop('feature_cleaned', axis=1, inplace=True)

In [28]:
data['feature_cleaned_ps']=data['feature'].apply(lambda x: clean_text_by_porter_stem( ('' if x is None else x).lower()))
data['feature_cleaned_wd']=data['feature'].apply(lambda x: clean_text_by_wordnet_lemmatize( ('' if x is None else x).lower()))

In [29]:
data.head()

,feature,label,feature_cleaned_ps,feature_cleaned_wd
0,"Anaxim Accounting Solutions The company is a qualified, professional accountant who deals with a...",Accountant,"[anaxim, account, solut, compani, qualifi, profession, account, deal, array, account, issu, prov...","[anaxim, accounting, solution, company, qualified, professional, accountant, deal, array, accoun..."
1,RCS Websites Let RCS Websites breath life in to your existing website!\r\nOur websites are simpl...,SEO and SEM,"[rc, websit, let, rc, websit, breath, life, exist, websit, websit, simpl, clean, profession, sur...","[rcs, website, let, rcs, website, breath, life, existing, website, website, simple, clean, profe..."
2,Intouch Carpet Cleaning Services InTouch Carpet and Pest Control is a family owned business who ...,Pest Control,"[intouch, carpet, clean, servic, intouch, carpet, pest, control, famili, own, busi, valu, old, f...","[intouch, carpet, cleaning, service, intouch, carpet, pest, control, family, owned, business, va..."
3,Shannon Thomas Carpenter Licensed Carpenter\r\n - Small Decks and Pergolas as well as re deck...,Carpenter,"[shannon, thoma, carpent, licens, carpent, small, deck, pergola, well, deck, repair, attent, det...","[shannon, thomas, carpenter, licensed, carpenter, small, deck, pergola, well, decking, repair, a..."
4,"M&M Cabinets Custom-made Cabinets for kitchen, laundries, bathroom and anywhere in your house. 3...",Builder,"[mm, cabinet, custommad, cabinet, kitchen, laundri, bathroom, anywher, hous, 3d, comput, draw, a...","[mm, cabinet, custommade, cabinet, kitchen, laundry, bathroom, anywhere, house, 3d, computer, dr..."

In [31]:
print(type(data.iloc[0]['feature_cleaned_ps']))
print(type(data.iloc[0]['feature_cleaned_wd']))

<class 'list'>
<class 'list'>

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [94]:
tfidf_vectorizer_ps = TfidfVectorizer(analyzer=clean_text_by_porter_stem)
tfidf_vectorized_matrix_ps = tfidf_vectorizer_ps.fit_transform(data['feature'] )

In [11]:
count_vectorizer_ps = CountVectorizer(analyzer=clean_text_by_porter_stem)
count_vectorized_matrix_ps = count_vectorizer_ps.fit_transform(data['feature'] )

In [95]:
tfidf_vectorized_matrix_ps.shape

(39025, 38077)

In [99]:
tfidf_vectorized_df_ps = pd.DataFrame(tfidf_vectorized_matrix_ps.toarray())

MemoryError:

In [96]:
tfidf_vectorized_df_ps.head()

NameError: name 'tfidf_vectorized_df_ps' is not defined

In [9]:
tfidf_vectorizer_wn = TfidfVectorizer(analyzer=clean_text_by_wordnet_lemmatize)
tfidf_vectorized_matrix_wn = tfidf_vectorizer_wn.fit_transform(data['feature'])

In [10]:
tfidf_vectorized_matrix_wn.shape

(38974, 56825)

In [ ]:
tfidf_vectorizer_wn = TfidfVectorizer(analyzer=clean_text_by_wordnet_lemmatize)
tfidf_vectorized_matrix_wn = tfidf_vectorizer_wn.fit_transform(data['feature'])
tfidf_vectorized_df_wn = pd.DataFrame(tfidf_vectorized_matrix_wn.toarray())

In [97]:
tfidf_vectorized_df_ps_h = tfidf_vectorized_df_ps
tfidf_vectorized_df_ps_h.columns = tfidf_vectorizer_ps.get_feature_names()
tfidf_vectorized_df_ps_h.head()

NameError: name 'tfidf_vectorized_df_ps' is not defined

In [ ]:
tfidf_vectorized_df_wn_h = tfidf_vectorized_df_wn
tfidf_vectorized_df_wn_h.columns = tfidf_vectorizer_wn.get_feature_names()
tfidf_vectorized_df_wn_h.head()

In [16]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import precision_recall_fscore_support as score
import time

In [65]:
print(dir(RandomForestClassifier))
print(RandomForestClassifier())

['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_estimator_type', '_get_param_names', '_make_estimator', '_set_oob_score', '_validate_X_predict', '_validate_estimator', '_validate_y_class_weight', 'apply', 'decision_path', 'feature_importances_', 'fit', 'get_params', 'predict', 'predict_log_proba', 'predict_proba', 'score', 'set_params']
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [66]:
print(dir(GradientBoostingClassifier))
print(GradientBoostingClassifier())

['_SUPPORTED_LOSS', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_check_initialized', '_check_params', '_clear_state', '_decision_function', '_estimator_type', '_fit_stage', '_fit_stages', '_get_param_names', '_init_decision_function', '_init_state', '_is_initialized', '_make_estimator', '_resize_state', '_staged_decision_function', '_validate_estimator', '_validate_y', 'apply', 'decision_function', 'feature_importances_', 'fit', 'get_params', 'n_features', 'predict', 'predict_log_proba', 'predict_proba', 'score', 'set_params', 'staged_decision_function', 'staged_predict', 'staged_predict_proba']
GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

## Start to evaluate models

In [100]:
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.model_selection import train_test_split

In [101]:
X_train, X_test, y_train, y_test = train_test_split(tfidf_vectorized_matrix_ps, data['label'], test_size=0.2)

In [28]:
print(X_train)
print(y_train)

  (0, 12554)	0.897560979187
  (0, 43683)	0.418577057734
  (0, 38357)	0.138482978662
  (1, 546)	0.153514794957
  (1, 25221)	0.140580537403
  (1, 27985)	0.614059179828
  (1, 30343)	0.129450761432
  (1, 31123)	0.116775518268
  (1, 10302)	0.0797108439834
  (1, 7831)	0.176736539174
  (1, 43756)	0.0797108439834
  (1, 1885)	0.0838096269878
  (1, 5411)	0.0679026764305
  (1, 31732)	0.089084966057
  (1, 38273)	0.102735537169
  (1, 44046)	0.0800556182295
  (1, 45950)	0.0960768681014
  (1, 17635)	0.240989165277
  (1, 47144)	0.0874223538907
  (1, 14034)	0.0742547705572
  (1, 41046)	0.106732115752
  (1, 32781)	0.138885720703
  (1, 39241)	0.0787243392195
  (1, 24799)	0.064152586744
  (1, 31790)	0.0704076165584
  :	:
  (31109, 4269)	0.0377460871041
  (31109, 35272)	0.0577218965356
  (31109, 24686)	0.0417189988265
  (31109, 21468)	0.0281246360286
  (31109, 3707)	0.100935388312
  (31109, 14571)	0.0423268753826
  (31109, 46080)	0.0482403344871
  (31109, 11701)	0.0361762110722
  (31109, 2750)	0.0289037009938
  (31109, 26419)	0.0322898505704
  (31109, 9435)	0.029176706815
  (31109, 20514)	0.0429523147684
  (31109, 27413)	0.0362260546839
  (31109, 29392)	0.0777149243008
  (31109, 43528)	0.0369232215741
  (31109, 15099)	0.040564659642
  (31109, 21584)	0.0289853454357
  (31109, 46899)	0.0648565924512
  (31109, 7718)	0.0563129109073
  (31109, 40154)	0.0270330351744
  (31109, 9988)	0.0295151781965
  (31109, 33974)	0.0353588278113
  (31109, 41667)	0.0354400159436
  (31109, 15343)	0.0450484575541
  (31109, 48055)	0.0226438182527
19634                  Tree Lopping
11354                       Fencing
26991                  Partitioning
13747               Carpet Cleaning
12442                    Accountant
35804              Wedding Car Hire
6660                Carpet Cleaning
15530                    Accountant
36342                       Pergola
12312                      Handyman
29114                       Glazier
5810                   Pest Control
15983                   Solar Panel
13605                    Accountant
26491                   Solar Panel
34408                    Accountant
11164               Carpet Cleaning
29109                   Lawn Mowing
24815                       Cleaner
30543              T-Shirt Printing
14093                       Pergola
1060                    Pet Sitting
21871                  Conveyancing
10337                 Makeup Artist
38780                     Celebrant
21543                    Accountant
14454                   Electrician
19832                  Videographer
23916                       Massage
20480                  Photographer
                    ...
11827                       Builder
6296                   Photographer
29715               Security System
29266                       Roofing
5378                       Gardener
4781                        Ceiling
29660          Wedding Hair Stylist
7469                Interior Design
25921    Prepurchase Car Inspection
5321                Carpet Cleaning
23824                       Painter
2980                      Carpenter
9817                        Decking
36115                       Painter
14067                    Accountant
8844                Computer Repair
25465                       Cleaner
2822                        Plumber
30377                     Wallpaper
12136                      Handyman
1541                     Accountant
2719                        Fencing
9912                     TV Repairs
30708                  Partitioning
31582               Computer Repair
12759                    Accountant
914                       Plasterer
22930               Security System
23594              Personal Trainer
38363                 Makeup Artist
Name: label, Length: 31110, dtype: object

In [31]:
print(X_test)

  (0, 10272)	0.248899690119
  (0, 44883)	0.248899690119
  (0, 3670)	0.2658434338
  (0, 23632)	0.5316868676
  (0, 23979)	0.210811382518
  (0, 32119)	0.192613791953
  (0, 11749)	0.22008787539
  (0, 25430)	0.222044491763
  (0, 19132)	0.130824386178
  (0, 26435)	0.119020203111
  (0, 14463)	0.18765297304
  (0, 29282)	0.11753117282
  (0, 35354)	0.163801977225
  (0, 31704)	0.106775275246
  (0, 38178)	0.142796360154
  (0, 39919)	0.138101859336
  (0, 5235)	0.220350590333
  (0, 12337)	0.0936864965212
  (0, 15249)	0.12099438661
  (0, 45669)	0.102670656056
  (0, 25754)	0.0851553043744
  (0, 14683)	0.0885781407425
  (0, 11701)	0.0911815794986
  (0, 44489)	0.112900334261
  (0, 21584)	0.073057114076
  :	:
  (7776, 14571)	0.0995837462847
  (7776, 17076)	0.0685402501629
  (7776, 37387)	0.105277003827
  (7776, 30447)	0.0601834483687
  (7776, 40154)	0.0636014563273
  (7776, 26337)	0.284373096009
  (7776, 44750)	0.0794525675833
  (7776, 33974)	0.0831898056697
  (7776, 41667)	0.0833808194948
  (7776, 38357)	0.107539066383
  (7777, 23167)	0.595892640529
  (7777, 40565)	0.212615355724
  (7777, 19955)	0.228554164934
  (7777, 35959)	0.183573275798
  (7777, 39564)	0.312208822892
  (7777, 5709)	0.200086893321
  (7777, 46899)	0.126870418158
  (7777, 40154)	0.158643509335
  (7777, 26337)	0.354661264981
  (7777, 23006)	0.154929327269
  (7777, 9988)	0.173209978736
  (7777, 35029)	0.229003851895
  (7777, 14253)	0.210838003378
  (7777, 34271)	0.120690015385
  (7777, 2125)	0.209156935879

In [102]:
def train_RF(n_est, depth):
    rf = RandomForestClassifier(n_estimators=n_est, max_depth=depth, n_jobs=-1, verbose=10)
    rf_model = rf.fit(X_train, y_train)
    y_pred = rf_model.predict(X_test)
    precision, recall, fscore, support = score(y_test, y_pred)
    print('Est: {} / Depth: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
        n_est, depth, precision, recall,
        round((y_pred==y_test).sum() / len(y_pred), 3)))

In [14]:
from ipywidgets import FloatProgress
from IPython.display import display

In [20]:
max_count = 12
count = 0
progressBar = FloatProgress(min=0, max=max_count)
display(progressBar)

for n_est in [10, 50, 100]:
    for depth in [10, 20, 30, None]:
        print("\n\nTraining combination: n_est:{n_est} - depth:{max_depth}".format(n_est=str(n_est),depth=str(depth)))
        progressBar.value+=1
        count += 1
        train_RF(n_est, depth)

A Jupyter Widget

Training combination: n_est:10 - max_depth:10

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 10 ---- Precision: [ 0.48833034  0.          0.625       0.          0.          0.          0.64
  0.          0.          0.          0.          0.13306908  0.
  0.73333333  0.          0.          0.          0.          0.
  0.61538462  0.38461538  0.          0.76271186  0.          0.14427481
  0.59447005  0.7         0.          0.          0.          0.625       0.
  0.          0.          1.          0.33333333  0.38271605  0.
  0.68627451  0.          0.          0.          0.53218884  0.
  0.74285714  0.          0.          0.          0.          0.          0.
  0.32142857  0.95454545  0.5         0.          0.          0.
  0.26470588  0.5         0.61111111  0.          0.          0.
  0.28508772  0.          0.          0.          0.          0.
  0.66486486  0.73387097  0.          0.77272727  0.          0.41734417
  0.          0.          0.59183673  0.          0.          0.          0.
  0.          0.          0.55844156  0.          0.          0.          1.
  0.          0.          0.          0.30612245  0.          0.          0.
  0.          0.          1.          0.          0.          0.          0.6875
  0.          0.          0.16666667  0.          0.          0.          0.
  0.          0.          0.          1.          0.          0.          0.
  0.        ] / Recall: [ 0.86624204  0.          0.34810127  0.          0.          0.
  0.55172414  0.          0.          0.          0.          0.55294118
  0.          0.21568627  0.          0.          0.          0.          0.
  0.04938272  0.06756757  0.          0.82568807  0.          0.73684211
  0.83225806  0.14736842  0.          0.          0.          0.12820513
  0.          0.          0.          0.03030303  0.03125     0.19018405
  0.          0.30973451  0.          0.          0.          0.50406504
  0.          0.41935484  0.          0.          0.          0.          0.
  0.          0.07258065  0.84        0.01666667  0.          0.          0.
  0.10714286  0.04054054  0.53921569  0.          0.          0.
  0.45454545  0.          0.          0.          0.          0.
  0.83108108  0.86666667  0.          0.77272727  0.          0.63900415
  0.          0.          0.77910448  0.          0.          0.          0.
  0.          0.          0.61428571  0.          0.          0.
  0.01333333  0.          0.          0.          0.09868421  0.          0.
  0.          0.          0.          0.03636364  0.          0.          0.
  0.14379085  0.          0.          0.03448276  0.          0.          0.
  0.          0.          0.          0.          0.02040816  0.          0.
  0.          0.        ] / Accuracy: 0.312


Training combination: n_est:10 - max_depth:20

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 20 ---- Precision: [ 0.78005865  0.75        0.5703125   0.5         0.5         0.3         0.
  0.5         0.          1.          0.7037037   0.23684211  0.          0.
  0.          0.          0.61111111  0.          0.          0.46774194
  0.89130435  0.          0.81395349  0.          0.21251194  0.77018634
  0.53846154  0.75925926  0.          0.33333333  0.82142857  0.09090909
  0.33333333  0.72727273  0.5         0.          0.30357143  0.          0.
  0.375       0.75        0.          0.4804878   0.          0.61904762
  0.44285714  0.          0.17647059  0.          0.11111111  0.
  0.33333333  0.          0.23076923  0.          0.27272727  0.
  0.41304348  0.76315789  0.44444444  0.          0.66666667  0.
  0.32926829  0.66666667  0.          0.          0.38461538  0.
  0.66176471  0.69565217  0.          0.66666667  0.47368421  0.5530303   0.
  0.2         0.67352941  0.          0.          0.          0.66666667
  0.          0.          0.61643836  0.1         0.          0.
  0.48611111  0.78947368  0.          0.          0.35714286  0.          0.
  0.          0.41666667  0.          0.5         0.          0.16666667
  0.          0.41830065  0.          0.          0.4         0.125       0.
  0.          0.31746032  0.          0.          0.5         0.5         0.
  0.          0.33333333  0.33333333] / Recall: [ 0.84713376  0.68181818  0.46202532  0.04        0.08928571  0.05357143
  0.          0.08        0.          0.66666667  0.69090909  0.72        0.
  0.          0.          0.          0.16666667  0.          0.
  0.17901235  0.55405405  0.          0.96330275  0.          0.86744639
  0.8         0.29473684  0.78846154  0.          0.14285714  0.88461538
  0.01086957  0.07142857  0.27586207  0.06060606  0.          0.62576687
  0.          0.          0.06976744  0.27272727  0.          0.80081301
  0.          0.41935484  0.36046512  0.          0.02290076  0.
  0.01492537  0.          0.19354839  0.          0.075       0.
  0.13043478  0.          0.22619048  0.39189189  0.39215686  0.
  0.17391304  0.          0.37762238  0.06451613  0.          0.
  0.16949153  0.          0.91216216  0.3047619   0.          0.39393939
  0.29032258  0.90871369  0.          0.01428571  0.68358209  0.          0.
  0.          0.13793103  0.          0.          0.64285714  0.01219512
  0.          0.          0.46666667  0.25        0.          0.
  0.16447368  0.          0.          0.          0.11627907  0.
  0.07272727  0.          0.04761905  0.          0.41830065  0.          0.
  0.04597701  0.01492537  0.          0.          0.21978022  0.          0.
  0.03225806  0.06122449  0.          0.          0.01470588  0.0625    ] / Accuracy: 0.402


Training combination: n_est:10 - max_depth:30

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: 30 ---- Precision: [ 0.67483296  0.91666667  0.50381679  0.5         0.56756757  0.48
  0.64285714  0.6         0.          0.          0.63793103  0.18535735
  0.33333333  0.57142857  0.          0.          0.62222222  0.5         0.
  0.40350877  0.72463768  0.          0.78676471  0.83333333  0.42813456
  0.76300578  0.60869565  0.66666667  0.75        0.          0.72727273
  0.14705882  0.          0.61538462  0.36363636  0.39130435  0.33802817
  0.          0.65333333  0.23076923  0.          0.          0.51289398
  0.          0.76923077  0.40740741  0.          0.14285714  0.14285714
  0.11111111  0.          0.18421053  0.94444444  0.23076923  0.
  0.48484848  1.          0.45985401  0.75862069  0.46153846  0.
  0.63636364  0.          0.26966292  0.76923077  0.07692308  0.          0.2
  0.          0.66666667  0.75675676  0.25        0.76923077  0.28571429
  0.5494186   1.          0.14285714  0.63733906  0.          0.          0.
  0.16666667  0.5         0.6         0.61764706  0.28        0.          0.
  0.41176471  0.52777778  0.11111111  0.          0.376       0.          0.
  0.          0.90909091  0.          0.66666667  0.          0.          0.
  0.58558559  0.53846154  0.16666667  0.25925926  0.          0.          0.
  0.4556962   0.84615385  0.          0.14285714  0.625       0.33333333
  0.          0.42857143  0.5       ] / Recall: [ 0.96496815  0.5         0.41772152  0.24        0.375       0.21428571
  0.31034483  0.12        0.          0.          0.67272727  0.75058824
  0.04545455  0.07843137  0.          0.          0.42424242  0.2         0.
  0.14197531  0.67567568  0.          0.98165138  0.41666667  0.81871345
  0.8516129   0.58947368  0.69230769  0.36        0.          0.30769231
  0.02717391  0.          0.27586207  0.36363636  0.28125     0.29447853
  0.          0.43362832  0.06976744  0.          0.          0.72764228
  0.          0.48387097  0.38372093  0.          0.03816794  0.03846154
  0.01492537  0.          0.05645161  0.68        0.075       0.
  0.69565217  0.22222222  0.75        0.89189189  0.58823529  0.
  0.30434783  0.          0.16783217  0.32258065  0.02272727  0.
  0.03389831  0.          0.87837838  0.8         0.05555556  0.75757576
  0.06451613  0.78423237  0.4         0.02857143  0.88656716  0.          0.
  0.          0.10344828  0.05263158  0.13636364  0.9         0.08536585
  0.          0.          0.09333333  0.31666667  0.03571429  0.
  0.30921053  0.          0.          0.          0.23255814  0.
  0.47272727  0.          0.          0.          0.4248366   0.5
  0.04651163  0.08045977  0.          0.          0.          0.3956044
  0.37931034  0.          0.03225806  0.10204082  0.08333333  0.
  0.13235294  0.25      ] / Accuracy: 0.458


Training combination: n_est:10 - max_depth:None

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 10 / Depth: None ---- Precision: [ 0.74820144  0.59259259  0.37668161  0.45833333  0.40350877  0.30508475
  0.58064516  0.5         0.          0.          0.30075188  0.3559322
  0.4         0.425       0.          0.          0.57534247  0.5
  0.0862069   0.41958042  0.75280899  0.          0.74305556  0.85714286
  0.58187135  0.74594595  0.58369099  0.60784314  0.90909091  0.
  0.83950617  0.125       0.55555556  0.7037037   0.33333333  0.5
  0.39613527  0.33333333  0.53773585  0.39285714  0.42857143  0.
  0.54754098  0.          0.6744186   0.33898305  0.18181818  0.13461538
  0.2         0.11111111  0.11428571  0.24444444  1.          0.34234234
  0.          0.57894737  1.          0.48818898  0.77108434  0.62686567
  0.          0.9         0.          0.30808081  1.          0.08955224
  0.4         0.5         0.          0.80898876  0.84745763  0.25
  0.79487179  0.33333333  0.68493151  0.5         0.23529412  0.79100529
  0.          0.66666667  0.          0.28571429  0.77777778  1.
  0.74431818  0.21428571  0.          0.          0.43421053  0.88
  0.33333333  1.          0.37410072  0.          0.125       1.
  0.68571429  1.          0.73809524  0.75        0.375       0.
  0.63513514  0.9         0.29545455  0.24390244  0.          0.57142857
  0.66666667  0.47058824  0.93333333  0.5         0.1         0.35294118
  0.6         0.66666667  0.56756757  0.8       ] / Recall: [ 0.99363057  0.72727273  0.53164557  0.44        0.41071429  0.32142857
  0.62068966  0.28        0.          0.          0.72727273  0.64235294
  0.09090909  0.33333333  0.          0.          0.63636364  0.4
  0.07352941  0.37037037  0.90540541  0.          0.98165138  0.5
  0.77582846  0.89032258  0.71578947  0.59615385  0.4         0.
  0.87179487  0.08695652  0.35714286  0.65517241  0.3030303   0.25
  0.50306748  0.09090909  0.50442478  0.25581395  0.27272727  0.
  0.67886179  0.          0.46774194  0.46511628  0.13333333  0.05343511
  0.05769231  0.05970149  0.07142857  0.17741935  0.72        0.31666667
  0.          0.47826087  0.44444444  0.73809524  0.86486486  0.82352941
  0.          0.39130435  0.          0.42657343  0.35483871  0.06818182
  0.125       0.10169492  0.          0.97297297  0.95238095  0.05555556
  0.93939394  0.19354839  0.82987552  0.2         0.05714286  0.89253731
  0.          0.14285714  0.          0.20689655  0.36842105  0.27272727
  0.93571429  0.1097561   0.          0.          0.44        0.36666667
  0.10714286  0.41666667  0.34210526  0.          0.0625      0.5
  0.55813953  0.11111111  0.56363636  0.11111111  0.14285714  0.
  0.61437908  0.64285714  0.30232558  0.11494253  0.          0.33333333
  0.10526316  0.35164835  0.48275862  0.11111111  0.03225806  0.12244898
  0.125       0.2         0.30882353  0.5       ] / Accuracy: 0.531


Training combination: n_est:50 - max_depth:10

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 10 ---- Precision: [ 0.74378109  1.          0.70149254  0.          0.85714286  0.          0.
  0.          0.          0.          1.          0.18921833  0.          1.
  0.          0.          0.          0.          0.          0.33333333
  0.89285714  0.          0.8677686   1.          0.15201238  0.8411215
  0.77272727  0.          0.          0.          0.8125      0.          0.
  1.          0.          0.          0.66666667  0.          0.84615385
  0.          0.          0.          0.53688525  0.          0.
  0.54545455  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.51937984
  0.82258065  0.65306122  0.          0.          0.          0.40909091
  0.          0.          0.          0.          0.          0.80246914
  0.92537313  0.          0.94871795  0.          0.61748634  0.          0.
  0.63915094  0.          0.          0.          0.          0.          0.
  0.824       0.          0.          0.          0.          0.          0.
  0.          1.          0.          0.          0.          0.          0.
  0.78571429  0.          0.          0.          0.66071429  0.          0.125
  0.          0.          0.          0.          0.5106383   0.          0.
  0.          0.          0.          0.          0.          1.        ] / Recall: [ 0.9522293   0.5         0.29746835  0.          0.10714286  0.          0.
  0.          0.          0.          0.01818182  0.82588235  0.
  0.01960784  0.          0.          0.          0.          0.
  0.00617284  0.67567568  0.          0.96330275  0.08333333  0.95711501
  0.58064516  0.17894737  0.          0.          0.          0.16666667
  0.          0.          0.10344828  0.          0.          0.01226994
  0.          0.09734513  0.          0.          0.          0.53252033
  0.          0.          0.06976744  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.79761905  0.68918919  0.31372549  0.          0.          0.
  0.06293706  0.          0.          0.          0.          0.
  0.87837838  0.59047619  0.          0.56060606  0.          0.93775934
  0.          0.          0.80895522  0.          0.          0.          0.
  0.          0.          0.73571429  0.          0.          0.          0.
  0.          0.          0.          0.09868421  0.          0.          0.
  0.          0.          0.2         0.          0.          0.
  0.24183007  0.          0.02325581  0.          0.          0.          0.
  0.26373626  0.          0.          0.          0.          0.          0.
  0.          0.0625    ] / Accuracy: 0.351


Training combination: n_est:50 - max_depth:20

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 20 ---- Precision: [ 0.73396675  1.          0.68292683  0.66666667  0.70588235  0.          1.
  0.          0.          0.          0.56818182  0.21375     0.          0.75
  0.          0.          0.86666667  0.          0.          0.82857143
  0.87878788  0.          0.82170543  1.          0.22611618  0.80368098
  0.74193548  0.85185185  0.          0.          0.88888889  0.66666667
  0.          0.55555556  0.42857143  0.          0.34090909  0.
  0.80952381  0.          0.          0.          0.53333333  0.
  0.89655172  0.42553191  0.          0.625       0.          0.          0.
  0.66666667  0.          0.45454545  0.          0.5         0.
  0.50331126  0.84507042  0.67741935  0.          0.85714286  0.
  0.34042553  1.          0.          0.          0.          0.
  0.77297297  0.83783784  0.          0.78205128  0.          0.63764045
  0.          0.          0.69162996  0.          0.          0.          1.
  0.          0.          0.82394366  0.          0.          0.          1.
  0.9375      0.          0.          0.49206349  0.          0.          0.
  0.82608696  0.          0.71875     0.          0.          0.
  0.68644068  1.          0.27272727  1.          0.          1.          0.
  0.51898734  1.          0.          0.          0.          0.          0.
  0.          0.        ] / Recall: [ 0.98407643  0.54545455  0.35443038  0.32        0.21428571  0.
  0.06896552  0.          0.          0.          0.45454545  0.80470588
  0.          0.05882353  0.          0.          0.1969697   0.          0.
  0.17901235  0.78378378  0.          0.97247706  0.33333333  0.91812865
  0.84516129  0.60526316  0.44230769  0.          0.          0.82051282
  0.01086957  0.          0.34482759  0.09090909  0.          0.18404908
  0.          0.30088496  0.          0.          0.          0.74796748
  0.          0.41935484  0.23255814  0.          0.03816794  0.          0.
  0.          0.01612903  0.          0.125       0.          0.60869565
  0.          0.9047619   0.81081081  0.61764706  0.          0.26086957
  0.          0.33566434  0.19354839  0.          0.          0.          0.
  0.96621622  0.88571429  0.          0.92424242  0.          0.94190871
  0.          0.          0.93731343  0.          0.          0.
  0.03448276  0.          0.          0.83571429  0.          0.          0.
  0.04        0.25        0.          0.          0.20394737  0.          0.
  0.          0.44186047  0.          0.83636364  0.          0.          0.
  0.52941176  0.07142857  0.06976744  0.01149425  0.          0.25        0.
  0.45054945  0.10344828  0.          0.          0.          0.          0.
  0.          0.        ] / Accuracy: 0.461


Training combination: n_est:50 - max_depth:30

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: 30 ---- Precision: [ 0.76923077  1.          0.67391304  0.84615385  0.77272727  0.625
  0.85714286  1.          0.          0.          0.71875     0.25433962
  0.          0.76923077  0.          0.          0.97368421  0.          0.
  0.75862069  0.85294118  0.          0.79411765  0.8         0.33834049
  0.77595628  0.66857143  0.80487805  1.          0.          0.89333333
  0.27272727  0.5         0.76        0.5         0.6875      0.34916201
  0.          0.78947368  0.          0.          0.          0.51948052
  0.          0.79545455  0.47        0.          0.          0.          0.
  0.          0.42424242  0.          0.47916667  0.          0.57142857
  0.          0.48993289  0.80246914  0.61744966  0.          1.          0.
  0.30601093  1.          0.          0.          1.          0.
  0.80555556  0.8877551   0.          0.65625     0.41666667  0.62087912
  0.          0.          0.72286374  0.          0.          0.          0.5
  1.          1.          0.73033708  0.36842105  0.          0.
  0.51851852  0.94736842  0.          0.          0.45833333  0.          0.
  0.          0.73333333  0.          0.74193548  0.          0.6         0.
  0.66197183  0.91666667  0.21052632  0.5         0.          0.          0.
  0.52702703  1.          0.          0.          0.5         0.          0.
  0.66666667  1.        ] / Recall: [ 0.98726115  0.45454545  0.39240506  0.44        0.30357143  0.08928571
  0.20689655  0.12        0.          0.          0.83636364  0.79294118
  0.          0.19607843  0.          0.          0.56060606  0.          0.
  0.27160494  0.78378378  0.          0.99082569  0.33333333  0.92202729
  0.91612903  0.61578947  0.63461538  0.4         0.          0.85897436
  0.01630435  0.07142857  0.65517241  0.21212121  0.34375     0.76687117
  0.          0.39823009  0.          0.          0.          0.81300813
  0.          0.56451613  0.54651163  0.          0.          0.          0.
  0.          0.11290323  0.          0.19166667  0.          0.52173913
  0.          0.86904762  0.87837838  0.90196078  0.          0.04347826
  0.          0.39160839  0.29032258  0.          0.          0.01694915
  0.          0.97972973  0.82857143  0.          0.95454545  0.16129032
  0.93775934  0.          0.          0.93432836  0.          0.          0.
  0.13793103  0.05263158  0.09090909  0.92857143  0.08536585  0.          0.
  0.37333333  0.3         0.          0.          0.28947368  0.          0.
  0.          0.51162791  0.          0.83636364  0.          0.14285714
  0.          0.61437908  0.78571429  0.09302326  0.01149425  0.          0.
  0.          0.42857143  0.51724138  0.          0.          0.04081633
  0.          0.          0.08823529  0.3125    ] / Accuracy: 0.523


Training combination: n_est:50 - max_depth:None

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 50 / Depth: None ---- Precision: [ 0.89111748  0.88888889  0.52702703  0.69565217  0.58974359  0.51923077
  0.66666667  0.77777778  0.          0.          0.61842105  0.39578164
  0.          0.58536585  0.          0.          0.82539683  0.75        0.05
  0.625       0.6         0.          0.78832117  0.7         0.62011173
  0.77837838  0.625       0.78723404  1.          0.          0.81111111
  0.23595506  0.5         0.82142857  0.42307692  0.46428571  0.37795276
  0.          0.62745098  0.42857143  0.5         0.          0.55681818
  0.          0.74        0.51456311  0.          0.14583333  0.66666667
  0.125       0.          0.30851064  0.95        0.37007874  0.
  0.46153846  1.          0.51282051  0.83333333  0.67132867  1.          1.
  0.          0.35611511  0.94117647  0.09756098  0.5         0.61111111
  0.          0.875       0.86956522  0.          0.8         0.35897436
  0.70322581  1.          0.38709677  0.78282828  0.          0.5         0.
  0.54545455  0.81818182  0.875       0.75690608  0.44444444  0.          0.
  0.45631068  0.86206897  0.33333333  1.          0.36024845  0.          0.
  0.          0.76086957  0.66666667  0.76271186  0.57142857  0.6         0.
  0.62427746  1.          0.29545455  0.38095238  0.5         0.66666667
  0.33333333  0.49090909  1.          0.          0.25        0.25        1.
  1.          0.66666667  0.86666667] / Recall: [ 0.99044586  0.72727273  0.49367089  0.64        0.41071429  0.48214286
  0.4137931   0.28        0.          0.          0.85454545  0.75058824
  0.          0.47058824  0.          0.          0.78787879  0.6
  0.01470588  0.37037037  0.93243243  0.          0.99082569  0.58333333
  0.86549708  0.92903226  0.71052632  0.71153846  0.52        0.
  0.93589744  0.11413043  0.28571429  0.79310345  0.33333333  0.40625
  0.58895706  0.          0.56637168  0.41860465  0.18181818  0.
  0.79674797  0.          0.59677419  0.61627907  0.          0.05343511
  0.11538462  0.01492537  0.          0.23387097  0.76        0.39166667
  0.          0.52173913  0.44444444  0.95238095  0.87837838  0.94117647
  0.10526316  0.52173913  0.          0.69230769  0.51612903  0.04545455
  0.0625      0.18644068  0.          0.99324324  0.95238095  0.
  0.96969697  0.4516129   0.90456432  0.2         0.17142857  0.92537313
  0.          0.14285714  0.          0.4137931   0.47368421  0.31818182
  0.97857143  0.24390244  0.          0.          0.62666667  0.41666667
  0.03571429  0.08333333  0.38157895  0.          0.          0.
  0.81395349  0.11111111  0.81818182  0.14814815  0.28571429  0.
  0.70588235  0.92857143  0.30232558  0.09195402  0.01492537  0.33333333
  0.05263158  0.59340659  0.75862069  0.          0.03225806  0.04081633
  0.04166667  0.1         0.32352941  0.8125    ] / Accuracy: 0.593


Training combination: n_est:100 - max_depth:10

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: 10 ---- Precision: [ 0.67777778  1.          0.80645161  0.          0.          0.          0.
  0.          0.          0.          0.          0.16913414  0.          0.
  0.          0.          0.          0.          0.          1.
  0.90566038  0.          0.9009009   0.          0.18794326  0.82142857
  0.76258993  1.          0.          0.          0.95238095  0.          0.
  0.5         0.          0.          0.55555556  0.          0.82758621
  0.          0.          0.          0.46904762  0.          0.9         0.8
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.43333333  0.84313725
  0.65546218  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.92424242  0.87912088  0.
  0.93877551  0.          0.60052219  0.          0.          0.65979381
  0.          0.          0.          0.          0.          0.
  0.83458647  0.          0.          0.          0.          0.          0.
  0.          0.62962963  0.          0.          0.          0.66666667
  0.          0.7037037   0.          0.          0.          0.77777778
  0.          0.          0.          0.          0.          0.
  0.58333333  0.          0.          0.          0.          0.          0.
  0.          0.        ] / Recall: [ 0.97133758  0.36363636  0.3164557   0.          0.          0.          0.
  0.          0.          0.          0.          0.88705882  0.          0.
  0.          0.          0.          0.          0.          0.00617284
  0.64864865  0.          0.91743119  0.          0.92982456  0.59354839
  0.55789474  0.03846154  0.          0.          0.51282051  0.          0.
  0.03448276  0.          0.          0.03067485  0.          0.42477876
  0.          0.          0.          0.80081301  0.          0.14516129
  0.04651163  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.30952381
  0.58108108  0.76470588  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.82432432  0.76190476
  0.          0.6969697   0.          0.95435685  0.          0.          0.7641791
  0.          0.          0.          0.          0.          0.
  0.79285714  0.          0.          0.          0.          0.          0.
  0.          0.11184211  0.          0.          0.          0.13953488
  0.          0.34545455  0.          0.          0.          0.1372549   0.
  0.          0.          0.          0.          0.          0.23076923
  0.          0.          0.          0.          0.          0.          0.
  0.        ] / Accuracy: 0.378


Training combination: n_est:100 - max_depth:20

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: 20 ---- Precision: [ 0.74100719  0.9375      0.69230769  1.          0.75        0.          0.
  0.          0.          0.          0.73809524  0.22864483  0.          1.
  0.          0.          0.83333333  0.          0.          0.65
  0.91935484  0.          0.8372093   0.          0.23338185  0.79411765
  0.75838926  0.8         0.          0.          0.8375      0.          0.
  0.80952381  0.6         1.          0.32773109  0.          0.77027027
  0.          0.          0.          0.49343832  0.          0.83333333
  0.63157895  0.          0.          0.          0.          0.
  0.54545455  0.          0.52173913  0.          0.5         0.          0.5034965
  0.86666667  0.63432836  0.          0.75        0.          0.32291667
  0.          0.          0.          0.          0.          0.88125
  0.92134831  0.          0.79746835  1.          0.58461538  0.          0.
  0.69026549  0.          0.          0.          0.          0.          0.
  0.77300613  0.          0.          0.          0.66666667  1.          0.
  0.          0.48484848  0.          0.          0.          0.76315789
  0.          0.82978723  0.          1.          0.          0.68965517
  0.          0.1         1.          0.          0.          0.
  0.62068966  1.          0.          0.          0.          0.          0.
  0.5         1.        ] / Recall: [ 0.98407643  0.68181818  0.39873418  0.08        0.26785714  0.          0.
  0.          0.          0.          0.56363636  0.83764706  0.
  0.09803922  0.          0.          0.07575758  0.          0.
  0.08024691  0.77027027  0.          0.99082569  0.          0.93762183
  0.87096774  0.59473684  0.69230769  0.          0.          0.85897436
  0.          0.          0.5862069   0.09090909  0.0625      0.2392638   0.
  0.50442478  0.          0.          0.          0.76422764  0.
  0.56451613  0.41860465  0.          0.          0.          0.          0.
  0.0483871   0.          0.1         0.          0.26086957  0.
  0.85714286  0.87837838  0.83333333  0.          0.13043478  0.
  0.21678322  0.          0.          0.          0.          0.          0.9527027
  0.78095238  0.          0.95454545  0.03225806  0.94605809  0.          0.
  0.93134328  0.          0.          0.          0.          0.          0.
  0.9         0.          0.          0.          0.08        0.26666667
  0.          0.          0.21052632  0.          0.          0.          0.6744186
  0.          0.70909091  0.          0.04761905  0.          0.52287582
  0.          0.02325581  0.01149425  0.          0.          0.          0.3956044
  0.24137931  0.          0.          0.          0.          0.
  0.01470588  0.0625    ] / Accuracy: 0.472


Training combination: n_est:100 - max_depth:30

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: 30 ---- Precision: [ 0.81315789  0.86666667  0.58333333  0.75        0.60526316  0.71428571
  0.          0.          0.          0.          0.7         0.27734375
  0.          0.91666667  0.          0.          0.94444444  0.          0.
  0.76470588  0.81578947  0.          0.81203008  1.          0.3423161
  0.78285714  0.66483516  0.875       1.          0.          0.85526316
  0.          0.          0.73333333  0.42857143  0.33333333  0.37223975
  0.          0.78205128  0.5         0.          0.          0.51378446
  0.          0.83333333  0.50666667  0.          0.          0.          0.
  0.          0.5         0.91666667  0.39344262  0.          0.57142857
  0.          0.47945205  0.8         0.64748201  0.          1.          0.
  0.32996633  1.          0.          0.          0.          0.
  0.81818182  0.87735849  0.          0.76190476  0.53333333  0.61621622
  0.          0.          0.74231678  0.          0.          0.          0.4
  0.          0.          0.70967742  0.6         0.          0.
  0.46774194  1.          0.          0.          0.4625      0.          0.
  0.          0.75        0.          0.74603175  0.          0.6         0.
  0.60248447  1.          0.30769231  1.          0.          1.          0.
  0.50574713  1.          0.          0.          0.          0.          0.
  0.66666667  1.        ] / Recall: [ 0.98407643  0.59090909  0.48734177  0.24        0.41071429  0.17857143
  0.          0.          0.          0.          0.50909091  0.83529412
  0.          0.21568627  0.          0.          0.51515152  0.          0.
  0.16049383  0.83783784  0.          0.99082569  0.41666667  0.91617934
  0.88387097  0.63684211  0.67307692  0.44        0.          0.83333333
  0.          0.          0.75862069  0.27272727  0.03125     0.72392638
  0.          0.53982301  0.18604651  0.          0.          0.83333333
  0.          0.56451613  0.44186047  0.          0.          0.          0.
  0.          0.12096774  0.44        0.2         0.          0.34782609
  0.          0.83333333  0.86486486  0.88235294  0.          0.08695652
  0.          0.68531469  0.16129032  0.          0.          0.          0.
  0.97297297  0.88571429  0.          0.96969697  0.25806452  0.94605809
  0.          0.          0.93731343  0.          0.          0.
  0.13793103  0.          0.          0.94285714  0.03658537  0.          0.
  0.38666667  0.33333333  0.          0.          0.24342105  0.          0.
  0.          0.55813953  0.          0.85454545  0.          0.14285714
  0.          0.63398693  0.21428571  0.18604651  0.01149425  0.
  0.08333333  0.          0.48351648  0.62068966  0.          0.          0.
  0.          0.          0.02941176  0.6875    ] / Accuracy: 0.53


Training combination: n_est:100 - max_depth:None

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 100 / Depth: None ---- Precision: [ 0.90144928  0.84210526  0.53191489  0.7037037   0.55555556  0.57692308
  0.72727273  0.83333333  0.          0.          0.64383562  0.4         0.
  0.60869565  0.          0.          0.81967213  1.          0.06666667
  0.68539326  0.82142857  0.          0.77142857  0.875       0.60213618
  0.78494624  0.63768116  0.79545455  1.          0.          0.82954545
  0.18571429  0.4         0.74193548  0.5         0.51724138  0.37412587
  1.          0.625       0.44444444  0.5         0.          0.54061625
  0.          0.77083333  0.54081633  0.4         0.10416667  0.7         0.
  0.          0.37179487  0.95454545  0.37815126  0.          0.5         1.
  0.50980392  0.84615385  0.68055556  1.          0.92857143  0.          0.33
  0.9047619   0.14285714  0.          0.5         0.          0.87058824
  0.88695652  1.          0.78571429  0.37931034  0.69470405  1.
  0.36111111  0.78030303  0.          0.33333333  0.          0.45833333
  0.83333333  0.72727273  0.7816092   0.39130435  0.          0.
  0.48039216  0.83333333  0.          1.          0.4379562   0.          0.
  0.          0.75        0.5         0.72131148  0.8         0.42857143
  0.          0.62643678  0.92857143  0.30232558  0.36363636  0.          0.25
  0.75        0.47058824  1.          1.          0.5         0.45454545
  1.          1.          0.75862069  0.85714286] / Recall: [ 0.99044586  0.72727273  0.47468354  0.76        0.35714286  0.53571429
  0.55172414  0.4         0.          0.          0.85454545  0.78117647
  0.          0.54901961  0.          0.          0.75757576  0.4
  0.01470588  0.37654321  0.93243243  0.          0.99082569  0.58333333
  0.8791423   0.94193548  0.69473684  0.67307692  0.52        0.
  0.93589744  0.07065217  0.14285714  0.79310345  0.42424242  0.46875
  0.65644172  0.09090909  0.57522124  0.46511628  0.09090909  0.
  0.78455285  0.          0.59677419  0.61627907  0.13333333  0.03816794
  0.13461538  0.          0.          0.23387097  0.84        0.375       0.
  0.65217391  0.55555556  0.92857143  0.89189189  0.96078431  0.05263158
  0.56521739  0.          0.69230769  0.61290323  0.07954545  0.
  0.08474576  0.          1.          0.97142857  0.05555556  1.
  0.35483871  0.9253112   0.6         0.18571429  0.92238806  0.
  0.07142857  0.          0.37931034  0.52631579  0.36363636  0.97142857
  0.2195122   0.          0.          0.65333333  0.41666667  0.
  0.16666667  0.39473684  0.          0.          0.          0.8372093
  0.11111111  0.8         0.14814815  0.14285714  0.          0.7124183
  0.92857143  0.30232558  0.04597701  0.          0.08333333  0.15789474
  0.61538462  0.79310345  0.11111111  0.03225806  0.10204082  0.04166667
  0.1         0.32352941  0.75      ] / Accuracy: 0.599

In [31]:
train_RF(900, None) # 0.613 accuracy if i use wordnet lemamtizing

building tree 1 of 900
building tree 4 of 900
building tree 3 of 900
building tree 2 of 900
building tree 5 of 900
building tree 6 of 900
building tree 7 of 900
building tree 8 of 900

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   11.2s

building tree 9 of 900
building tree 10 of 900
building tree 11 of 900
building tree 12 of 900
building tree 13 of 900
building tree 14 of 900
building tree 15 of 900
building tree 16 of 900

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   17.6s

building tree 17 of 900
building tree 18 of 900
building tree 19 of 900
building tree 20 of 900
building tree 21 of 900

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   29.0s

building tree 22 of 900
building tree 23 of 900
building tree 24 of 900
building tree 25 of 900
building tree 26 of 900
building tree 27 of 900
building tree 28 of 900

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   35.3s

building tree 29 of 900
building tree 30 of 900
building tree 31 of 900
building tree 32 of 900
building tree 33 of 900
building tree 34 of 900
building tree 35 of 900
building tree 36 of 900

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   54.3s

building tree 37 of 900
building tree 38 of 900
building tree 39 of 900
building tree 40 of 900
building tree 41 of 900
building tree 42 of 900
building tree 43 of 900
building tree 44 of 900
building tree 45 of 900
building tree 46 of 900

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.1min

building tree 47 of 900
building tree 48 of 900
building tree 49 of 900
building tree 50 of 900
building tree 51 of 900
building tree 52 of 900
building tree 53 of 900
building tree 54 of 900
building tree 55 of 900
building tree 56 of 900

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.5min

building tree 57 of 900
building tree 58 of 900
building tree 59 of 900
building tree 60 of 900
building tree 61 of 900
building tree 62 of 900
building tree 63 of 900
building tree 64 of 900
building tree 65 of 900
building tree 66 of 900
building tree 67 of 900
building tree 68 of 900

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  1.7min

building tree 69 of 900
building tree 70 of 900
building tree 71 of 900
building tree 72 of 900
building tree 73 of 900
building tree 74 of 900
building tree 75 of 900
building tree 76 of 900
building tree 77 of 900
building tree 78 of 900
building tree 79 of 900
building tree 80 of 900
building tree 81 of 900
building tree 82 of 900

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.2min

building tree 83 of 900
building tree 84 of 900
building tree 85 of 900
building tree 86 of 900
building tree 87 of 900
building tree 88 of 900
building tree 89 of 900
building tree 90 of 900
building tree 91 of 900
building tree 92 of 900
building tree 93 of 900
building tree 94 of 900

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.5min

building tree 95 of 900
building tree 96 of 900
building tree 97 of 900
building tree 98 of 900
building tree 99 of 900
building tree 100 of 900
building tree 101 of 900
building tree 102 of 900
building tree 103 of 900
building tree 104 of 900
building tree 105 of 900
building tree 106 of 900
building tree 107 of 900
building tree 108 of 900

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  2.9min

building tree 109 of 900
building tree 110 of 900
building tree 111 of 900
building tree 112 of 900
building tree 113 of 900
building tree 114 of 900
building tree 115 of 900
building tree 116 of 900
building tree 117 of 900
building tree 118 of 900
building tree 119 of 900
building tree 120 of 900
building tree 121 of 900
building tree 122 of 900
building tree 123 of 900
building tree 124 of 900

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  3.2min

building tree 125 of 900
building tree 126 of 900
building tree 127 of 900
building tree 128 of 900
building tree 129 of 900
building tree 130 of 900
building tree 131 of 900
building tree 132 of 900
building tree 133 of 900
building tree 134 of 900
building tree 135 of 900
building tree 136 of 900
building tree 137 of 900
building tree 138 of 900
building tree 139 of 900
building tree 140 of 900
building tree 141 of 900

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  3.7min

building tree 142 of 900
building tree 143 of 900
building tree 144 of 900
building tree 145 of 900
building tree 146 of 900
building tree 147 of 900
building tree 148 of 900
building tree 149 of 900
building tree 150 of 900
building tree 151 of 900
building tree 152 of 900
building tree 153 of 900
building tree 154 of 900
building tree 155 of 900
building tree 156 of 900
building tree 157 of 900
building tree 158 of 900

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  4.2min

building tree 159 of 900
building tree 160 of 900
building tree 161 of 900
building tree 162 of 900
building tree 163 of 900
building tree 164 of 900
building tree 165 of 900
building tree 166 of 900
building tree 167 of 900
building tree 168 of 900
building tree 169 of 900
building tree 170 of 900
building tree 171 of 900
building tree 172 of 900
building tree 173 of 900
building tree 174 of 900
building tree 175 of 900
building tree 176 of 900

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  4.7min

building tree 177 of 900
building tree 178 of 900
building tree 179 of 900
building tree 180 of 900
building tree 181 of 900
building tree 182 of 900
building tree 183 of 900
building tree 184 of 900
building tree 185 of 900
building tree 186 of 900
building tree 187 of 900
building tree 188 of 900
building tree 189 of 900
building tree 190 of 900
building tree 191 of 900
building tree 192 of 900
building tree 193 of 900
building tree 194 of 900
building tree 195 of 900

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  5.2min

building tree 196 of 900
building tree 197 of 900
building tree 198 of 900
building tree 199 of 900
building tree 200 of 900
building tree 201 of 900
building tree 202 of 900
building tree 203 of 900
building tree 204 of 900
building tree 205 of 900
building tree 206 of 900
building tree 207 of 900
building tree 208 of 900
building tree 209 of 900
building tree 210 of 900
building tree 211 of 900
building tree 212 of 900
building tree 213 of 900
building tree 214 of 900
building tree 215 of 900
building tree 216 of 900
building tree 217 of 900

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  6.0min

building tree 218 of 900
building tree 219 of 900
building tree 220 of 900
building tree 221 of 900
building tree 222 of 900
building tree 223 of 900
building tree 224 of 900
building tree 225 of 900
building tree 226 of 900
building tree 227 of 900
building tree 228 of 900
building tree 229 of 900
building tree 230 of 900
building tree 231 of 900
building tree 232 of 900
building tree 233 of 900
building tree 234 of 900
building tree 235 of 900
building tree 236 of 900
building tree 237 of 900

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  6.8min

building tree 238 of 900
building tree 239 of 900
building tree 240 of 900
building tree 241 of 900
building tree 242 of 900
building tree 243 of 900
building tree 244 of 900
building tree 245 of 900
building tree 246 of 900
building tree 247 of 900
building tree 248 of 900
building tree 249 of 900
building tree 250 of 900
building tree 251 of 900
building tree 252 of 900
building tree 253 of 900
building tree 254 of 900
building tree 255 of 900
building tree 256 of 900
building tree 257 of 900
building tree 258 of 900
building tree 259 of 900
building tree 260 of 900
building tree 261 of 900

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  7.6min

building tree 262 of 900
building tree 263 of 900
building tree 264 of 900
building tree 265 of 900
building tree 266 of 900
building tree 267 of 900
building tree 268 of 900
building tree 269 of 900
building tree 270 of 900
building tree 271 of 900
building tree 272 of 900
building tree 273 of 900
building tree 274 of 900
building tree 275 of 900
building tree 276 of 900
building tree 277 of 900
building tree 278 of 900
building tree 279 of 900
building tree 280 of 900
building tree 281 of 900
building tree 282 of 900
building tree 283 of 900
building tree 284 of 900

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  8.4min

building tree 285 of 900
building tree 286 of 900
building tree 287 of 900
building tree 288 of 900
building tree 289 of 900
building tree 290 of 900
building tree 291 of 900
building tree 292 of 900
building tree 293 of 900
building tree 294 of 900
building tree 295 of 900
building tree 296 of 900
building tree 297 of 900
building tree 298 of 900
building tree 299 of 900
building tree 300 of 900
building tree 301 of 900
building tree 302 of 900
building tree 303 of 900
building tree 304 of 900
building tree 305 of 900
building tree 306 of 900
building tree 307 of 900
building tree 308 of 900
building tree 309 of 900

[Parallel(n_jobs=-1)]: Done 305 tasks      | elapsed:  9.2min

building tree 310 of 900
building tree 311 of 900
building tree 312 of 900
building tree 313 of 900
building tree 314 of 900
building tree 315 of 900
building tree 316 of 900
building tree 317 of 900
building tree 318 of 900
building tree 319 of 900
building tree 320 of 900
building tree 321 of 900
building tree 322 of 900
building tree 323 of 900
building tree 324 of 900
building tree 325 of 900
building tree 326 of 900
building tree 327 of 900
building tree 328 of 900
building tree 329 of 900
building tree 330 of 900
building tree 331 of 900
building tree 332 of 900
building tree 333 of 900
building tree 334 of 900

[Parallel(n_jobs=-1)]: Done 330 tasks      | elapsed: 10.2min

building tree 335 of 900
building tree 336 of 900
building tree 337 of 900
building tree 338 of 900
building tree 339 of 900
building tree 340 of 900
building tree 341 of 900
building tree 342 of 900
building tree 343 of 900
building tree 344 of 900
building tree 345 of 900
building tree 346 of 900
building tree 347 of 900
building tree 348 of 900
building tree 349 of 900
building tree 350 of 900
building tree 351 of 900
building tree 352 of 900
building tree 353 of 900
building tree 354 of 900
building tree 355 of 900
building tree 356 of 900
building tree 357 of 900
building tree 358 of 900
building tree 359 of 900
building tree 360 of 900

[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed: 11.2min

building tree 361 of 900
building tree 362 of 900
building tree 363 of 900
building tree 364 of 900
building tree 365 of 900
building tree 366 of 900
building tree 367 of 900
building tree 368 of 900
building tree 369 of 900
building tree 370 of 900
building tree 371 of 900
building tree 372 of 900
building tree 373 of 900
building tree 374 of 900
building tree 375 of 900
building tree 376 of 900
building tree 377 of 900
building tree 378 of 900
building tree 379 of 900
building tree 380 of 900
building tree 381 of 900
building tree 382 of 900
building tree 383 of 900
building tree 384 of 900
building tree 385 of 900
building tree 386 of 900
building tree 387 of 900
building tree 388 of 900

[Parallel(n_jobs=-1)]: Done 384 tasks      | elapsed: 12.1min

building tree 389 of 900
building tree 390 of 900
building tree 391 of 900
building tree 392 of 900
building tree 393 of 900
building tree 394 of 900
building tree 395 of 900
building tree 396 of 900
building tree 397 of 900
building tree 398 of 900
building tree 399 of 900
building tree 400 of 900
building tree 401 of 900
building tree 402 of 900
building tree 403 of 900
building tree 404 of 900
building tree 405 of 900
building tree 406 of 900
building tree 407 of 900
building tree 408 of 900
building tree 409 of 900
building tree 410 of 900
building tree 411 of 900
building tree 412 of 900
building tree 413 of 900
building tree 414 of 900
building tree 415 of 900
building tree 416 of 900
building tree 417 of 900

[Parallel(n_jobs=-1)]: Done 413 tasks      | elapsed: 13.2min

building tree 418 of 900
building tree 419 of 900
building tree 420 of 900
building tree 421 of 900
building tree 422 of 900
building tree 423 of 900
building tree 424 of 900
building tree 425 of 900
building tree 426 of 900
building tree 427 of 900
building tree 428 of 900
building tree 429 of 900
building tree 430 of 900
building tree 431 of 900
building tree 432 of 900
building tree 433 of 900
building tree 434 of 900
building tree 435 of 900
building tree 436 of 900
building tree 437 of 900
building tree 438 of 900
building tree 439 of 900
building tree 440 of 900
building tree 441 of 900
building tree 442 of 900
building tree 443 of 900
building tree 444 of 900
building tree 445 of 900

[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed: 14.2min

building tree 446 of 900
building tree 447 of 900
building tree 448 of 900
building tree 449 of 900
building tree 450 of 900
building tree 451 of 900
building tree 452 of 900
building tree 453 of 900
building tree 454 of 900
building tree 455 of 900
building tree 456 of 900
building tree 457 of 900
building tree 458 of 900
building tree 459 of 900
building tree 460 of 900
building tree 461 of 900
building tree 462 of 900
building tree 463 of 900
building tree 464 of 900
building tree 465 of 900
building tree 466 of 900
building tree 467 of 900
building tree 468 of 900
building tree 469 of 900
building tree 470 of 900
building tree 471 of 900
building tree 472 of 900
building tree 473 of 900
building tree 474 of 900
building tree 475 of 900
building tree 476 of 900
building tree 477 of 900

[Parallel(n_jobs=-1)]: Done 473 tasks      | elapsed: 15.3min

building tree 478 of 900
building tree 479 of 900
building tree 480 of 900
building tree 481 of 900
building tree 482 of 900
building tree 483 of 900
building tree 484 of 900
building tree 485 of 900
building tree 486 of 900
building tree 487 of 900
building tree 488 of 900
building tree 489 of 900
building tree 490 of 900
building tree 491 of 900
building tree 492 of 900
building tree 493 of 900
building tree 494 of 900
building tree 495 of 900
building tree 496 of 900
building tree 497 of 900
building tree 498 of 900
building tree 499 of 900
building tree 500 of 900
building tree 501 of 900
building tree 502 of 900
building tree 503 of 900
building tree 504 of 900
building tree 505 of 900
building tree 506 of 900
building tree 507 of 900
building tree 508 of 900

[Parallel(n_jobs=-1)]: Done 504 tasks      | elapsed: 16.3min

building tree 509 of 900
building tree 510 of 900
building tree 511 of 900
building tree 512 of 900
building tree 513 of 900
building tree 514 of 900
building tree 515 of 900
building tree 516 of 900
building tree 517 of 900
building tree 518 of 900
building tree 519 of 900
building tree 520 of 900
building tree 521 of 900
building tree 522 of 900
building tree 523 of 900
building tree 524 of 900
building tree 525 of 900
building tree 526 of 900
building tree 527 of 900
building tree 528 of 900
building tree 529 of 900
building tree 530 of 900
building tree 531 of 900
building tree 532 of 900
building tree 533 of 900
building tree 534 of 900
building tree 535 of 900
building tree 536 of 900
building tree 537 of 900
building tree 538 of 900
building tree 539 of 900
building tree 540 of 900
building tree 541 of 900

[Parallel(n_jobs=-1)]: Done 537 tasks      | elapsed: 17.4min

building tree 542 of 900
building tree 543 of 900
building tree 544 of 900
building tree 545 of 900
building tree 546 of 900
building tree 547 of 900
building tree 548 of 900
building tree 549 of 900
building tree 550 of 900
building tree 551 of 900
building tree 552 of 900
building tree 553 of 900
building tree 554 of 900
building tree 555 of 900
building tree 556 of 900
building tree 557 of 900
building tree 558 of 900
building tree 559 of 900
building tree 560 of 900
building tree 561 of 900
building tree 562 of 900
building tree 563 of 900
building tree 564 of 900
building tree 565 of 900
building tree 566 of 900
building tree 567 of 900
building tree 568 of 900
building tree 569 of 900
building tree 570 of 900
building tree 571 of 900
building tree 572 of 900
building tree 573 of 900
building tree 574 of 900

[Parallel(n_jobs=-1)]: Done 570 tasks      | elapsed: 18.6min

building tree 575 of 900
building tree 576 of 900
building tree 577 of 900
building tree 578 of 900
building tree 579 of 900
building tree 580 of 900
building tree 581 of 900
building tree 582 of 900
building tree 583 of 900
building tree 584 of 900
building tree 585 of 900
building tree 586 of 900
building tree 587 of 900
building tree 588 of 900
building tree 589 of 900
building tree 590 of 900
building tree 591 of 900
building tree 592 of 900
building tree 593 of 900
building tree 594 of 900
building tree 595 of 900
building tree 596 of 900
building tree 597 of 900
building tree 598 of 900
building tree 599 of 900
building tree 600 of 900
building tree 601 of 900
building tree 602 of 900
building tree 603 of 900
building tree 604 of 900
building tree 605 of 900
building tree 606 of 900
building tree 607 of 900
building tree 608 of 900
building tree 609 of 900

[Parallel(n_jobs=-1)]: Done 605 tasks      | elapsed: 19.9min

building tree 610 of 900
building tree 611 of 900
building tree 612 of 900
building tree 613 of 900
building tree 614 of 900
building tree 615 of 900
building tree 616 of 900
building tree 617 of 900
building tree 618 of 900
building tree 619 of 900
building tree 620 of 900
building tree 621 of 900
building tree 622 of 900
building tree 623 of 900
building tree 624 of 900
building tree 625 of 900
building tree 626 of 900
building tree 627 of 900
building tree 628 of 900
building tree 629 of 900
building tree 630 of 900
building tree 631 of 900
building tree 632 of 900
building tree 633 of 900
building tree 634 of 900
building tree 635 of 900
building tree 636 of 900
building tree 637 of 900
building tree 638 of 900
building tree 639 of 900
building tree 640 of 900
building tree 641 of 900
building tree 642 of 900
building tree 643 of 900
building tree 644 of 900

[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed: 21.0min

building tree 645 of 900
building tree 646 of 900
building tree 647 of 900
building tree 648 of 900
building tree 649 of 900
building tree 650 of 900
building tree 651 of 900
building tree 652 of 900
building tree 653 of 900
building tree 654 of 900
building tree 655 of 900
building tree 656 of 900
building tree 657 of 900
building tree 658 of 900
building tree 659 of 900
building tree 660 of 900
building tree 661 of 900
building tree 662 of 900
building tree 663 of 900
building tree 664 of 900
building tree 665 of 900
building tree 666 of 900
building tree 667 of 900
building tree 668 of 900
building tree 669 of 900
building tree 670 of 900
building tree 671 of 900
building tree 672 of 900
building tree 673 of 900
building tree 674 of 900
building tree 675 of 900
building tree 676 of 900
building tree 677 of 900
building tree 678 of 900
building tree 679 of 900
building tree 680 of 900
building tree 681 of 900

[Parallel(n_jobs=-1)]: Done 677 tasks      | elapsed: 22.3min

building tree 682 of 900
building tree 683 of 900
building tree 684 of 900
building tree 685 of 900
building tree 686 of 900
building tree 687 of 900
building tree 688 of 900
building tree 689 of 900
building tree 690 of 900
building tree 691 of 900
building tree 692 of 900
building tree 693 of 900
building tree 694 of 900
building tree 695 of 900
building tree 696 of 900
building tree 697 of 900
building tree 698 of 900
building tree 699 of 900
building tree 700 of 900
building tree 701 of 900
building tree 702 of 900
building tree 703 of 900
building tree 704 of 900
building tree 705 of 900
building tree 706 of 900
building tree 707 of 900
building tree 708 of 900
building tree 709 of 900
building tree 710 of 900
building tree 711 of 900
building tree 712 of 900
building tree 713 of 900
building tree 714 of 900
building tree 715 of 900
building tree 716 of 900
building tree 717 of 900

[Parallel(n_jobs=-1)]: Done 714 tasks      | elapsed: 23.6min

building tree 718 of 900
building tree 719 of 900
building tree 720 of 900
building tree 721 of 900
building tree 722 of 900
building tree 723 of 900
building tree 724 of 900
building tree 725 of 900
building tree 726 of 900
building tree 727 of 900
building tree 728 of 900
building tree 729 of 900
building tree 730 of 900
building tree 731 of 900
building tree 732 of 900
building tree 733 of 900
building tree 734 of 900
building tree 735 of 900
building tree 736 of 900
building tree 737 of 900
building tree 738 of 900
building tree 739 of 900
building tree 740 of 900
building tree 741 of 900
building tree 742 of 900
building tree 743 of 900
building tree 744 of 900
building tree 745 of 900
building tree 746 of 900
building tree 747 of 900
building tree 748 of 900
building tree 749 of 900
building tree 750 of 900
building tree 751 of 900
building tree 752 of 900
building tree 753 of 900
building tree 754 of 900
building tree 755 of 900
building tree 756 of 900
building tree 757 of 900

[Parallel(n_jobs=-1)]: Done 753 tasks      | elapsed: 25.0min

building tree 758 of 900
building tree 759 of 900
building tree 760 of 900
building tree 761 of 900
building tree 762 of 900
building tree 763 of 900
building tree 764 of 900
building tree 765 of 900
building tree 766 of 900
building tree 767 of 900
building tree 768 of 900
building tree 769 of 900
building tree 770 of 900
building tree 771 of 900
building tree 772 of 900
building tree 773 of 900
building tree 774 of 900
building tree 775 of 900
building tree 776 of 900
building tree 777 of 900
building tree 778 of 900
building tree 779 of 900
building tree 780 of 900
building tree 781 of 900
building tree 782 of 900
building tree 783 of 900
building tree 784 of 900
building tree 785 of 900
building tree 786 of 900
building tree 787 of 900
building tree 788 of 900
building tree 789 of 900
building tree 790 of 900
building tree 791 of 900
building tree 792 of 900
building tree 793 of 900
building tree 794 of 900
building tree 795 of 900
building tree 796 of 900

[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed: 26.0min

building tree 797 of 900
building tree 798 of 900
building tree 799 of 900
building tree 800 of 900
building tree 801 of 900
building tree 802 of 900
building tree 803 of 900
building tree 804 of 900
building tree 805 of 900
building tree 806 of 900
building tree 807 of 900
building tree 808 of 900
building tree 809 of 900
building tree 810 of 900
building tree 811 of 900
building tree 812 of 900
building tree 813 of 900
building tree 814 of 900
building tree 815 of 900
building tree 816 of 900
building tree 817 of 900
building tree 818 of 900
building tree 819 of 900
building tree 820 of 900
building tree 821 of 900
building tree 822 of 900
building tree 823 of 900
building tree 824 of 900
building tree 825 of 900
building tree 826 of 900
building tree 827 of 900
building tree 828 of 900
building tree 829 of 900
building tree 830 of 900
building tree 831 of 900
building tree 832 of 900
building tree 833 of 900
building tree 834 of 900
building tree 835 of 900
building tree 836 of 900

[Parallel(n_jobs=-1)]: Done 833 tasks      | elapsed: 27.2min

building tree 837 of 900
building tree 838 of 900
building tree 839 of 900
building tree 840 of 900
building tree 841 of 900
building tree 842 of 900
building tree 843 of 900
building tree 844 of 900
building tree 845 of 900
building tree 846 of 900
building tree 847 of 900
building tree 848 of 900
building tree 849 of 900
building tree 850 of 900
building tree 851 of 900
building tree 852 of 900
building tree 853 of 900
building tree 854 of 900
building tree 855 of 900
building tree 856 of 900
building tree 857 of 900
building tree 858 of 900
building tree 859 of 900
building tree 860 of 900
building tree 861 of 900
building tree 862 of 900
building tree 863 of 900
building tree 864 of 900
building tree 865 of 900
building tree 866 of 900
building tree 867 of 900
building tree 868 of 900
building tree 869 of 900
building tree 870 of 900
building tree 871 of 900
building tree 872 of 900
building tree 873 of 900
building tree 874 of 900
building tree 875 of 900
building tree 876 of 900
building tree 877 of 900

[Parallel(n_jobs=-1)]: Done 874 tasks      | elapsed: 28.2min

building tree 878 of 900
building tree 879 of 900
building tree 880 of 900
building tree 881 of 900
building tree 882 of 900
building tree 883 of 900
building tree 884 of 900
building tree 885 of 900
building tree 886 of 900
building tree 887 of 900
building tree 888 of 900
building tree 889 of 900
building tree 890 of 900
building tree 891 of 900
building tree 892 of 900
building tree 893 of 900
building tree 894 of 900
building tree 895 of 900
building tree 896 of 900
building tree 897 of 900
building tree 898 of 900
building tree 899 of 900
building tree 900 of 900

[Parallel(n_jobs=-1)]: Done 900 out of 900 | elapsed: 28.9min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    1.3s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    1.8s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    1.9s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    2.4s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    3.1s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    6.5s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    6.9s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    7.2s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:    7.4s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:    7.8s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:   11.0s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:   11.9s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   12.3s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   12.8s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   14.9s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   16.2s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   19.8s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   20.4s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   23.6s
[Parallel(n_jobs=4)]: Done 305 tasks      | elapsed:   24.2s
[Parallel(n_jobs=4)]: Done 330 tasks      | elapsed:   24.8s
[Parallel(n_jobs=4)]: Done 357 tasks      | elapsed:   28.8s
[Parallel(n_jobs=4)]: Done 384 tasks      | elapsed:   29.4s
[Parallel(n_jobs=4)]: Done 413 tasks      | elapsed:   32.8s
[Parallel(n_jobs=4)]: Done 442 tasks      | elapsed:   33.5s
[Parallel(n_jobs=4)]: Done 473 tasks      | elapsed:   36.9s
[Parallel(n_jobs=4)]: Done 504 tasks      | elapsed:   38.2s
[Parallel(n_jobs=4)]: Done 537 tasks      | elapsed:   41.0s
[Parallel(n_jobs=4)]: Done 570 tasks      | elapsed:   44.1s
[Parallel(n_jobs=4)]: Done 605 tasks      | elapsed:   46.2s
[Parallel(n_jobs=4)]: Done 640 tasks      | elapsed:   48.7s
[Parallel(n_jobs=4)]: Done 677 tasks      | elapsed:   51.3s
[Parallel(n_jobs=4)]: Done 714 tasks      | elapsed:   54.9s
[Parallel(n_jobs=4)]: Done 753 tasks      | elapsed:   56.0s
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed:  1.0min
[Parallel(n_jobs=4)]: Done 833 tasks      | elapsed:  1.0min
[Parallel(n_jobs=4)]: Done 874 tasks      | elapsed:  1.1min
[Parallel(n_jobs=4)]: Done 900 out of 900 | elapsed:  1.1min finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 900 / Depth: None ---- Precision: [ 0.8617284   0.77777778  0.73214286  0.6         0.47826087  0.53731343
  0.6875      1.          0.          0.          0.75862069  0.45292621
  0.          0.73333333  0.          0.          0.89830508  0.375       0.15
  0.61333333  0.84313725  0.          0.86861314  0.875       0.5744089
  0.81656805  0.62264151  0.85106383  0.85714286  0.          0.79487179
  0.21052632  0.44444444  0.75862069  0.39285714  0.63636364  0.35534591
  1.          0.7826087   0.66666667  0.          0.          0.53250774
  0.          0.83333333  0.62765957  0.57142857  0.28        0.6
  0.22222222  0.          0.47142857  0.6875      0.38848921  0.
  0.57894737  0.66666667  0.51369863  0.8         0.62328767  1.          1.
  0.          0.37647059  0.8         0.12        0.          0.63636364
  0.          0.90116279  0.92682927  1.          0.91025641  0.52173913
  0.65373134  0.          0.21568627  0.77925532  0.          0.36363636
  0.          0.64705882  1.          0.83333333  0.78894472  0.33333333
  0.          0.          0.45528455  0.90909091  0.          1.
  0.47580645  0.          0.          0.2         0.66037736  1.
  0.71212121  1.          0.42857143  0.          0.69270833  0.92307692
  0.3         0.66666667  0.          0.5         0.66666667  0.5754717
  0.94117647  0.          0.          0.33333333  0.875       1.
  0.65909091  0.9375    ] / Recall: [ 0.99714286  0.93333333  0.5125      0.75        0.54098361  0.63157895
  0.44        0.26923077  0.          0.          0.84615385  0.80361174
  0.          0.54098361  0.          0.          0.84126984  0.42857143
  0.0483871   0.32624113  0.95555556  0.          0.99166667  0.58333333
  0.86221294  0.91390728  0.72131148  0.6779661   0.4137931   0.
  0.95384615  0.09375     0.23529412  0.91666667  0.5         0.56756757
  0.74834437  0.07692308  0.65693431  0.23255814  0.          0.
  0.75770925  0.          0.66666667  0.70238095  0.13793103  0.07865169
  0.11111111  0.03571429  0.          0.25581395  1.          0.44628099
  0.          0.39285714  0.75        0.86206897  0.92753623  0.91919192
  0.25        0.57894737  0.          0.78527607  0.63157895  0.02325581
  0.          0.13461538  0.          0.99358974  0.93442623  0.07142857
  0.97260274  0.4         0.96475771  0.          0.18333333  0.9184953   0.
  0.30769231  0.          0.26190476  0.60869565  0.55555556  0.97515528
  0.28571429  0.          0.          0.66666667  0.4         0.
  0.57142857  0.33714286  0.          0.          0.5         0.83333333
  0.52941176  0.88679245  0.25        0.4         0.          0.76
  0.66666667  0.09375     0.08928571  0.          0.33333333  0.11111111
  0.67032967  0.8         0.          0.          0.06521739  0.29166667
  0.33333333  0.3258427   0.75      ] / Accuracy: 0.62

In [103]:
train_RF(300, None) # 0.618 accuracy if i use wordnet lemamtizing

building tree 1 of 300
building tree 3 of 300building tree 2 of 300building tree 4 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   11.8s

building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   17.7s

building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   29.6s

building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   36.3s

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   53.3s

building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.1min

building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  1.4min

building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  1.6min

building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300
building tree 82 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  2.1min

building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  2.4min

building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  2.8min

building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  3.2min

building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  3.6min

building tree 141 of 300
building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  4.0min

building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  4.5min

building tree 177 of 300
building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  5.0min

building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300
building tree 217 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed:  5.7min

building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300
building tree 238 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed:  6.3min

building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed:  7.0min

building tree 261 of 300
building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed:  7.6min

building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.2min finished
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.7s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    2.1s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    4.3s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    4.6s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    4.8s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    5.1s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:    6.9s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:   10.3s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:   10.8s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:   11.1s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:   13.2s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   14.5s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   15.1s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   18.3s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   18.7s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   19.3s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   24.4s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   24.9s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:   25.3s finished
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Est: 300 / Depth: None ---- Precision: [ 0.92915531  0.83333333  0.59166667  0.83333333  0.35555556  0.61538462
  0.73684211  0.88888889  0.          0.5         0.75        0.44536817
  0.5         0.68181818  1.          0.89230769  0.8         0.
  0.67326733  0.86516854  0.          0.91603053  0.76923077  0.58474576
  0.83636364  0.56730769  0.86885246  0.92857143  0.          0.77319588
  0.25730994  0.71428571  0.84848485  0.525       0.64516129  0.28571429
  1.          0.71111111  0.57142857  0.66666667  1.          0.56923077
  0.          0.76923077  0.62765957  0.6         0.31764706  0.45454545
  0.33333333  0.          0.35714286  1.          0.43609023  0.          0.6
  0.75        0.47402597  0.7721519   0.72727273  0.8         0.73913043
  0.          0.41697417  0.875       0.21875     0.66666667  0.7         0.
  0.9         0.88118812  1.          0.82352941  0.52941176  0.58255452
  1.          0.22222222  0.79076087  1.          0.625       0.          0.56
  0.83333333  0.64285714  0.77830189  0.3902439   0.          0.
  0.57731959  0.86842105  0.          0.75        0.39215686  0.          0.
  0.79310345  0.8         0.78082192  0.77777778  0.61538462  0.          0.7254902
  0.94117647  0.27906977  0.81818182  0.66666667  0.5         0.
  0.56666667  0.90909091  0.          0.33333333  0.28571429  1.          1.
  0.85294118  0.84615385] / Recall: [ 0.9941691   0.6         0.51449275  0.86956522  0.33333333  0.53333333
  0.46666667  0.36363636  0.          0.2         0.9         0.79113924
  0.08333333  0.65217391  0.125       0.85294118  0.5         0.
  0.36756757  0.9625      0.          0.99173554  0.71428571  0.82733813
  0.8961039   0.77631579  0.76811594  0.41935484  0.          0.98684211
  0.17322835  0.22727273  0.875       0.72413793  0.52631579  0.1147541
  0.0625      0.60377358  0.11764706  0.33333333  0.66666667  0.7254902   0.
  0.90909091  0.72839506  0.2         0.14438503  0.09259259  0.05        0.
  0.23809524  1.          0.50434783  0.          0.10344828  0.5
  0.8902439   0.84722222  0.98113208  0.23529412  0.89473684  0.
  0.76351351  0.63636364  0.175       0.13333333  0.14583333  0.
  0.98780488  0.90816327  0.13333333  0.94594595  0.29032258  0.95897436
  0.18181818  0.07843137  0.96677741  0.1         0.3125      0.
  0.46666667  0.58823529  0.69230769  0.9939759   0.21917808  0.          0.
  0.74666667  0.58928571  0.          1.          0.74766355  0.          0.
  0.83636364  0.25        0.86363636  0.26923077  0.53333333  0.          0.7254902
  0.72727273  0.23529412  0.0703125   0.04651163  0.22222222  0.
  0.64150943  0.83333333  0.          0.02941176  0.03571429  0.31818182
  0.2         0.3625      0.64705882] / Accuracy: 0.618

In [14]:
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier()
param = {'n_estimators': [10, 150, 300],
        'max_depth': [30, 90, None],
         'verbose': [10]
        }

In [ ]:
gs = GridSearchCV(rf, param, cv=5, n_jobs=-1, verbose=10)
gs_fit = gs.fit(tfidf_vectorized_matrix_ps, data['label'])
pd.DataFrame(gs_fit.cv_results_).sort_values('mean_test_score', ascending=False)[0:5]

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   17.2s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:  4.2min
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:  8.6min
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed: 21.6min

### my laptop doesnt have enough memory to run GridsearchCV above 
### so I ran the same on EC2 instance and got n_est 300 and depth None as best mean test score

In [15]:
def train_GB(est, max_depth, lr):
    gb = GradientBoostingClassifier(n_estimators=est, max_depth=max_depth, learning_rate=lr , verbose=10)
    gb_model = gb.fit(X_train, y_train)
    y_pred = gb_model.predict(X_test)
    precision, recall, fscore, train_support = score(y_test, y_pred)
    print('Est: {} / Depth: {} / LR: {} ---- Precision: {} / Recall: {} / Accuracy: {}'.format(
        est, max_depth, lr, precision,recall, 
        round((y_pred==y_test).sum()/len(y_pred), 3)))

In [16]:
from ipywidgets import FloatProgress
from IPython.display import display

In [ ]:
max_count = 12
count = 0
progressBar = FloatProgress(min=0, max=max_count)
display(progressBar)

for n_est in [50, 100, 150]:
    for max_depth in [3, 7, 11, 15]:
        print("\n\nTraining combination: n_est:{n_est} - max_depth:{max_depth}".format(n_est=str(n_est),max_depth=str(max_depth)))
        progressBar.value+=1
        count += 1
        train_GB(n_est, max_depth, 0.01)

A Jupyter Widget

Training combination: 50 - 3

C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\chrisq\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

Est: 50 / Depth: 3 / LR: 0.01 ---- Precision: [ 0.93452381  0.96        0.73451327  0.75        0.28        0.48        0.71875
  0.45        0.          0.41666667  0.81538462  0.34558824  0.
  0.72972973  0.          0.16666667  0.74545455  0.83333333  0.07692308
  0.61458333  0.83333333  0.          0.90833333  0.75        0.65492958
  0.81761006  0.7         0.69565217  0.76470588  0.5         0.81428571
  0.30508475  0.57142857  0.90243902  0.53125     0.53846154  0.28851541
  0.66666667  0.65137615  0.38461538  0.83333333  1.          0.49832776
  0.          0.86956522  0.43434343  0.66666667  0.19354839  0.66666667
  0.08333333  0.55555556  0.40243902  1.          0.4159292   0.          0.53125
  1.          0.55555556  0.81578947  0.8         0.53846154  0.76470588
  0.          0.36394558  0.84615385  0.11363636  0.75        0.59259259
  0.          0.91156463  0.8877551   0.          0.89041096  0.41176471
  0.68543046  0.625       0.18681319  0.77777778  0.          0.66666667
  0.          0.43333333  0.61111111  0.63636364  0.83428571  0.40350877
  0.          0.          0.47863248  0.89655172  0.33333333  1.
  0.58823529  0.          0.3         0.16666667  0.71428571  0.55
  0.67142857  0.66666667  0.81818182  0.          0.65968586  0.94444444
  0.35897436  0.52173913  0.          0.5         0.75        0.48181818
  0.81818182  0.8         0.          0.23529412  0.38888889  0.5
  0.68518519  0.95      ] / Recall: [ 0.96024465  0.92307692  0.48538012  0.77777778  0.34146341  0.61016949
  0.60526316  0.36        0.          0.55555556  0.85483871  0.76334107
  0.          0.52941176  0.          0.16666667  0.70689655  0.55555556
  0.01219512  0.37341772  0.77464789  0.          0.90082645  0.85714286
  0.80345572  0.86092715  0.73684211  0.60377358  0.54166667  0.11111111
  0.91935484  0.24324324  0.34782609  0.80434783  0.60714286  0.65625
  0.79230769  0.36363636  0.57723577  0.27777778  0.38461538  0.33333333
  0.72682927  0.          0.70175439  0.5375      0.2         0.04545455
  0.14814815  0.01315789  0.07692308  0.23239437  0.88235294  0.4017094   0.
  0.68        0.5         0.80645161  0.86111111  0.81355932  0.31818182
  0.56521739  0.          0.76978417  0.45833333  0.04        0.28571429
  0.33333333  0.          0.86451613  0.93548387  0.          0.79268293
  0.58333333  0.90789474  0.71428571  0.28813559  0.88421053  0.
  0.31578947  0.          0.39393939  0.42307692  0.41176471  0.86390533
  0.26436782  0.          0.          0.64367816  0.40625     0.1
  0.85714286  0.23255814  0.          0.2         0.5         0.8         0.44
  0.79661017  0.52173913  0.31034483  0.          0.81818182  0.94444444
  0.19444444  0.11650485  0.          0.25        0.16666667  0.67088608
  0.6         0.8         0.          0.07843137  0.38888889  0.33333333
  0.52112676  0.9047619 ] / Accuracy: 0.59


Training combination: 50 - 7
Est: 50 / Depth: 7 / LR: 0.01 ---- Precision: [ 0.93529412  0.95        0.67521368  0.72413793  0.3125      0.49275362
  0.60526316  0.55555556  0.          0.2         0.82258065  0.34863388
  0.          0.68571429  0.          0.25        0.82        0.875
  0.08695652  0.60784314  0.83823529  0.          0.9137931   0.8
  0.66727941  0.81212121  0.66853933  0.68        0.86666667  0.          0.828125
  0.23893805  0.53846154  0.8974359   0.55555556  0.45714286  0.30943396
  0.5         0.63302752  0.13333333  0.83333333  1.          0.49458484
  0.          0.88636364  0.48148148  0.5         0.13924051  0.47826087
  0.2         0.30434783  0.30232558  1.          0.37414966  0.
  0.46666667  1.          0.56097561  0.82191781  0.80869565  0.45454545
  0.72222222  0.          0.34920635  0.8125      0.08333333  0.77777778
  0.46428571  0.          0.9205298   0.89690722  0.33333333  0.89041096
  0.40540541  0.66666667  0.57142857  0.15068493  0.78930818  0.          0.625
  0.          0.33333333  0.66666667  0.77777778  0.84745763  0.36538462
  0.          0.          0.46464646  0.78947368  0.3125      1.          0.4
  0.          0.125       0.33333333  0.70833333  0.52631579  0.66153846
  0.6875      0.7         0.33333333  0.68131868  0.94444444  0.40909091
  0.35294118  0.09090909  0.5         0.5         0.42477876  0.81818182
  0.66666667  0.07142857  0.36842105  0.35        1.          0.62962963
  0.9047619 ] / Recall: [ 0.97247706  0.73076923  0.4619883   0.77777778  0.36585366  0.57627119
  0.60526316  0.4         0.          0.11111111  0.82258065  0.74013921
  0.          0.47058824  0.          0.16666667  0.70689655  0.77777778
  0.02439024  0.39240506  0.8028169   0.          0.87603306  0.85714286
  0.78401728  0.88741722  0.69590643  0.64150943  0.54166667  0.
  0.85483871  0.18243243  0.30434783  0.76086957  0.53571429  0.5
  0.63076923  0.36363636  0.56097561  0.05555556  0.38461538  0.16666667
  0.66829268  0.          0.68421053  0.4875      0.175       0.08333333
  0.2037037   0.05263158  0.10769231  0.18309859  0.82352941  0.47008547
  0.          0.56        0.33333333  0.74193548  0.83333333  0.78813559
  0.22727273  0.56521739  0.          0.63309353  0.54166667  0.064
  0.33333333  0.27083333  0.          0.89677419  0.93548387  0.09090909
  0.79268293  0.625       0.81578947  0.57142857  0.18644068  0.88070175
  0.          0.26315789  0.          0.42424242  0.46153846  0.41176471
  0.88757396  0.2183908   0.          0.          0.52873563  0.46875
  0.16666667  0.85714286  0.36046512  0.          0.06666667  0.5         0.68
  0.4         0.72881356  0.47826087  0.24137931  0.33333333  0.80519481
  0.94444444  0.25        0.17475728  0.05357143  0.375       0.05555556
  0.60759494  0.6         0.8         0.03703704  0.1372549   0.38888889
  0.33333333  0.47887324  0.9047619 ] / Accuracy: 0.572


Training combination: 50 - 11
Est: 50 / Depth: 11 / LR: 0.01 ---- Precision: [ 0.94311377  0.95238095  0.65254237  0.65517241  0.3902439   0.41818182
  0.61538462  0.81818182  0.          0.          0.79365079  0.31034483
  0.          0.67647059  0.          0.25        0.86363636  0.77777778
  0.03846154  0.59433962  0.8         0.          0.91452991  0.78571429
  0.67931689  0.81578947  0.66091954  0.66037736  0.86666667  0.
  0.83333333  0.23376623  0.57142857  0.92105263  0.51724138  0.46875
  0.30204082  0.42857143  0.62244898  0.21428571  0.83333333  1.
  0.46570397  0.          0.86666667  0.44594595  0.57142857  0.09876543
  0.44        0.20833333  0.18181818  0.31818182  1.          0.33103448
  0.          0.46428571  1.          0.55555556  0.82352941  0.78448276
  0.4         0.90909091  0.          0.35950413  0.8         0.06481481
  0.77777778  0.42105263  0.          0.92810458  0.90425532  0.30769231
  0.91549296  0.46666667  0.66415094  0.71428571  0.17142857  0.8         0.
  0.7         0.          0.38461538  0.69230769  0.77777778  0.8372093
  0.30769231  0.          0.          0.46875     0.775       0.46153846
  1.          0.34337349  0.          0.22222222  0.25        0.7173913
  0.30769231  0.71186441  0.66666667  0.75        0.33333333  0.65027322
  0.94444444  0.43137255  0.35        0.06666667  0.42857143  0.33333333
  0.40740741  0.90909091  0.6         0.04761905  0.4         0.38888889
  0.33333333  0.68627451  0.90909091] / Recall: [ 0.96330275  0.76923077  0.4502924   0.7037037   0.3902439   0.38983051
  0.42105263  0.36        0.          0.          0.80645161  0.7099768   0.
  0.45098039  0.          0.16666667  0.65517241  0.77777778  0.01219512
  0.39873418  0.78873239  0.          0.88429752  0.78571429  0.77321814
  0.82119205  0.67251462  0.66037736  0.54166667  0.          0.80645161
  0.24324324  0.34782609  0.76086957  0.53571429  0.46875     0.56923077
  0.27272727  0.49593496  0.08333333  0.38461538  0.16666667  0.62926829
  0.          0.68421053  0.4125      0.2         0.06060606  0.2037037
  0.06578947  0.06153846  0.1971831   0.82352941  0.41025641  0.          0.52
  0.33333333  0.64516129  0.77777778  0.77118644  0.18181818  0.43478261
  0.          0.62589928  0.5         0.056       0.33333333  0.33333333
  0.          0.91612903  0.91397849  0.36363636  0.79268293  0.58333333
  0.77192982  0.71428571  0.20338983  0.87017544  0.          0.36842105
  0.          0.45454545  0.34615385  0.41176471  0.85207101  0.18390805
  0.          0.          0.51724138  0.484375    0.2         0.85714286
  0.33139535  0.          0.13333333  0.5         0.66        0.16
  0.71186441  0.43478261  0.31034483  0.33333333  0.77272727  0.94444444
  0.30555556  0.2038835   0.05357143  0.375       0.05555556  0.55696203
  0.66666667  0.6         0.03703704  0.23529412  0.38888889  0.33333333
  0.49295775  0.95238095] / Accuracy: 0.555


Training combination: 50 - 15

Est: 50 / Depth: 15 / LR: 0.01 ---- Precision: [ 0.94864048  0.95238095  0.62601626  0.59375     0.34285714  0.49019608
  0.64        0.64285714  0.          0.          0.77777778  0.27158099
  0.          0.64516129  0.          0.2         0.84444444  0.77777778
  0.03846154  0.52991453  0.79710145  0.          0.90677966  0.8
  0.66793893  0.82550336  0.69871795  0.70212766  0.92857143  0.
  0.81355932  0.17682927  0.5         0.92105263  0.48275862  0.46666667
  0.31481481  0.42857143  0.6         0.30434783  0.83333333  1.          0.4924812
  0.          0.82978723  0.44615385  0.52941176  0.09174312  0.42307692
  0.25        0.14814815  0.32467532  1.          0.37162162  0.
  0.51612903  1.          0.56521739  0.8358209   0.77777778  0.4
  0.90909091  0.          0.37089202  0.8         0.08823529  0.5
  0.45714286  0.07692308  0.93377483  0.91304348  0.25        0.92647059
  0.44444444  0.67054264  0.71428571  0.15789474  0.78456592  0.          0.6
  0.          0.37209302  0.61538462  0.75        0.83529412  0.30508475
  0.          0.          0.46511628  0.71428571  0.5         1.
  0.36363636  0.          0.22222222  0.16666667  0.76744186  0.35714286
  0.70909091  0.66666667  0.72727273  0.33333333  0.64285714  0.94117647
  0.4137931   0.35384615  0.05263158  0.28571429  0.33333333  0.41414141
  0.9         0.6         0.04761905  0.34146341  0.38888889  0.33333333
  0.63461538  0.9047619 ] / Recall: [ 0.96024465  0.76923077  0.4502924   0.7037037   0.29268293  0.42372881
  0.42105263  0.36        0.          0.          0.79032258  0.64965197
  0.          0.39215686  0.          0.16666667  0.65517241  0.77777778
  0.01219512  0.39240506  0.77464789  0.          0.88429752  0.85714286
  0.75593952  0.81456954  0.6374269   0.62264151  0.54166667  0.
  0.77419355  0.19594595  0.26086957  0.76086957  0.5         0.4375
  0.52307692  0.27272727  0.48780488  0.19444444  0.38461538  0.16666667
  0.63902439  0.          0.68421053  0.3625      0.225       0.07575758
  0.2037037   0.09210526  0.06153846  0.17605634  0.82352941  0.47008547
  0.          0.64        0.33333333  0.55913978  0.77777778  0.71186441
  0.18181818  0.43478261  0.          0.56834532  0.5         0.096
  0.14285714  0.33333333  0.02272727  0.90967742  0.90322581  0.18181818
  0.76829268  0.5         0.75877193  0.71428571  0.20338983  0.85614035
  0.          0.31578947  0.          0.48484848  0.30769231  0.35294118
  0.84023669  0.20689655  0.          0.          0.45977011  0.46875
  0.16666667  0.85714286  0.37209302  0.          0.13333333  0.5         0.66
  0.2         0.66101695  0.34782609  0.27586207  0.33333333  0.75974026
  0.88888889  0.33333333  0.22330097  0.03571429  0.25        0.05555556
  0.51898734  0.6         0.6         0.03703704  0.2745098   0.38888889
  0.33333333  0.46478873  0.9047619 ] / Accuracy: 0.541


Training combination: 100 - 3

In [ ]:
gb = GradientBoostingClassifier()
param = {
    'n_estimators': [50, 100, 150], 
    'max_depth': [7, 11, 15],
    'learning_rate': [0.01]
}

clf = GridSearchCV(gb, param, cv=5, n_jobs=-1)
cv_fit = clf.fit(tfidf_vectorized_matrix_ps, data['label'])
pd.DataFrame(cv_fit.cv_results_).sort_values('mean_test_score', ascending=False)[0:5]

In [26]:
tfidf_vect_fit = tfidf_vectorizer_ps.fit(data['feature'])

tfidf_train = tfidf_vect_fit.transform(data['feature'])

In [27]:
rf = RandomForestClassifier(n_estimators=300, max_depth=None, n_jobs=-1, verbose=10)
rf_model = rf.fit(tfidf_train, data['label'])

building tree 1 of 300building tree 2 of 300building tree 3 of 300
building tree 4 of 300


building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300

[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   21.2s

building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300
building tree 16 of 300

[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   31.2s

building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   51.8s

building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:  1.0min

building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.6min

building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  2.0min

building tree 46 of 300
building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300

[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:  2.6min

building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300

[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:  3.0min

building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300

[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:  3.7min

building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300

[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:  4.3min

building tree 94 of 300
building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300

[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:  5.0min

building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300

[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:  5.5min

building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300

[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  6.6min

building tree 141 of 300
building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300

[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  7.5min

building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300

[Parallel(n_jobs=-1)]: Done 173 tasks      | elapsed:  8.4min

building tree 177 of 300
building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300

[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  9.2min

building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300
building tree 217 of 300

[Parallel(n_jobs=-1)]: Done 213 tasks      | elapsed: 10.1min

building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300
building tree 238 of 300
building tree 239 of 300

[Parallel(n_jobs=-1)]: Done 234 tasks      | elapsed: 11.0min

building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300

[Parallel(n_jobs=-1)]: Done 257 tasks      | elapsed: 11.9min

building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300

[Parallel(n_jobs=-1)]: Done 280 tasks      | elapsed: 12.7min

building tree 284 of 300
building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 13.5min finished

In [48]:
list(zip(tfidf_vectorizer_ps.get_feature_names(),rf_model.feature_importances_))
#print(type(tfidf_vectorizer_ps.get_feature_names()))
#print(type(rf_model.feature_importances_))
features_importances_df=pd.DataFrame(list(zip(tfidf_vectorizer_ps.get_feature_names(),rf_model.feature_importances_)))
features_importances_df.columns = ['feature','importance']

In [118]:
features_importances_df['match']=features_importances_df['feature'].str.match('^[a-zA-Z]+$')
features_importances_df[features_importances_df['match']==True  ][['feature']]

            feature
1412              a
1451             aa
1452            aaa
1454           aaaa
1455         aaaaaa
1456    aaaaaaaargh
1457          aaabc
1458      aaabsolut
1459          aaacc
1460        aaactiv
1461          aaafm
1462     aaafmcomau
1463           aaag
1464           aaba
1465         aabacu
1466           aabp
1467          aacma
1468            aad
1469           aada
1470           aadb
1471       aadvisor
1472            aae
1473          aafrb
1474            aah
1475          aahil
1476            aak
1477         aalcan
1478          aalst
1479          aalto
1480           aama
...             ...
48539         zolli
48540         zombi
48541          zone
48542           zoo
48543       zookeep
48544          zoom
48546       zoomcar
48547        zoozoo
48548         zoran
48549          zorb
48550          zorn
48551        zotech
48552         zouki
48553         zouni
48555            zs
48556           ztl
48557      zubrycki
48558         zumba
48559         zumbo
48560          zuri
48561        zurich
48562           zuu
48563            zv
48564  zvinalukecom
48565        zwirek
48566            zy
48567         zymol
48568         zynam
48569          zzle
48570           zzp

[45974 rows x 1 columns]

In [123]:
top_features_df=features_importances_df.sort_values('importance',ascending =False)[0:40000]
top_features_df[top_features_df['match']==True  ][['feature']].to_csv('features_importances.csv',index=False)
top_features_df

                       feature    importance  match
9155                     clean  1.186558e-02   True
33032                    plumb  8.892218e-03   True
38446                   servic  7.519486e-03   True
1694                   account  7.503087e-03   True
32566              photographi  5.551820e-03   True
14276                   electr  5.514186e-03   True
6336                  bookkeep  5.372179e-03   True
42975                     tile  5.328983e-03   True
7385                      busi  5.209701e-03   True
35938                    renov  4.958713e-03   True
10194                  concret  4.799120e-03   True
31430                    paint  4.708328e-03   True
7130                     build  4.688097e-03   True
34345                   provid  4.673421e-03   True
47006                     work  4.303102e-03   True
17571                   garden  4.255318e-03   True
20279                     home  4.230870e-03   True
15370                   experi  4.154725e-03   True
34085               profession  4.080505e-03   True
10118                   comput  4.021780e-03   True
34731                  qualiti  3.926570e-03   True
35803                    remov  3.811552e-03   True
48165                     year  3.779296e-03   True
23053                      job  3.549585e-03   True
16075                     fenc  3.538984e-03   True
12257                   design  3.524815e-03   True
32343                     pest  3.516169e-03   True
40250                specialis  3.413802e-03   True
42191                      tax  3.402345e-03   True
39659                    small  3.302348e-03   True
...                        ...           ...    ...
45781                      wap  1.788992e-07   True
30200                  nowwith  1.788674e-07   True
12560                 dianella  1.788180e-07   True
21567                 indemand  1.788043e-07   True
48579               çăńjoysçăń  1.787977e-07  False
5477                     benco  1.787819e-07   True
376                        1to  1.787807e-07  False
14813                     eora  1.787804e-07   True
40712                  standup  1.787469e-07   True
47881     wwwthespoiltdogcomau  1.787189e-07   True
9909                     comic  1.787068e-07   True
15563                 extrapol  1.786621e-07   True
4215                  auskleen  1.785826e-07   True
20028                    highr  1.784747e-07   True
17922                 gf015211  1.784713e-07  False
13956                   ec9065  1.784602e-07  False
27451                    mehta  1.783921e-07   True
23821                      kfc  1.783779e-07   True
9454              clientcustom  1.783739e-07   True
47838  wwwstarnowcomkenghumman  1.783178e-07   True
48576                  çăńaçăń  1.782655e-07  False
19242                 hammafit  1.782550e-07   True
46439                    whamp  1.782123e-07   True
42238                tazspoton  1.782086e-07   True
47276                 wurtulla  1.781656e-07   True
28321                   molina  1.781599e-07   True
22286                 invitbox  1.781516e-07   True
37309                    ruffo  1.781322e-07   True
20256            hollingsworth  1.781246e-07   True
19613                     hbia  1.781099e-07   True

[40000 rows x 3 columns]

In [92]:
#features_importances_df.head()
#print(features_importances_df.sort_values('importance',ascending =False)[0:40000])

import_features_list=list(features_importances_df.sort_values('importance',ascending =False)[0:40000]['feature'])
import_features_list

['clean',
 'plumb',
 'servic',
 'account',
 'photographi',
 'electr',
 'bookkeep',
 'tile',
 'busi',
 'renov',
 'concret',
 'paint',
 'build',
 'provid',
 'work',
 'garden',
 'home',
 'experi',
 'profession',
 'comput',
 'qualiti',
 'remov',
 'year',
 'job',
 'fenc',
 'design',
 'pest',
 'specialis',
 'tax',
 'small',
 'photograph',
 'mainten',
 'aspect',
 'repair',
 'construct',
 'need',
 'roof',
 'commerci',
 'celebr',
 'offer',
 'landscap',
 'carpet',
 'cater',
 'ga',
 'wed',
 'move',
 'industri',
 'window',
 'compani',
 'train',
 'fit',
 'bathroom',
 'best',
 'high',
 'detail',
 'custom',
 'makeup',
 'floor',
 'team',
 'includ',
 'new',
 'mechan',
 'reliabl',
 'instal',
 'control',
 'free',
 'mow',
 'tree',
 'lawn',
 'also',
 'ceremoni',
 'person',
 'big',
 'pti',
 'domest',
 'skill',
 'base',
 'ltd',
 'dog',
 'project',
 'client',
 'plaster',
 'rang',
 'air',
 'quot',
 'area',
 'carpentri',
 'solut',
 'massag',
 'call',
 'car',
 'dj',
 'portrait',
 'complet',
 'us',
 'offic',
 'properti',
 'kitchen',
 'price',
 'groom',
 'time',
 'bricklay',
 'insur',
 'wall',
 'conveyanc',
 'builder',
 'cleaner',
 'mobil',
 'friendli',
 'qualifi',
 'event',
 'water',
 'decor',
 'famili',
 'highli',
 'fulli',
 'condit',
 'artist',
 'residenti',
 'help',
 'sydney',
 'interior',
 'melbourn',
 'plumber',
 'make',
 'extens',
 'experienc',
 'marriag',
 'glass',
 'type',
 'special',
 'afford',
 'hous',
 'painter',
 'manag',
 'removalist',
 'oper',
 'captur',
 'product',
 'ba',
 'leas',
 'care',
 'deck',
 'standard',
 'local',
 'guarante',
 'law',
 'hot',
 'financi',
 'gate',
 'look',
 'pride',
 'use',
 'take',
 'taxat',
 'creativ',
 'secur',
 'websit',
 'hi',
 'deliv',
 'print',
 'gutter',
 'avail',
 'workmanship',
 'furnitur',
 'alway',
 'get',
 'drain',
 'coast',
 'pave',
 'requir',
 'gener',
 'cover',
 'web',
 'day',
 'legal',
 'australia',
 'end',
 'agent',
 'rate',
 'leak',
 'pet',
 'highest',
 'wealth',
 'come',
 'attent',
 'own',
 'give',
 'ensur',
 'licens',
 'develop',
 'locksmith',
 'one',
 'waterproof',
 'well',
 'group',
 'full',
 'system',
 'handyman',
 'studio',
 'sign',
 'wide',
 'inspect',
 'firm',
 'architectur',
 'specialist',
 'trade',
 'expert',
 'imag',
 'graphic',
 'driveway',
 'bond',
 'remedi',
 'competit',
 'termit',
 'electrician',
 'prune',
 'brisban',
 'trainer',
 'food',
 'hair',
 'aim',
 'rubbish',
 'pleas',
 'everi',
 'support',
 'knowledg',
 'timber',
 'health',
 'contact',
 'finish',
 'budget',
 'mani',
 'door',
 'restor',
 'great',
 'happi',
 'signag',
 'weight',
 'perth',
 'render',
 'payrol',
 'love',
 'today',
 'individu',
 'satisfact',
 'beauti',
 'lawyer',
 'light',
 'creat',
 'superior',
 'plan',
 'undertak',
 'brick',
 'upholsteri',
 'xero',
 'tiler',
 'done',
 'level',
 'suppli',
 'return',
 'contract',
 'storag',
 'first',
 'moment',
 'contractor',
 'vehicl',
 'block',
 'exterior',
 'owner',
 'drainag',
 'occas',
 'pergola',
 'truck',
 'consult',
 'hedg',
 'auto',
 'myob',
 'pressur',
 'network',
 'digit',
 'problem',
 'run',
 'refriger',
 'retain',
 'name',
 'regist',
 'market',
 'around',
 'meticul',
 'advic',
 'goal',
 'effici',
 'parti',
 'larg',
 'pool',
 'civil',
 'walk',
 'effect',
 'good',
 'style',
 'fix',
 'report',
 'automot',
 'equip',
 'commit',
 'bridal',
 'result',
 'asbesto',
 'data',
 'wash',
 'gold',
 'photo',
 'survey',
 'viru',
 'corpor',
 'right',
 'power',
 'australian',
 'weed',
 'suburb',
 'steam',
 'surround',
 'suit',
 'colour',
 'sinc',
 'bring',
 'carpent',
 'start',
 'heat',
 'function',
 'excav',
 'top',
 'model',
 'estat',
 'south',
 'abl',
 'brand',
 'expos',
 'excel',
 'tow',
 'assist',
 'shop',
 'hire',
 'replac',
 'pc',
 'upgrad',
 'whether',
 'passion',
 'real',
 'locat',
 'outdoor',
 'music',
 'valu',
 'glaze',
 'slab',
 'strength',
 'establish',
 '',
 'expertis',
 'like',
 'staff',
 'solar',
 'acupunctur',
 'session',
 'book',
 'polic',
 'regular',
 'etc',
 'achiev',
 'peopl',
 'safe',
 'nutrit',
 'courier',
 'therapi',
 'dedic',
 'perfect',
 'want',
 'last',
 'onlin',
 'architect',
 'dynam',
 'oblig',
 'alarm',
 'meet',
 'trust',
 'bodi',
 'stone',
 'check',
 'site',
 'cctv',
 'materi',
 'cost',
 'im',
 'laptop',
 'antenna',
 'stump',
 'gasfit',
 'tv',
 'licenc',
 'vow',
 'prompt',
 'back',
 'heater',
 'renew',
 'sale',
 'mind',
 'commun',
 'life',
 'fast',
 'improv',
 'natur',
 'loss',
 'feel',
 'pack',
 'honest',
 'extrem',
 'much',
 'decad',
 'tap',
 'way',
 'within',
 'ceil',
 'class',
 'focu',
 'bin',
 'blockag',
 'earthmov',
 'hour',
 'laundri',
 'reloc',
 'possibl',
 'know',
 'except',
 'entertain',
 'interst',
 'transport',
 'keep',
 'adelaid',
 'let',
 'turf',
 'quotat',
 'go',
 'formal',
 'relax',
 'emerg',
 'find',
 'wast',
 'everyth',
 'chiropract',
 'screen',
 'point',
 'video',
 'cockroach',
 'uniqu',
 'menu',
 'technolog',
 'reason',
 'region',
 'amp',
 'demolit',
 'edg',
 'ceram',
 'safeti',
 'see',
 'addit',
 'treatment',
 'dont',
 'visit',
 'spring',
 'understand',
 'master',
 'live',
 'practic',
 'space',
 'polish',
 'cool',
 'shoot',
 'skip',
 'built',
 'lock',
 'carri',
 'superannu',
 'courteou',
 'salon',
 'charter',
 'across',
 'hard',
 'softwar',
 'strive',
 'panel',
 'past',
 'dri',
 'privat',
 'choos',
 'packag',
 'throughout',
 'featur',
 'would',
 'lead',
 'groomer',
 'sand',
 'inform',
 'porcelain',
 'old',
 'maintain',
 'behaviour',
 'quickbook',
 'technician',
 'trim',
 'media',
 'welcom',
 'cut',
 'sure',
 'clip',
 'metal',
 'hand',
 'cabinet',
 'mover',
 'set',
 'central',
 'perform',
 'access',
 'north',
 'fun',
 'money',
 'anyth',
 'aggreg',
 'follow',
 'stress',
 'windscreen',
 'sunshin',
 'reput',
 'differ',
 'sport',
 'size',
 'footpath',
 'brake',
 'mulch',
 'logo',
 'northern',
 'freelanc',
 'prepar',
 'ant',
 'intern',
 'public',
 'forward',
 'member',
 'innov',
 'satisfi',
 'unit',
 'deliveri',
 'shower',
 'shed',
 'coat',
 'expect',
 'therapist',
 'protect',
 'nsw',
 'kind',
 'easi',
 'engin',
 'card',
 'exercis',
 'purchas',
 'green',
 'patio',
 'import',
 'thing',
 'fashion',
 'western',
 'plant',
 'coach',
 'tailor',
 'medium',
 'clear',
 'will',
 'medicin',
 'process',
 'program',
 'current',
 'believ',
 'varieti',
 'limousin',
 'dream',
 'matter',
 'approach',
 'part',
 'item',
 'seo',
 'place',
 'enjoy',
 'next',
 'garag',
 'frame',
 'mirror',
 'spray',
 'phone',
 'latest',
 'even',
 'long',
 'victoria',
 'number',
 'aircondit',
 'hardwar',
 'choic',
 'art',
 'pipe',
 'artistri',
 'success',
 'leav',
 'warranti',
 'certifi',
 'week',
 'plu',
 'issu',
 'newborn',
 'travel',
 'spider',
 'west',
 'made',
 'memori',
 'agenc',
 'oven',
 'stop',
 'assur',
 'fee',
 'draft',
 'lay',
 'email',
 'combin',
 'onsit',
 'idea',
 'birthday',
 'applianc',
 'room',
 'express',
 'advisori',
 'lifestyl',
 'focus',
 'discount',
 'grow',
 'absolut',
 'pl',
 'land',
 'concept',
 'save',
 'environ',
 'may',
 'coupl',
 'chines',
 'j',
 'grind',
 'brickwork',
 'mc',
 'line',
 'grout',
 'tradesmen',
 'sit',
 'discuss',
 'deal',
 'textur',
 'certif',
 'handl',
 'test',
 'structur',
 'eye',
 'transform',
 'energi',
 'key',
 'banner',
 'readi',
 'recoveri',
 'reconcili',
 'produc',
 'thank',
 'financ',
 'extern',
 'quick',
 'splashback',
 'applic',
 'smaller',
 'modern',
 'switchboard',
 'box',
 'split',
 'peac',
 'touch',
 'damag',
 'log',
 'metro',
 'wa',
 'better',
 'pain',
 'fresh',
 'extra',
 'beach',
 'lamin',
 'boutiqu',
 'receiv',
 'manufactur',
 'tradesman',
 'school',
 'eastern',
 'integr',
 'weekli',
 'associ',
 'queensland',
 'simpl',
 'accredit',
 'colorbond',
 'man',
 'field',
 'arborist',
 'citi',
 'gym',
 'metropolitan',
 'children',
 'board',
 'sell',
 'toilet',
 'request',
 'blind',
 'workshop',
 'naturopath',
 'exist',
 'total',
 'n',
 'yard',
 'personalis',
 'breed',
 'joineri',
 'retail',
 'fitout',
 'second',
 'up',
 'charg',
 'facebook',
 'treat',
 'form',
 'valley',
 'centr',
 'tissu',
 'puppi',
 'newcastl',
 'trustworthi',
 'pre',
 'tidi',
 'complianc',
 'without',
 'intercom',
 'gyprock',
 'prioriti',
 'close',
 'bobcat',
 'nail',
 'partner',
 'smash',
 'solid',
 'refer',
 'engag',
 'tint',
 'flexibl',
 'horticultur',
 'east',
 'array',
 'premium',
 'cement',
 'deep',
 'internet',
 'chang',
 'strong',
 'turn',
 'co',
 'liabil',
 'serv',
 'stylist',
 'award',
 'select',
 'memor',
 'transact',
 'limit',
 'lot',
 'park',
 'put',
 'respons',
 'crimin',
 'option',
 'major',
 'specif',
 'yr',
 'comprehens',
 'almost',
 'pt',
 'vacat',
 'environment',
 'open',
 'repaint',
 'organis',
 'solicitor',
 'blue',
 'stain',
 'pro',
 'hill',
 'social',
 'seal',
 'main',
 'specialti',
 '20yr',
 'steel',
 'qld',
 'arrang',
 'relationship',
 'machin',
 'smsf',
 'direct',
 'film',
 'anim',
 'setup',
 'rodent',
 'none',
 'john',
 'proud',
 'vinyl',
 'rug',
 'advertis',
 'world',
 'fair',
 'away',
 'sector',
 'advanc',
 'alter',
 'mean',
 'two',
 'mark',
 'show',
 'camera',
 'invest',
 'patch',
 'lifetim',
 'irrig',
 'cabl',
 'chemic',
 'togeth',
 'cpa',
 'document',
 'switch',
 'page',
 'peninsula',
 'disco',
 'connect',
 'server',
 'comfort',
 'star',
 'c',
 'vacuum',
 'scaffold',
 'sound',
 'low',
 'mac',
 'track',
 'fabric',
 'host',
 'stori',
 'app',
 'littl',
 'buy',
 'out',
 'continu',
 'lop',
 'list',
 'marbl',
 'confid',
 'vision',
 'allow',
 'beyond',
 'your',
 'ask',
 'weld',
 'regard',
 'rest',
 'view',
 'countri',
 'respect',
 'manner',
 'flat',
 'along',
 'canberra',
 'wire',
 'promot',
 'videographi',
 'flyer',
 'involv',
 'date',
 'sole',
 'self',
 'mattress',
 'tri',
 'hear',
 'council',
 'win',
 'hold',
 'hesit',
 'question',
 'duct',
 'david',
 'factori',
 'simpli',
 'portraitur',
 'measur',
 'conveni',
 'consist',
 'white',
 'holiday',
 'rental',
 'whole',
 'sewer',
 'abn',
 'clinic',
 'record',
 'stand',
 'fortnightli',
 'tech',
 'think',
 'friend',
 'outstand',
 'sustain',
 'order',
 'search',
 'appli',
 'basic',
 'premis',
 'excit',
 'ever',
 'insid',
 'abil',
 'desktop',
 'minor',
 'cat',
 'approv',
 'brochur',
 'outcom',
 'strata',
 'user',
 'advis',
 'present',
 'per',
 'compet',
 'ive',
 'recommend',
 'swim',
 'cornic',
 'pension',
 'smoke',
 'partnership',
 'exceed',
 'method',
 'pay',
 'chef',
 'visual',
 'premier',
 'accur',
 'apart',
 'downpip',
 'optimis',
 'mission',
 'makeov',
 'limeston',
 'michael',
 'face',
 'punctual',
 'employ',
 'tool',
 'amaz',
 'supplier',
 'r',
 'techniqu',
 'tradit',
 'greater',
 'desir',
 'appoint',
 'treasur',
 'luxuri',
 'curtain',
 'aluminium',
 'state',
 'smart',
 'step',
 'spa',
 'matern',
 'ecommerc',
 'b',
 'led',
 'southern',
 'motor',
 'geelong',
 'nation',
 'age',
 'stencil',
 'pregnanc',
 ...]

In [20]:
QUERY = """ 
SELECT
bm.id
,trim(nvl(bm.name,'') || ' ' || nvl(description,'')) "feature"
FROM oneflare_reports.business_master bm
WHERE bm.total_quotes_made < 3
"""

In [21]:
data_to_predict=pd.read_sql(QUERY,redshift)

In [22]:
data_to_predict.head()

,id,feature
0,94,Royal Flush Flooring
1,113,Barwon Electrical Services Barwon Electrical Services is a friendly Electrical business with a w...
2,231,Blitz Floors And Blinds Blitz Blinds is a family owned local business which has been established...
3,235,Edwards Interiors Domestic & Commercial Supply & installation of\r\n*Plasterboard & Cornices\r\n...
4,333,Zac's Home Insulation Zac's Home Insulation is an Australian owned and operated company providin...

In [28]:
#tfidf_vectorizer_ps = TfidfVectorizer(analyzer=clean_text_by_porter_stem)
tfidf_vectorized_matrix_to_predict_ps = tfidf_vect_fit.transform(data_to_predict['feature'] )

In [29]:
y_to_predict = rf_model.predict(tfidf_vectorized_matrix_to_predict_ps)

[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:    0.7s
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    1.2s
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    1.7s
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    2.4s
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    3.4s
[Parallel(n_jobs=4)]: Done  53 tasks      | elapsed:    6.4s
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:    9.7s
[Parallel(n_jobs=4)]: Done  77 tasks      | elapsed:   12.0s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:   12.9s
[Parallel(n_jobs=4)]: Done 105 tasks      | elapsed:   15.7s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:   18.5s
[Parallel(n_jobs=4)]: Done 137 tasks      | elapsed:   21.0s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   24.3s
[Parallel(n_jobs=4)]: Done 173 tasks      | elapsed:   26.6s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:   30.3s
[Parallel(n_jobs=4)]: Done 213 tasks      | elapsed:   33.4s
[Parallel(n_jobs=4)]: Done 234 tasks      | elapsed:   36.6s
[Parallel(n_jobs=4)]: Done 257 tasks      | elapsed:   40.6s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:   43.7s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:   45.8s finished

In [30]:
data_to_predict['predited_category'] = y_to_predict

In [31]:
data_to_predict.to_csv('predited_category.csv',index=False)

In [34]:
pd.set_option('display.max_colwidth', -1)
data_to_predict.head()

,id,feature,predited_category
0,94,Royal Flush Flooring,Concreting
1,113,Barwon Electrical Services Barwon Electrical Services is a friendly Electrical business with a wealth of experience that can cater for all your commercial and domestic electrical needs.\nCover all aspects of electrical from new homes and developments through to smaller jobs and general maintenance.\nOur professional and courteous service ensures you that all our work is completed to the highest standard at affordable rates.,Home Appliance Repair
2,231,"Blitz Floors And Blinds Blitz Blinds is a family owned local business which has been established for the past 15 years servicing the Western suburbs of Victoria with quality blinds. \r\n\r\nWe specialise in the supply and installation of quality custom made to measure blinds and curtains.\r\n\r\nBlitz Floors and Blinds offer the ultimate in quality and style for all your Drapes, Pelmets, Holland, E- screen, Shutters, Romans, Timber, Venetians and Swags and Tails.\r\n\r\nTo build a successful business, you need to understand how important existing customers are and the importance of creating new long term customers. \r\nWe strive to offer the highest levels of quality products & commitment to our customers with the best service, workmanship and price guaranteed.\r\n\r\nWe provide our customers with:\r\nFree Measure and quote\r\nFree Consultation\r\nWe come to you\r\nExpert Advice\r\nServicing all Suburbs",Flooring
3,235,Edwards Interiors Domestic & Commercial Supply & installation of\r\n*Plasterboard & Cornices\r\n*Suspended Ceilings\r\n*Partition Systems\r\n*Fire rated Systems & Insulation\r\n*Demolition & Waste removal,Rubbish Removal
4,333,Zac's Home Insulation Zac's Home Insulation is an Australian owned and operated company providing high quality insulation for your home or business.,Builder

In [32]:
from sklearn.externals import joblib
joblib.dump(rf_model, 'random_forest.pkl') 
#clf = joblib.load('filename.pk1')

['random_forest.pkl']

In [35]:
len(data_to_predict)

33373